/**
 * This file is auto-generated by protobufgen
 * Don't change manually
 */

export enum TriBool {
	TriBoolNone = "TriBoolNone",
	TriBoolTrue = "TriBoolTrue",
	TriBoolFalse = "TriBoolFalse"
}

export interface Bytes {
	data: string;
}

export interface Strings {
	value: string[];
}

export interface Bools {
	value: boolean[];
}

export interface Int32 {
	value: number[];
}

export interface Doubles {
	value: number[];
}

export interface I64Range {
	/**
	 * @pattern ^\d+$
	 */
	from: string;
	/**
	 * @pattern ^\d+$
	 */
	to: string;
}
