/**
 * This file is auto-generated by protobufgen
 * Don't change manually
 */

import { Duration as CommonDuration } from "../common/time";

export interface WebapiOption {
	enable: boolean;
	disable: boolean;
	upload: boolean;
	download: boolean;
	get: boolean;
	interactive: boolean;
}

export interface AuthOption {
	user: boolean;
	admin: boolean;
	allowService: string[];
}

export interface ServiceOption {
	webapi: boolean;
	public: boolean;
	admin: boolean;
	cacheMemoryLimit: string;
}

export interface ServiceOpDesc {
	name: string;
	option: ServiceOption;
	methods: MethodOpDesc[];
}

export interface MethodOpDesc {
	name: string;
	webapi: WebapiOption;
	auth: AuthOption;
	timeout: CommonDuration;
	isClientStreaming: boolean;
	isServerStreaming: boolean;
	cache: InterfaceCacheOpDesc;
}

export interface InterfaceCacheOpDesc {
	enableClientSideCache: boolean;
	enableServerSideCache: boolean;
	cacheExpired: string;
}

export interface MessageOpDesc {

}

export interface StringValidator {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	minLen: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	maxLen: number;
	in: string[];
	regex: string;
}