/**
 * This file is auto-generated by protobufgen
 * Don't change manually
 */

import { Strings as CommonStrings } from "../common/common";

export interface File {
	header: FileHeader;
	data: string;
}

export interface FileHeader {
	filename: string;
	mime: {[key: string]: CommonStrings};
}