/**
 * This file is auto-generated by protobufgen
 * Don't change manually
 */



export interface Time {
	/**
	 * @pattern ^\d+$
	 */
	seconds: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	nanos: number;
}

export interface Duration {
	/**
	 * @pattern ^\d+$
	 */
	nanos: string;
}