/**
 * This file is auto-generated by protobufgen
 * Don't change manually
 */

import { File as CommonFile } from "../common/file";
import webapi from "../webapi";

export enum TraceOp {
	TraceOpReset = "TraceOpReset",
	TraceOpSet = "TraceOpSet",
	TraceOpGet = "TraceOpGet"
}

export enum ReduceOp {
	ReduceValue = "ReduceValue",
	ReducePercent = "ReducePercent"
}

export enum ServiceType {
	ServiceTypeAll = "ServiceTypeAll",
	ServiceTypeEzbuy = "ServiceTypeEzbuy",
	ServiceTypeBuyForMe = "ServiceTypeBuyForMe",
	ServiceTypeShipForMe = "ServiceTypeShipForMe",
	ServiceTypePrime = "ServiceTypePrime"
}

export enum ProductOriginCode {
	OriginCodeAll = "OriginCodeAll",
	OriginCodeCN = "OriginCodeCN",
	OriginCodeUS = "OriginCodeUS",
	OriginCodeTW = "OriginCodeTW",
	OriginCodeKR = "OriginCodeKR"
}

export enum ClientType {
	ClientTypeAll = "ClientTypeAll",
	ClientTypeWWW = "ClientTypeWWW",
	ClientTypeApp = "ClientTypeApp",
	ClientTypeMobile = "ClientTypeMobile"
}

export enum ProductPlatform {
	PlatformAll = "PlatformAll",
	PlatformUnknow = "PlatformUnknow",
	PlatformCNEzseller = "PlatformCNEzseller",
	PlatformTaobao = "PlatformTaobao",
	PlatformJD = "PlatformJD",
	PlatformMogujie = "PlatformMogujie",
	PlatformChuchujie = "PlatformChuchujie",
	PlatformCNOther = "PlatformCNOther",
	PlatformJDLocal = "PlatformJDLocal",
	PlatformJDNotLocal = "PlatformJDNotLocal",
	PlatformVip = "PlatformVip",
	PlatformUSEzseller = "PlatformUSEzseller",
	PlatformAmazon = "PlatformAmazon",
	PlatformUSOther = "PlatformUSOther",
	PlatformTWAll = "PlatformTWAll",
	PlatformKRAll = "PlatformKRAll",
	PlatformKREzseller = "PlatformKREzseller"
}

export enum DiscountKind {
	DiscountKindShippingFee = "DiscountKindShippingFee",
	DiscountKindAgentFee = "DiscountKindAgentFee"
}

export enum RuleType {
	RuleTypeUnKnow = "RuleTypeUnKnow",
	RuleTypeFullCut = "RuleTypeFullCut",
	RuleTypeDiscount = "RuleTypeDiscount",
	RuleTypeCouponCode = "RuleTypeCouponCode",
	RuleTypeWrapFullCut = "RuleTypeWrapFullCut",
	RuleTypeRedPacket = "RuleTypeRedPacket",
	RuleTypeAgentFeeVoucher = "RuleTypeAgentFeeVoucher",
	RuleTypeMNCashOff = "RuleTypeMNCashOff",
	RuleTypeShippingFeeVoucher = "RuleTypeShippingFeeVoucher",
	RuleTypeFreeShippingExt = "RuleTypeFreeShippingExt"
}

export enum ProductType {
	IsFun = "IsFun",
	IsProduct = "IsProduct"
}

export enum FunType {
	ViewType = "ViewType",
	ConditionType = "ConditionType",
	ActionType = "ActionType"
}

export enum FieldFlag {
	Normal = "Normal",
	ForBid = "ForBid",
	Hidden = "Hidden"
}

export enum FieldType {
	Float64Type = "Float64Type",
	StringType = "StringType",
	BoolType = "BoolType",
	ArrayType = "ArrayType"
}

export enum CouponKind {
	CouponKindUnKnow = "CouponKindUnKnow",
	CouponKindFullCut = "CouponKindFullCut",
	CouponKindDiscount = "CouponKindDiscount",
	CouponKindRedPacket = "CouponKindRedPacket",
	CouponKindShipping = "CouponKindShipping"
}

export enum ActType {
	Other = "Other",
	FullCutType = "FullCutType",
	FreeShipping = "FreeShipping",
	CouponType = "CouponType",
	DiscountType = "DiscountType",
	RedPacketType = "RedPacketType",
	AgentFeeVoucherType = "AgentFeeVoucherType",
	MNCashOffType = "MNCashOffType",
	ShippingFeeVoucherType = "ShippingFeeVoucherType",
	FastDeliveryType = "FastDeliveryType",
	FreeShippingExt = "FreeShippingExt"
}

export enum ActStatus {
	Unknow = "Unknow",
	UnOpen = "UnOpen",
	Prepare = "Prepare",
	Opening = "Opening",
	Closed = "Closed"
}

export enum ChargeType {
	ChargeUnknow = "ChargeUnknow",
	Weight = "Weight",
	TotalWeight = "TotalWeight",
	ProductPrice = "ProductPrice",
	TotalPrice = "TotalPrice",
	ProductShippingFee = "ProductShippingFee",
	ProductAgentFee = "ProductAgentFee",
	TotalShippingFee = "TotalShippingFee",
	TotalAgentFee = "TotalAgentFee"
}

export interface ActivityDiscountTag {
	actId: string;
}

export interface ActivityDiscountTagResp {}

export interface ActivityDeleteProductsByExcel {
	actId: string;
	file: CommonFile;
}

export interface ActivityDeleteProductsByExcelResp {}

export interface ActivityTrace {
	op: TraceOp;
	trace: TraceInfo;
}

export interface ActivityTraceResp {
	trace: TraceInfo;
}

export interface TraceInfo {
	logLevel: string;
	/**
	 * @pattern ^\d+$
	 */
	customerId: string;
}

export interface ActivityUsedActsByTime {
	actId: string;
	/**
	 * @pattern ^\d+$
	 */
	time: string;
	catalog: string;
}

export interface ActivityUsedActsByTimeResp {
	acts: string[];
}

export interface ActivityActChangeLog {
	actId: string;
}

export interface ActivityActChangeLogResp {
	acts: ActChangeLog[];
}

export interface ActChangeLog {
	id: string;
	name: string;
	actId: string;
	startTime: string;
	endTime: string;
	createTime: string;
	UpdateTime: string;
	DeleteTime: string;
}

export interface ActivityMultiTriggerByTime {
	triggers: TriggerReq[];
}

export interface ActivityMultiTriggerByTimeResp {
	resp: TriggerResp[];
}

export interface ActivityGetFullCutUrl {
	/**
	 * @pattern ^\d+$
	 */
	typeIds: string[];
	ruleIds: string[];
}

export interface ActivityGetFullCutUrlResp {
	urls: string[];
}

export interface ActivityGetSpecActByZoneKey {
	zoneKey: string;
}

export interface ActivityGetSpecActByZoneKeyResp {
	act: SpecAct;
}

export interface ActivityChangeRuleTime {
	ruleId: string;
	/**
	 * @pattern ^\d+$
	 */
	startTime: string;
	/**
	 * @pattern ^\d+$
	 */
	endTime: string;
}

export interface ActivityChangeRuleTimeResp {}

export interface ActivityGetShipmentBy {
	catalog: string;
	originCode: ProductOriginCode[];
	catalogs: string[];
}

export interface ActivityGetShipmentByResp {
	shipments: Shipment[];
}

export interface Shipment {
	name: string;
	value: string;
}

export interface ActivityUpdateSpecAct {
	act: SpecAct;
	updateBy: string;
}

export interface ActivityUpdateSpecActResp {
	actId: string;
	ruleId: string;
}

export interface ActivityListSpecAct {
	filter: ActFilter;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	limit: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	offset: number;
}

export interface ActivityListSpecActResp {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	total: number;
	acts: SpecAct[];
}

export interface SpecAct {
	act: ActDetail;
	rule: Rule;
}

export interface ActivityBindRule {
	actId: string;
	ruleIds: string[];
}

export interface ActivityBindRuleResp {
	actId: string;
}

export interface ActivityAddRule {
	actId: string;
	rule: Rule;
}

export interface FullCutRule {
	/**
	 * @pattern ^\d+$
	 */
	fullAmount: string;
	/**
	 * @pattern ^\d+$
	 */
	cutAmount: string;
	desc: string;
	serviceTypes: ServiceType[];
}

export interface AgentFeeVoucherRule {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	discount: number;
	desc: string;
	serviceTypes: ServiceType[];
	vendorNames: string[];
	platforms: ProductPlatform[];
	originCodes: ProductOriginCode[];
}

export interface CouponCodeRule {
	name: string;
	desc: string;
	serviceType: ServiceType[];
	originCode: ProductOriginCode[];
	catalog: string;
	shipments: string[];
	/**
	 * @pattern ^\d+$
	 */
	startTime: string;
	/**
	 * @pattern ^\d+$
	 */
	endTime: string;
	reduceType: ReduceOp;
	/**
	 * @pattern ^\d+$
	 */
	reduce: string;
	/**
	 * @pattern ^\d+$
	 */
	maxReduce: string;
	isAvailable: boolean;
	/**
	 * @pattern ^\d+$
	 */
	maxUseTimes: string;
}

export interface WrapFullCutRule {
	zoneKey: string;
	color: string;
	rules: { [key: string]: CatalogFullCut };
}

export interface CatalogFullCut {
	ruleIds: string[];
	rules: Rule[];
	desc: string;
	link: string;
}

export interface RedPacketRule {
	name: string;
	desc: string;
	needFirstUse: boolean;
	serviceTypes: ServiceType[];
	/**
	 * @pattern ^\d+$
	 */
	minPrice: string;
	/**
	 * @pattern ^\d+$
	 */
	redPrice: string;
}

export interface DiscountRuleDcid {
	dcid: number[];
}

export interface DiscountRule {
	kind: DiscountKind;
	name: string;
	serviceTypes: ServiceType[];
	clients: ClientType[];
	originCodes: ProductOriginCode[];
	shipments: string[];
	vendorNames: string[];
	platforms: ProductPlatform[];
	reduceType: ReduceOp;
	isNew: boolean;
	/**
	 * @pattern ^\d+$
	 */
	reduce: string;
	/**
	 * @pattern ^\d+$
	 */
	maxReduce: string;
	isAvailable: boolean;
	data: string;
	allDcids: number[];
	dcids: number[];
	tagImg: string;
	appImg: string;
	imgDesc: string;
	desc: string;
	link: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	minLimit: number;
}

export interface MNCashOffRule {
	name: string;
	/**
	 * @pattern ^\d+$
	 */
	startTime: string;
	/**
	 * @pattern ^\d+$
	 */
	endTime: string;
	desc: string;
	descTH: string;
	link: string;
	tagImg: string;
	steps: MNCashOffStep[];
}

export interface MNCashOffStep {
	reduceType: ReduceOp;
	/**
	 * @pattern ^\d+$
	 */
	reduce: string;
	/**
	 * @pattern ^\d+$
	 */
	fullAmount: string;
}

export interface ShippingFeeVoucherRule {
	name: string;
	desc: string;
	serviceTypes: ServiceType[];
	originCodes: ProductOriginCode[];
	shipments: string[];
	vendorNames: string[];
	platforms: ProductPlatform[];
	isNew: boolean;
	/**
	 * @pattern ^\d+$
	 */
	reduce: string;
	/**
	 * @pattern ^\d+$
	 */
	fullAmount: string;
}

export interface FreeShippingExtRule {
	desc: string;
	img: string;
	/**
	 * @pattern ^\d+$
	 */
	SG: string;
	SGDesc: string;
	SGDescLink: string;
	/**
	 * @pattern ^\d+$
	 */
	MY: string;
	MYDesc: string;
	MYDescLink: string;
	/**
	 * @pattern ^\d+$
	 */
	TH: string;
	THDesc: string;
	THDescLink: string;
	isSeaShipping: boolean;
}

export interface Rule {
	RuleId: string;
	ruleType: RuleType;
	fullCutRule: FullCutRule;
	discountRule: DiscountRule;
	couponCodeRule: CouponCodeRule;
	wrapFullCut: WrapFullCutRule;
	redPacket: RedPacketRule;
	agentFee: AgentFeeVoucherRule;
	MNCashOff: MNCashOffRule;
	shippingFee: ShippingFeeVoucherRule;
	freeshippingExt: FreeShippingExtRule;
}

export interface ActivityAddRuleResp {
	ruleId: string;
}

export interface ActivityGetRule {
	ruleId: string;
}

export interface ActivityGetRuleResp {
	rule: Rule;
}

export interface ActivityGetActInfo {
	/**
	 * @pattern ^\d+$
	 */
	gpid: string;
	client: string;
	catalog: string;
	actId: string;
}

export interface ActivityGetActInfoResp {
	acts: ActInfo[];
}

export interface ProductId {
	/**
	 * @pattern ^\d+$
	 */
	gpid: string;
	actIds: string[];
}

export interface ActivityMultiGetActInfo {
	/**
	 * @pattern ^\d+$
	 */
	gpids: string[];
	ids: ProductId[];
	client: string;
	catalog: string;
}

export interface ActivityMultiGetActInfoResp {
	prodActs: ProductActInfo[];
}

export interface ProductActInfo {
	/**
	 * @pattern ^\d+$
	 */
	gpid: string;
	acts: ActInfo[];
}

export interface ActivityImportExcel {
	actId: string;
	file: CommonFile;
}

export interface ErrorGpid {
	/**
	 * @pattern ^\d+$
	 */
	gpid: string;
	reason: string;
}

export interface ActivityImportExcelResp {
	errGpids: ErrorGpid[];
	url: string;
}

export interface ActivityGetProducts {
	actId: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	offset: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	limit: number;
	productURL: string;
	productName: string;
}

export interface ActivityGetProductsResp {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	total: number;
	products: ProductDetail[];
}

export interface ProductDetail {
	image: string;
	name: string;
	/**
	 * @pattern ^\d+$
	 */
	gpid: string;
	productURL: string;
}

export interface ActivityGetConfByType {
	type: ActType;
}

export interface ActivityGetConfByTypeResp {
	views: string[];
	conds: string[];
	actions: string[];
}

export interface ActivityGetFunConf {
	type: FunType;
	funName: string;
}

export interface ActivityGetFunConfResp {
	fields: FieldDesc[];
}

export interface FieldDesc {
	name: string;
	key: string;
	type: FieldType;
	flags: FieldFlag[];
	defaults: string[];
}

export interface ActivityList {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	offset: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	limit: number;
	filter: ActFilter;
	sort: string;
}

export interface ActivityListResp {
	acts: ActDetail[];
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	total: number;
}

export interface ActFilter {
	actIds: string[];
	actType: ActType;
	isAvaliable: boolean;
	catalogs: string[];
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	ruleIdNum: number;
	isCurrent: boolean;
	name: string;
}

export interface ActDetail {
	actId: string;
	actName: string;
	actType: ActType;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	startTime: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	endTime: number;
	ruleIds: string[];
	catalogs: string[];
	cond: Condition;
	actions: Action[];
	view: View;
	desc: ActDesc;
}

export interface ActDesc {
	goal: string;
	expectedResult: string;
	principal: string;
	desc: string;
}

export interface ActivityUpdate {
	act: ActDetail;
	isNew: boolean;
}

export interface ActivityUpdateResp {
	actId: string;
}

export interface ActivityReload {
	actId: string;
	isReloadProduct: boolean;
}

export interface ActivityReloadResp {}

export interface ActivityDeleteProducts {
	actId: string;
	/**
	 * @pattern ^\d+$
	 */
	gpids: string[];
	pds: Product[];
	notNotify: boolean;
}

export interface ActivityDeleteProductsResp {
	errInfo: DeleteProductsError[];
}

export interface DeleteProductsError {
	pd: Product;
	reason: string;
}

export interface ActivityGetActByType {
	actType: ActType;
}

export interface ActivityGetActByTypeResp {
	acts: ActInfo[];
}

export interface ActivityAddProducts {
	actId: string;
	products: Product[];
}

export interface ActivityAddProductsResp {}

export interface ActivityDelete {
	actId: string;
}

export interface ActivityDeleteResp {}

export interface ActivityImport {
	actId: string;
	/**
	 * @pattern ^\d+$
	 */
	gpids: string[];
	productURL: string[];
}

export interface ActivityImportResp {
	/**
	 * @pattern ^\d+$
	 */
	errGpids: string[];
	reason: string[];
}

export interface ActivityReduceProductStock {
	actId: string;
	/**
	 * @pattern ^\d+$
	 */
	gpid: string;
	skuId: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	value: number;
}

export interface ActivityReduceProductStockResp {
	isSucc: boolean;
	msg: string;
}

export interface ActivityAddProductStock {
	actId: string;
	/**
	 * @pattern ^\d+$
	 */
	gpid: string;
	skuId: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	value: number;
}

export interface ActivityAddProductStockResp {
	isSucc: boolean;
	msg: string;
}

export interface ActivityCreate {
	actName: string;
	actType: ActType;
	times: ActTime[];
	actions: Action[];
	condition: Condition;
	view: View;
}

export interface ActivityCreateResp {
	isSucc: boolean;
	actId: string;
}

export interface ActivityGetActIdsByProduct {
	/**
	 * @pattern ^\d+$
	 */
	gpid: string;
	skuIds: string[];
}

export interface ActivityGetActIdsByProductResp {
	actInfos: ProductAct[];
}

export interface TriggerReq {
	customer: CustomerInfo;
	products: ProductInfo[];
	totalCharge: Charge[];
	/**
	 * @pattern ^\d+$
	 */
	time: string;
}

export interface TriggerResp {
	productDiscount: DiscountInfo[];
	globalDiscount: Discount[];
	couponInfo: CouponDetail;
	useCouponCode: string;
	/**
	 * @pattern ^\d+$
	 */
	time: string;
}

export interface ActUseCoupon {
	actInfo: ActInfo;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	idx: number;
}

export interface CouponDetail {
	fullCuts: FullCutCoupon[];
	fullCutUse: ActUseCoupon[];
	coupons: CouponInfo[];
	use: ActUseCoupon[];
}

export interface Coupon {
	fullCuts: FullCutCoupon[];
	fullCutCur: number[];
	coupons: CouponInfo[];
	use: number[];
}

export interface FullCutCoupon {
	/**
	 * @pattern ^\d+$
	 */
	couponId: string;
	ruleId: string;
	/**
	 * @pattern ^\d+$
	 */
	voucherTypeId: string;
	/**
	 * @pattern ^\d+$
	 */
	fullAmount: string;
	/**
	 * @pattern ^\d+$
	 */
	cutAmount: string;
	isAvailable: boolean;
}

export interface CouponInfo {
	ruleId: string;
	kind: CouponKind;
	isAvailable: boolean;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	useTimes: number;
}

export interface ActivityPing {
	Msg: string;
}

export interface ActivityPingResp {
	Msg: string;
}

export interface Action {
	type: string;
	value: string;
}

export interface Trigger {
	name: string;
	combineType: string;
	leftNode: Trigger;
	rightNode: Trigger;
	condition: Condition;
}

export interface Condition {
	name: string;
	type: string;
	value: string;
}

export interface View {
	name: string;
	type: string;
	value: string;
}

export interface ActTime {
	/**
	 * @pattern ^\d+$
	 */
	startTime: string;
	/**
	 * @pattern ^\d+$
	 */
	endTime: string;
	status: ActStatus;
}

export interface Product {
	/**
	 * @pattern ^\d+$
	 */
	gpid: string;
	sku: Sku[];
}

export interface Sku {
	skuId: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	stock: number;
}

export interface ProductAct {
	actId: string;
	status: ActStatus;
	skus: Sku[];
}

export interface ProductSku {
	/**
	 * @pattern ^\d+$
	 */
	gpid: string;
	skuId: string;
}

export interface CustomerInfo {
	/**
	 * @pattern ^\d+$
	 */
	customerId: string;
	catalog: string;
	coupon: Coupon;
	client: string;
	gradeCode: string;
	couponCode: CouponCode;
}

export interface CouponCode {
	code: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	useTimes: number;
}

export interface ProductInfo {
	productSku: ProductSku;
	/**
	 * @pattern ^\d+$
	 */
	quantity: string;
	originCode: string;
	shipmentType: string;
	serviceType: ServiceType;
	charge: Charge[];
	chargeMap: { [key: string]: string };
}

export interface Charge {
	chargeType: ChargeType;
	/**
	 * @pattern ^\d+$
	 */
	chargePrice: string;
}

export interface DiscountInfo {
	product: ProductSku;
	discount: Discount[];
}

export interface Discount {
	actInfo: ActInfo;
	isAvaliable: boolean;
	chargeType: ChargeType;
	/**
	 * @pattern ^\d+$
	 */
	price: string;
}

export interface ExtraData {
	cashoff: CashOffExt;
	MNCashoff: MNCashOffExt;
	fastDelivery: FastDeliveryExt;
	discount: DiscountExt;
	freeShippingExt: FreeShippingViewExt;
}

export interface CashOffExt {
	cashOffKey: string;
	color: string;
}

export interface MNCashOffExt {
	tagImg: string;
	BITag: string;
}

export interface FastDeliveryExt {
	icon: string;
	desc: string;
	banner: string;
}

export interface DiscountExt {
	img: string;
	desc: string;
}

export interface FreeShippingViewExt {
	img: string;
	desc: string;
	isSeaShipping: boolean;
}

export interface ActInfo {
	actId: string;
	actName: string;
	actType: ActType;
	desc: string;
	descLink: string;
	extraData: ExtraData;
	/**
	 * @pattern ^\d+$
	 */
	startTime: string;
	/**
	 * @pattern ^\d+$
	 */
	endTime: string;
	catalogs: string[];
}

export function Ping(payload: Partial<ActivityPing>) {
	return webapi<ActivityPingResp>("activity.Activity/Ping", payload);
}

export function GetActInfo(payload: Partial<ActivityGetActInfo>) {
	return webapi<ActivityGetActInfoResp>("activity.Activity/GetActInfo", payload);
}

export function MultiGetActInfo(payload: Partial<ActivityMultiGetActInfo>) {
	return webapi<ActivityMultiGetActInfoResp>("activity.Activity/MultiGetActInfo", payload);
}

export function MultiGetActInfoByCache(payload: Partial<ActivityMultiGetActInfo>) {
	return webapi<ActivityMultiGetActInfoResp>("activity.Activity/MultiGetActInfoByCache", payload);
}

export function ImportExcel(payload: Partial<ActivityImportExcel>) {
	return webapi<ActivityImportExcelResp>("activity.Activity/ImportExcel", payload);
}

export function ImportFile(payload: Partial<ActivityImportExcel>) {
	return webapi<ActivityImportExcelResp>("activity.Activity/ImportFile", payload);
}

export function GetProducts(payload: Partial<ActivityGetProducts>) {
	return webapi<ActivityGetProductsResp>("activity.Activity/GetProducts", payload);
}

export function GetConfByType(payload: Partial<ActivityGetConfByType>) {
	return webapi<ActivityGetConfByTypeResp>("activity.Activity/GetConfByType", payload);
}

export function GetFunConf(payload: Partial<ActivityGetFunConf>) {
	return webapi<ActivityGetFunConfResp>("activity.Activity/GetFunConf", payload);
}

export function List(payload: Partial<ActivityList>) {
	return webapi<ActivityListResp>("activity.Activity/List", payload);
}

export function Update(payload: Partial<ActivityUpdate>) {
	return webapi<ActivityUpdateResp>("activity.Activity/Update", payload);
}

export function DeleteProducts(payload: Partial<ActivityDeleteProducts>) {
	return webapi<ActivityDeleteProductsResp>("activity.Activity/DeleteProducts", payload);
}

export function DeleteProductsByExcel(payload: Partial<ActivityDeleteProductsByExcel>) {
	return webapi<ActivityDeleteProductsByExcelResp>(
		"activity.Activity/DeleteProductsByExcel",
		payload
	);
}

export function GetActByType(payload: Partial<ActivityGetActByType>) {
	return webapi<ActivityGetActByTypeResp>("activity.Activity/GetActByType", payload);
}

export function Delete(payload: Partial<ActivityDelete>) {
	return webapi<ActivityDeleteResp>("activity.Activity/Delete", payload);
}

export function Trigger(payload: Partial<TriggerReq>) {
	return webapi<TriggerResp>("activity.Activity/Trigger", payload);
}

export function TriggerByTime(payload: Partial<TriggerReq>) {
	return webapi<TriggerResp>("activity.Activity/TriggerByTime", payload);
}

export function MultiTriggerByTime(payload: Partial<ActivityMultiTriggerByTime>) {
	return webapi<ActivityMultiTriggerByTimeResp>("activity.Activity/MultiTriggerByTime", payload);
}

export function Create(payload: Partial<ActivityCreate>) {
	return webapi<ActivityCreateResp>("activity.Activity/Create", payload);
}

export function GetActIdsByProduct(payload: Partial<ActivityGetActIdsByProduct>) {
	return webapi<ActivityGetActIdsByProductResp>("activity.Activity/GetActIdsByProduct", payload);
}

export function ReduceProductStock(payload: Partial<ActivityReduceProductStock>) {
	return webapi<ActivityReduceProductStockResp>("activity.Activity/ReduceProductStock", payload);
}

export function AddProductStock(payload: Partial<ActivityAddProductStock>) {
	return webapi<ActivityAddProductStockResp>("activity.Activity/AddProductStock", payload);
}

export function Import(payload: Partial<ActivityImport>) {
	return webapi<ActivityImportResp>("activity.Activity/Import", payload);
}

export function AddRule(payload: Partial<ActivityAddRule>) {
	return webapi<ActivityAddRuleResp>("activity.Activity/AddRule", payload);
}

export function GetRule(payload: Partial<ActivityGetRule>) {
	return webapi<ActivityGetRuleResp>("activity.Activity/GetRule", payload);
}

export function BindRule(payload: Partial<ActivityBindRule>) {
	return webapi<ActivityBindRuleResp>("activity.Activity/BindRule", payload);
}

export function ListSpecAct(payload: Partial<ActivityListSpecAct>) {
	return webapi<ActivityListSpecActResp>("activity.Activity/ListSpecAct", payload);
}

export function UpdateSpecAct(payload: Partial<ActivityUpdateSpecAct>) {
	return webapi<ActivityUpdateSpecActResp>("activity.Activity/UpdateSpecAct", payload);
}

export function GetShipmentBy(payload: Partial<ActivityGetShipmentBy>) {
	return webapi<ActivityGetShipmentByResp>("activity.Activity/GetShipmentBy", payload);
}

export function ChangeRuleTime(payload: Partial<ActivityChangeRuleTime>) {
	return webapi<ActivityChangeRuleTimeResp>("activity.Activity/ChangeRuleTime", payload);
}

export function GetSpecActByZoneKey(payload: Partial<ActivityGetSpecActByZoneKey>) {
	return webapi<ActivityGetSpecActByZoneKeyResp>("activity.Activity/GetSpecActByZoneKey", payload);
}

export function GetFullCutUrl(payload: Partial<ActivityGetFullCutUrl>) {
	return webapi<ActivityGetFullCutUrlResp>("activity.Activity/GetFullCutUrl", payload);
}

export function ActChangeLog(payload: Partial<ActivityActChangeLog>) {
	return webapi<ActivityActChangeLogResp>("activity.Activity/ActChangeLog", payload);
}

export function UsedActsByTime(payload: Partial<ActivityUsedActsByTime>) {
	return webapi<ActivityUsedActsByTimeResp>("activity.Activity/UsedActsByTime", payload);
}

export function Trace(payload: Partial<ActivityTrace>) {
	return webapi<ActivityTraceResp>("activity.Activity/Trace", payload);
}

export function DiscountTag(payload: Partial<ActivityDiscountTag>) {
	return webapi<ActivityDiscountTagResp>("activity.Activity/DiscountTag", payload);
}

export default {
	Ping,
	GetActInfo,
	MultiGetActInfo,
	MultiGetActInfoByCache,
	ImportExcel,
	ImportFile,
	GetProducts,
	GetConfByType,
	GetFunConf,
	List,
	Update,
	DeleteProducts,
	DeleteProductsByExcel,
	GetActByType,
	Delete,
	Trigger,
	TriggerByTime,
	MultiTriggerByTime,
	Create,
	GetActIdsByProduct,
	ReduceProductStock,
	AddProductStock,
	Import,
	AddRule,
	GetRule,
	BindRule,
	ListSpecAct,
	UpdateSpecAct,
	GetShipmentBy,
	ChangeRuleTime,
	GetSpecActByZoneKey,
	GetFullCutUrl,
	ActChangeLog,
	UsedActsByTime,
	Trace,
	DiscountTag
};
