/**
 * This file is auto-generated by protobufgen
 * Don't change manually
 */

import { XPlatform as SpkXPlatform } from "../spk/spk_public";
import { Region as BizRegion } from "../biz/region";
import { Warehouse as BizWarehouse } from "../biz/warehouse";
import webapi from "../webapi";

export enum Source {
	SourceInvalid = "SourceInvalid",
	SourceTaobao = "SourceTaobao",
	SourceTmall = "SourceTmall",
	SourceOther = "SourceOther",
	SourceTmallJu = "SourceTmallJu",
	SourceAmazon = "SourceAmazon",
	SourceYiqihuo = "SourceYiqihuo",
	SourceCarters = "SourceCarters",
	SourceOshkosh = "SourceOshkosh",
	SourceJingDong = "SourceJingDong",
	SourceSephora = "SourceSephora",
	SourceEzSeller = "SourceEzSeller",
	SourceRalphlauren = "SourceRalphlauren",
	SourceKatespade = "SourceKatespade",
	SourceGap = "SourceGap",
	SourceForever21 = "SourceForever21",
	SourceUnderarmour = "SourceUnderarmour",
	SourceTheonlinedrugstore = "SourceTheonlinedrugstore",
	SourcePhilips = "SourcePhilips",
	SourceAbercrombie = "SourceAbercrombie",
	SourceNike = "SourceNike",
	SourceFootLocker = "SourceFootLocker",
	SourceSixpm = "SourceSixpm",
	SourceChuchujie = "SourceChuchujie",
	SourceOne688 = "SourceOne688",
	SourceTarget = "SourceTarget",
	SourceOldNavyGap = "SourceOldNavyGap",
	SourceMogujie = "SourceMogujie",
	SourceUlta = "SourceUlta",
	SourceColourpop = "SourceColourpop"
}

export interface AssassinGet {
	url: string;
	source: Source;
	platform: SpkXPlatform;
	id: string;
	seller: string;
	noAPI: boolean;
	simple: boolean;
	notRealtime: boolean;
	noCache: boolean;
	scid: string;
}

export interface AssassinGetResp {
	item: Product;
}

export interface AssassinMGet {
	reqs: AssassinGet[];
}

export interface AssassinMGetResp {
	items: Product[];
}

export interface Product {
	refId: string;
	isNotFound: boolean;
	isOnSale: boolean;
	platform: SpkXPlatform;
	skuIndexable: boolean;
	entity: EntityInfo;
	sku: EntitySku;
	desc: EntityDesc;
	delivery: EntityDelivery;
	rank: EntityRank;
	pkg: EntityPackage;
	url: string;
	/**
	 * @pattern ^\d+$
	 */
	offLineTime: string;
}

export interface EntityPackage {
	/**
	 * @pattern ^\d+$
	 */
	weight: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	height: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	length: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	width: number;
	/**
	 * @pattern ^\d+$
	 */
	volWeight: string;
}

export interface EntityRank {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	sellerRank: number;
}

export interface EntityInfo {
	title: string;
	subTitle: string;
	titleEN: string;
	originCode: string;
	region: BizRegion;
	vendorName: string;
	shopName: string;
	brand: string;
	primaryPic: string;
	pics: string[];
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	quantity: number;
	price: Price;
	/**
	 * @pattern ^\d+$
	 */
	cid: string;
	location: string;
	/**
	 * @pattern ^\d+$
	 */
	cids: string[];
	cidPlatform: SpkXPlatform;
	thirdPartySeller: boolean;
	vendorId: string;
	internalUrl: string;
	scid: string;
}

export interface Price {
	normalPrice: PriceUnit;
	promotionPrice: PriceUnit;
}

export interface PriceUnit {
	/**
	 * @pattern ^\d+$
	 */
	price: string;
	/**
	 * @pattern ^\d+$
	 */
	maxPrice: string;
	tips: string;
}

export interface EntitySku {
	skuProps: EntitySkuProp[];
	skuInfo: EntitySkuInfo[];
}

export interface EntitySkuProp {
	skuPropId: string;
	skuPropName: string;
	skuPropValues: EntitySkuPropValue[];
}

export interface EntitySkuPropValue {
	name: string;
	valueId: string;
	img: string;
}

export interface EntitySkuInfo {
	skuId: string;
	pvPair: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	quantity: number;
	price: Price;
	title: string;
	titleEN: string;
	url: string;
	isSelected: boolean;
	pkg: EntityPackage;
	detailImg: string[];
	swatchImg: string;
	thirdPartySeller: boolean;
	seller: string;
	/**
	 * @pattern ^\d+$
	 */
	originPurchasePrice: string;
}

export interface EntityDelivery {
	warehouses: EntityDeliveryWarehouse[];
}

export interface EntityDeliveryWarehouse {
	warehouse: BizWarehouse;
	fee: EntityDeliveryWarehouseFee[];
}

export interface EntityDeliveryWarehouseFee {
	name: string;
	/**
	 * @pattern ^\d+$
	 */
	price: string;
}

export interface EntityDescProp {
	name: string;
	value: string;
	values: string[];
}

export interface EntityDesc {
	descProps: EntityDescProp[];
	pics: string[];
	features: string[];
	text: string;
	rule: Rule;
}

export interface Rule {
	key: string;
	disclaimer: string;
	table: Table;
}

export interface Table {
	header: string[];
	rows: Row[];
}

export interface Row {
	element: string[];
}

export interface AssassinFetch {
	id: string;
}

export interface AssassinFetchResp {
	item: Product;
}

export function Get(payload: Partial<AssassinGet>) {
	return webapi<AssassinGetResp>("assassin.Assassin/Get", payload);
}

export function MGet(payload: Partial<AssassinMGet>) {
	return webapi<AssassinMGetResp>("assassin.Assassin/MGet", payload);
}

export function CrabtreeEvelyn(payload: Partial<AssassinFetch>) {
	return webapi<AssassinFetchResp>("assassin.Assassin/CrabtreeEvelyn", payload);
}

export function VictoriasSecret(payload: Partial<AssassinFetch>) {
	return webapi<AssassinFetchResp>("assassin.Assassin/VictoriasSecret", payload);
}

export function GNC(payload: Partial<AssassinFetch>) {
	return webapi<AssassinFetchResp>("assassin.Assassin/GNC", payload);
}

export function ELF(payload: Partial<AssassinFetch>) {
	return webapi<AssassinFetchResp>("assassin.Assassin/ELF", payload);
}

export function Etmall(payload: Partial<AssassinFetch>) {
	return webapi<AssassinFetchResp>("assassin.Assassin/Etmall", payload);
}

export default {
	Get,
	MGet,
	CrabtreeEvelyn,
	VictoriasSecret,
	GNC,
	ELF,
	Etmall
};
