/**
 * This file is auto-generated by protobufgen
 * Don't change manually
 */

import { Error as SpkError } from "../spk/errors_public";
import { Region as BizRegion } from "../biz/region";
import { TriBool as CommonTriBool, I64Range as CommonI64Range } from "../common/common";

export enum XPlatform {
	XPlatformUnknown = "XPlatformUnknown",
	XPlatformEzbuy = "XPlatformEzbuy",
	XPlatformTaobao = "XPlatformTaobao",
	XPlatformAmazon = "XPlatformAmazon",
	XPlatformJingdong = "XPlatformJingdong",
	XPlatformCarters = "XPlatformCarters",
	XPlatformGap = "XPlatformGap",
	XPlatformSephora = "XPlatformSephora",
	XPlatformForever21 = "XPlatformForever21",
	XPlatformRalphlauren = "XPlatformRalphlauren",
	XPlatformKatespade = "XPlatformKatespade",
	XPlatformPhilips = "XPlatformPhilips",
	XPlatformUnderarmour = "XPlatformUnderarmour",
	XPlatformTheonlinedrugstore = "XPlatformTheonlinedrugstore",
	XPlatformAbercrombie = "XPlatformAbercrombie",
	XPlatformNike = "XPlatformNike",
	XPlatformOshkosh = "XPlatformOshkosh",
	XPlatformYiqihuo = "XPlatformYiqihuo",
	XPlatformOther = "XPlatformOther",
	XPlatformFootlocker = "XPlatformFootlocker",
	XPlatformSixpm = "XPlatformSixpm",
	XPlatformChuchujie = "XPlatformChuchujie",
	XPlatformOne688 = "XPlatformOne688",
	XPlatformPcstore = "XPlatformPcstore",
	XPlatformAdidas = "XPlatformAdidas",
	XPlatformTarget = "XPlatformTarget",
	XPlatformOldNavyGap = "XPlatformOldNavyGap",
	XPlatformMogujie = "XPlatformMogujie",
	XPlatformUlta = "XPlatformUlta",
	XPlatformColourpop = "XPlatformColourpop",
	XPlatformCrabtreeEvelyn = "XPlatformCrabtreeEvelyn",
	XPlatformVictoriasSecret = "XPlatformVictoriasSecret",
	XPlatformGNC = "XPlatformGNC",
	XPlatformELF = "XPlatformELF",
	XPlatformMeilele = "XPlatformMeilele",
	XPlatformEtmall = "XPlatformEtmall",
	XPlatformWeidian = "XPlatformWeidian",
	XPlatformGongyun = "XPlatformGongyun",
	XPlatformVip = "XPlatformVip",
	XPlatformChinaBrands = "XPlatformChinaBrands"
}

export enum XEzbuyShipment {
	XEzbuyShipmentInvalid = "XEzbuyShipmentInvalid",
	XEzbuyShipmentNormal = "XEzbuyShipmentNormal",
	XEzbuyShipmentSensitive = "XEzbuyShipmentSensitive",
	XEzbuyShipmentSea = "XEzbuyShipmentSea",
	XEzbuyShipmentSetInvalid = "XEzbuyShipmentSetInvalid"
}

export enum XPrimeShipment {
	XPrimeShipmentInvalid = "XPrimeShipmentInvalid",
	XPrimeShipmentAir = "XPrimeShipmentAir",
	XPrimeShipmentSea = "XPrimeShipmentSea",
	XPrimeShipmentSetInvalid = "XPrimeShipmentSetInvalid"
}

export enum XActivity {
	XActivityInvalid = "XActivityInvalid",
	XActivityFlashsales = "XActivityFlashsales",
	XActivityCashoff = "XActivityCashoff",
	XActivityFreeShipping = "XActivityFreeShipping",
	XActivityMNCashoff = "XActivityMNCashoff",
	XActivityFastDelivery = "XActivityFastDelivery",
	XActivityDiscount = "XActivityDiscount",
	XActivityFreeShippingExt = "XActivityFreeShippingExt",
	XActivityIgnore = "XActivityIgnore",
	XActivityOpen24 = "XActivityOpen24"
}

export enum XProductTag {
	XProductTagNone = "XProductTagNone",
	XProductTagNewArrival = "XProductTagNewArrival",
	XProductTagBanList = "XProductTagBanList"
}

export enum XListField {
	XListFieldAll = "XListFieldAll",
	XListFieldBase = "XListFieldBase",
	XListFieldCat = "XListFieldCat",
	XListFieldBrand = "XListFieldBrand",
	XListFieldProps = "XListFieldProps",
	XListFieldKeywordRecommand = "XListFieldKeywordRecommand",
	XListFieldActFilter = "XListFieldActFilter",
	XListFieldSearchDcidForce = "XListFieldSearchDcidForce"
}

export enum XSearchSource {
	XSearchSourceAll = "XSearchSourceAll",
	XSearchSourceEzbuy = "XSearchSourceEzbuy",
	XSearchSourceAgentUS = "XSearchSourceAgentUS",
	XSearchSourceAgentNotUS = "XSearchSourceAgentNotUS",
	XSearchSourceAgent = "XSearchSourceAgent",
	XSearchSourceAgentJingdong = "XSearchSourceAgentJingdong",
	XSearchSourceAgentJingdongLocal = "XSearchSourceAgentJingdongLocal",
	XSearchSourceAgentJingdongNotLocal = "XSearchSourceAgentJingdongNotLocal",
	XSearchSourceAgentNotJingdong = "XSearchSourceAgentNotJingdong",
	XSearchSourceAgentNotMogujie = "XSearchSourceAgentNotMogujie",
	XSearchSourceAgentNotJingdongNotMogujie = "XSearchSourceAgentNotJingdongNotMogujie",
	XSearchSourceAgentNotUSNotJingdong = "XSearchSourceAgentNotUSNotJingdong",
	XSearchSourceAgentNotUSNotJingdongNotMogujie = "XSearchSourceAgentNotUSNotJingdongNotMogujie",
	XSearchSourceUSNotAmazonNotEzbuy = "XSearchSourceUSNotAmazonNotEzbuy",
	XSearchSourceAgentCN = "XSearchSourceAgentCN",
	XSearchSourceAgentCNNotJingdong = "XSearchSourceAgentCNNotJingdong",
	XSearchSourceAgentCNNotJingdongNotMogujie = "XSearchSourceAgentCNNotJingdongNotMogujie",
	XSearchSourceAgentMogujie = "XSearchSourceAgentMogujie",
	XSearchSourceAgentTaobao = "XSearchSourceAgentTaobao",
	XSearchSourceNotTaobao = "XSearchSourceNotTaobao",
	XSearchSourceAgentJingdongLike = "XSearchSourceAgentJingdongLike",
	XSearchSourceUS = "XSearchSourceUS",
	XSearchSourceEzbuyKR = "XSearchSourceEzbuyKR",
	XSearchSourceEzbuyCNLocal = "XSearchSourceEzbuyCNLocal",
	XSearchSourceEzbuyCN = "XSearchSourceEzbuyCN",
	XSearchSourceEzbuyLocal = "XSearchSourceEzbuyLocal",
	XSearchSourceEzbuyNotLocal = "XSearchSourceEzbuyNotLocal",
	XSearchSourceEzbuyCNKR = "XSearchSourceEzbuyCNKR",
	XSearchSourceEzbuyUS = "XSearchSourceEzbuyUS",
	XSearchSourceAgentChuchujie = "XSearchSourceAgentChuchujie",
	XSearchSourceAgentVip = "XSearchSourceAgentVip",
	XSearchSourceAgentAmazon = "XSearchSourceAgentAmazon",
	XSearchSourceOpen24 = "XSearchSourceOpen24",
	XSearchSourceExpired = "XSearchSourceExpired"
}

export enum XSearchSort {
	XSearchSortBestMatch = "XSearchSortBestMatch",
	XSearchSortNewest = "XSearchSortNewest",
	XSearchSortPriceUp = "XSearchSortPriceUp",
	XSearchSortPriceDown = "XSearchSortPriceDown",
	XSearchSortRandom = "XSearchSortRandom",
	XSearchSortRecentPurchase = "XSearchSortRecentPurchase"
}

export enum XItemField {
	XItemFieldAll = "XItemFieldAll",
	XItemFieldBase = "XItemFieldBase",
	XItemFieldExtend = "XItemFieldExtend",
	XItemFieldProp = "XItemFieldProp",
	XItemFieldSkus = "XItemFieldSkus",
	XItemFieldDelivery = "XItemFieldDelivery",
	XItemFieldActivity = "XItemFieldActivity",
	XItemFieldDcat = "XItemFieldDcat"
}

export enum XTitleIconType {
	XTitleIconTypeUnknown = "XTitleIconTypeUnknown",
	XTitleIconTypeFrom = "XTitleIconTypeFrom",
	XTitleIconTypeNationalFlag = "XTitleIconTypeNationalFlag",
	XTitleIconTypeActivity = "XTitleIconTypeActivity"
}

export enum XListFilterWidget {
	XListFilterWidgetCheckbox = "XListFilterWidgetCheckbox",
	XListFilterWidgetSelect = "XListFilterWidgetSelect",
	XListFilterWidgetMultiSelect = "XListFilterWidgetMultiSelect"
}

export enum XBanScope {
	XBanScopeInvalid = "XBanScopeInvalid",
	XBanScopeDetail = "XBanScopeDetail",
	XBanScopeIndex = "XBanScopeIndex",
	XBanScopeList = "XBanScopeList",
	XBanScopeSetInvalid = "XBanScopeSetInvalid"
}

export interface XProductPrice {
	/**
	 * @pattern ^\d+$
	 */
	price: string;
	/**
	 * @pattern ^\d+$
	 */
	listPrice: string;
	/**
	 * @pattern ^\d+$
	 */
	originPrice: string;
	/**
	 * @pattern ^\d+$
	 */
	originListPrice: string;
}

export interface XPrice {
	/**
	 * @pattern ^\d+$
	 */
	price: string;
	/**
	 * @pattern ^\d+$
	 */
	originPrice: string;
}

export interface XEzbuy {
	enable: boolean;
	type: XEzbuyShipment;
}

export interface XPrime {
	enable: boolean;
	type: XPrimeShipment;
}

export interface XProp {
	propId: string;
	propName: string;
	altPropName: string;
	propValue: XPropValue[];
}

export interface XPropValue {
	propValueId: string;
	propValueName: string;
	altPropValueName: string;
	img: string;
	isSelected: boolean;
}

export interface XListItem {
	error: SpkError;
	product: XProduct;
}

export interface XProduct {
	/**
	 * @pattern ^\d+$
	 */
	gpid: string;
	/**
	 * @pattern ^\d+$
	 */
	baseGpid: string;
	name: string;
	originName: string;
	/**
	 * @pattern ^\d+$
	 */
	price: string;
	/**
	 * @pattern ^\d+$
	 */
	listPrice: string;
	discount: string;
	img: string;
	region: BizRegion;
	isPrime: boolean;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	pcid: number;
	/**
	 * @pattern ^\d+$
	 */
	originPrice: string;
	/**
	 * @pattern ^\d+$
	 */
	originListPrice: string;
	url: string;
	acts: XProductActivity[];
	platform: XPlatform;
	cashoff: XProductCashoff;
	translated: boolean;
	isPremium: boolean;
	/**
	 * @minimum 0
	 */
	exchange: number;
	dcids: number[];
	allDcids: number[];
	mncashoff: XProductMNCashoff;
	vendor: string;
	icon: XIcon;
	/**
	 * @pattern ^\d+$
	 */
	createDate: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	weight: number;
	isEzbuy: boolean;
	titleIcons: XTitleIcon[];
	tag: XProductTag;
}

export interface XIcon {
	text: string;
	color: string;
	img: string;
}

export interface XProductCashoff {
	enable: boolean;
	color: string;
	key: string;
}

export interface XProductMNCashoff {
	tagImg: string;
}

export interface XProductActivity {
	type: XActivity;
	ids: string[];
}

export interface XList {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	maxPage: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	total: number;
	items: XListItem[];
	catCrumb: XListCat[];
	catTree: XListCatTree;
	catRecommendByKeyword: XListCat[];
	brands: XListBrand[];
	props: XListProp[];
	filters: XListFilter[];
}

export interface XListBrand {
	name: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	count: number;
}

export interface XListProp {
	name: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	propId: number;
	propValues: XListPropValue[];
}

export interface XListPropValue {
	name: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	propValueId: number;
}

export interface XListCat {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	dcid: number;
	name: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	count: number;
}

export interface XListCatTree {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	dcid: number;
	name: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	count: number;
	sub: XListCatTree[];
}

export interface XSearch {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	dcid: number;
	dcids: number[];
	excludeDcids: number[];
	pcid: number[];
	keyword: string;
	keywords: string[];
	source: XSearchSource;
	sources: XSearchSource[];
	primeOnly: boolean;
	isPrime: CommonTriBool;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	discount: number;
	price: XSearchRange;
	acts: XSearchActs[];
	multiActs: XActivity[];
	region: BizRegion;
	brands: string[];
	vendor: string;
	vendors: string[];
	ezbuyVendor: string[];
	platform: XPlatform;
	platforms: XPlatform[];
	props: XSearchProp[];
	premiumOnly: boolean;
	/**
	 * @pattern ^\d+$
	 */
	earliestCreateDate: string;
	/**
	 * @pattern ^\d+$
	 */
	latestCreateDate: string;
	/**
	 * @pattern ^\d+$
	 */
	platformCid: string[];
	regions: BizRegion[];
	collectionId: string;
	from: number[];
	newOnly: boolean;
	inSaleTime: CommonI64Range;
	invert: boolean;
	withSearchNewScore: boolean;
}

export interface XSearchProp {
	ids: number[];
}

export interface XSearchActs {
	type: XActivity;
	id: string;
	ids: string[];
}

export interface XSearchRange {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	start: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	end: number;
}

export interface XPremium {
	enable: boolean;
	bannerUrl: string;
}

export interface XTitleIcon {
	icon: string;
	text: string;
	link: string;
	linkText: string;
	type: XTitleIconType;
}

export interface XListFilter {
	name: string;
	filterId: string;
	widget: XListFilterWidget;
	items: XListFilterItem[];
}

export interface XListFilterItem {
	value: string;
	name: string;
}

export interface XBanner {
	img: string;
	link: string;
	text: string;
}
