// Code generated by protoc-gen-go. DO NOT EDIT.
// source: capital.proto

/*
Package capital is a generated protocol buffer package.

It is generated from these files:
	capital.proto

It has these top-level messages:
	Pagination
	CapitalFlowReq
	CapitalFlowResp
*/
package capital

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DateSpan int32

const (
	DateSpan_OneDay   DateSpan = 0
	DateSpan_TwoDay   DateSpan = 1
	DateSpan_ThreeDay DateSpan = 2
	DateSpan_FourDay  DateSpan = 3
	DateSpan_OneWk    DateSpan = 4
	DateSpan_TwoWk    DateSpan = 5
	DateSpan_ThreeWk  DateSpan = 6
	DateSpan_FourWk   DateSpan = 7
)

var DateSpan_name = map[int32]string{
	0: "OneDay",
	1: "TwoDay",
	2: "ThreeDay",
	3: "FourDay",
	4: "OneWk",
	5: "TwoWk",
	6: "ThreeWk",
	7: "FourWk",
}
var DateSpan_value = map[string]int32{
	"OneDay":   0,
	"TwoDay":   1,
	"ThreeDay": 2,
	"FourDay":  3,
	"OneWk":    4,
	"TwoWk":    5,
	"ThreeWk":  6,
	"FourWk":   7,
}

func (x DateSpan) String() string {
	return proto.EnumName(DateSpan_name, int32(x))
}
func (DateSpan) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Pagination struct {
	Page int32 `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	Size int32 `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	Next bool  `protobuf:"varint,3,opt,name=next" json:"next,omitempty"`
}

func (m *Pagination) Reset()                    { *m = Pagination{} }
func (m *Pagination) String() string            { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()               {}
func (*Pagination) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Pagination) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Pagination) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Pagination) GetNext() bool {
	if m != nil {
		return m.Next
	}
	return false
}

// 查询条件
type CapitalFlowReq struct {
	Code string      `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Span DateSpan    `protobuf:"varint,2,opt,name=span,enum=capital.DateSpan" json:"span,omitempty"`
	Page *Pagination `protobuf:"bytes,3,opt,name=page" json:"page,omitempty"`
}

func (m *CapitalFlowReq) Reset()                    { *m = CapitalFlowReq{} }
func (m *CapitalFlowReq) String() string            { return proto.CompactTextString(m) }
func (*CapitalFlowReq) ProtoMessage()               {}
func (*CapitalFlowReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CapitalFlowReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CapitalFlowReq) GetSpan() DateSpan {
	if m != nil {
		return m.Span
	}
	return DateSpan_OneDay
}

func (m *CapitalFlowReq) GetPage() *Pagination {
	if m != nil {
		return m.Page
	}
	return nil
}

type CapitalFlowResp struct {
	Code      string      `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Name      string      `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	MainIn    int64       `protobuf:"varint,3,opt,name=mainIn" json:"mainIn,omitempty"`
	MainOut   int64       `protobuf:"varint,4,opt,name=mainOut" json:"mainOut,omitempty"`
	RetailIn  int64       `protobuf:"varint,5,opt,name=retailIn" json:"retailIn,omitempty"`
	RetailOut int64       `protobuf:"varint,6,opt,name=retailOut" json:"retailOut,omitempty"`
	Balance   int64       `protobuf:"varint,7,opt,name=balance" json:"balance,omitempty"`
	Span      DateSpan    `protobuf:"varint,8,opt,name=span,enum=capital.DateSpan" json:"span,omitempty"`
	Page      *Pagination `protobuf:"bytes,9,opt,name=page" json:"page,omitempty"`
}

func (m *CapitalFlowResp) Reset()                    { *m = CapitalFlowResp{} }
func (m *CapitalFlowResp) String() string            { return proto.CompactTextString(m) }
func (*CapitalFlowResp) ProtoMessage()               {}
func (*CapitalFlowResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CapitalFlowResp) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CapitalFlowResp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CapitalFlowResp) GetMainIn() int64 {
	if m != nil {
		return m.MainIn
	}
	return 0
}

func (m *CapitalFlowResp) GetMainOut() int64 {
	if m != nil {
		return m.MainOut
	}
	return 0
}

func (m *CapitalFlowResp) GetRetailIn() int64 {
	if m != nil {
		return m.RetailIn
	}
	return 0
}

func (m *CapitalFlowResp) GetRetailOut() int64 {
	if m != nil {
		return m.RetailOut
	}
	return 0
}

func (m *CapitalFlowResp) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *CapitalFlowResp) GetSpan() DateSpan {
	if m != nil {
		return m.Span
	}
	return DateSpan_OneDay
}

func (m *CapitalFlowResp) GetPage() *Pagination {
	if m != nil {
		return m.Page
	}
	return nil
}

func init() {
	proto.RegisterType((*Pagination)(nil), "capital.Pagination")
	proto.RegisterType((*CapitalFlowReq)(nil), "capital.CapitalFlowReq")
	proto.RegisterType((*CapitalFlowResp)(nil), "capital.CapitalFlowResp")
	proto.RegisterEnum("capital.DateSpan", DateSpan_name, DateSpan_value)
}

func init() { proto.RegisterFile("capital.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0xdf, 0xb4, 0xf9, 0x3b, 0x7d, 0xad, 0x71, 0x05, 0x59, 0xc4, 0x43, 0x29, 0x88, 0xc5,
	0x43, 0x0f, 0xf5, 0x23, 0x58, 0x8a, 0x3d, 0x55, 0xd6, 0x42, 0xce, 0xd3, 0xba, 0xd4, 0x90, 0x74,
	0x37, 0xa6, 0x5b, 0xaa, 0x7e, 0x09, 0xbf, 0xb2, 0xcc, 0x6e, 0xda, 0x22, 0x08, 0x7a, 0xfb, 0x3d,
	0x33, 0xb3, 0xcf, 0x3c, 0x19, 0x02, 0x27, 0x4b, 0xac, 0x72, 0x83, 0xe5, 0xb0, 0xaa, 0xb5, 0xd1,
	0x2c, 0x6a, 0x64, 0xff, 0x01, 0xe0, 0x11, 0x57, 0xb9, 0x42, 0x93, 0x6b, 0xc5, 0x18, 0xf8, 0x15,
	0xae, 0x24, 0xf7, 0x7a, 0xde, 0x20, 0x10, 0x96, 0xa9, 0xb6, 0xc9, 0x3f, 0x24, 0x6f, 0xb9, 0x1a,
	0x31, 0xd5, 0x94, 0x7c, 0x33, 0xbc, 0xdd, 0xf3, 0x06, 0xb1, 0xb0, 0xdc, 0x37, 0xd0, 0xbd, 0x77,
	0xa6, 0x93, 0x52, 0xef, 0x84, 0x7c, 0xa5, 0xa9, 0xa5, 0x7e, 0x76, 0x6e, 0x89, 0xb0, 0xcc, 0xae,
	0xc1, 0xdf, 0x54, 0xa8, 0xac, 0x5b, 0x77, 0x74, 0x36, 0xdc, 0xc7, 0x1a, 0xa3, 0x91, 0x4f, 0x15,
	0x2a, 0x61, 0xdb, 0xec, 0xa6, 0x09, 0x42, 0x0b, 0x3a, 0xa3, 0xf3, 0xc3, 0xd8, 0x31, 0xab, 0x4b,
	0xd7, 0xff, 0x6c, 0xc1, 0xe9, 0xb7, 0xb5, 0x9b, 0xea, 0xc7, 0xbd, 0x94, 0x18, 0xd7, 0xee, 0x2b,
	0x12, 0x61, 0x99, 0x5d, 0x40, 0xb8, 0xc6, 0x5c, 0x4d, 0x95, 0x5d, 0xd3, 0x16, 0x8d, 0x62, 0x1c,
	0x22, 0xa2, 0xd9, 0xd6, 0x70, 0xdf, 0x36, 0xf6, 0x92, 0x5d, 0x42, 0x5c, 0x4b, 0x83, 0x79, 0x39,
	0x55, 0x3c, 0xb0, 0xad, 0x83, 0x66, 0x57, 0x90, 0x38, 0xa6, 0x77, 0xa1, 0x6d, 0x1e, 0x0b, 0xe4,
	0xb9, 0xc0, 0x12, 0xd5, 0x52, 0xf2, 0xc8, 0x79, 0x36, 0xf2, 0x70, 0x91, 0xf8, 0x6f, 0x17, 0x49,
	0x7e, 0xb9, 0xc8, 0x6d, 0x09, 0xf1, 0xfe, 0x29, 0x03, 0x08, 0x67, 0x4a, 0x8e, 0xf1, 0x3d, 0xfd,
	0x47, 0x3c, 0xdf, 0x69, 0x62, 0x8f, 0xfd, 0x87, 0x78, 0xfe, 0x52, 0x4b, 0xdb, 0x69, 0xb1, 0x0e,
	0x44, 0x13, 0xbd, 0xad, 0x49, 0xb4, 0x59, 0x02, 0xc1, 0x4c, 0xc9, 0xac, 0x48, 0x7d, 0xc2, 0xf9,
	0x4e, 0x67, 0x45, 0x1a, 0xd0, 0x88, 0x7d, 0x90, 0x15, 0x69, 0x48, 0x4e, 0x34, 0x9f, 0x15, 0x69,
	0xb4, 0x08, 0xed, 0xff, 0x74, 0xf7, 0x15, 0x00, 0x00, 0xff, 0xff, 0x83, 0x2b, 0x6b, 0x29, 0x60,
	0x02, 0x00, 0x00,
}
