// Code generated by protoc-gen-go. DO NOT EDIT.
// source: seller.proto

/*
Package seller is a generated protocol buffer package.

It is generated from these files:
	seller.proto

It has these top-level messages:
	Basic
	GetNameReq
	GetNameResp
*/
package seller

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Basic struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Basic) Reset()                    { *m = Basic{} }
func (m *Basic) String() string            { return proto.CompactTextString(m) }
func (*Basic) ProtoMessage()               {}
func (*Basic) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Basic) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetNameReq struct {
}

func (m *GetNameReq) Reset()                    { *m = GetNameReq{} }
func (m *GetNameReq) String() string            { return proto.CompactTextString(m) }
func (*GetNameReq) ProtoMessage()               {}
func (*GetNameReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type GetNameResp struct {
}

func (m *GetNameResp) Reset()                    { *m = GetNameResp{} }
func (m *GetNameResp) String() string            { return proto.CompactTextString(m) }
func (*GetNameResp) ProtoMessage()               {}
func (*GetNameResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*Basic)(nil), "seller.Basic")
	proto.RegisterType((*GetNameReq)(nil), "seller.GetNameReq")
	proto.RegisterType((*GetNameResp)(nil), "seller.GetNameResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Seller service

type SellerClient interface {
	GetSellerName(ctx context.Context, in *GetNameReq, opts ...grpc.CallOption) (*GetNameResp, error)
}

type sellerClient struct {
	cc *grpc.ClientConn
}

func NewSellerClient(cc *grpc.ClientConn) SellerClient {
	return &sellerClient{cc}
}

func (c *sellerClient) GetSellerName(ctx context.Context, in *GetNameReq, opts ...grpc.CallOption) (*GetNameResp, error) {
	out := new(GetNameResp)
	err := grpc.Invoke(ctx, "/seller.Seller/GetSellerName", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Seller service

type SellerServer interface {
	GetSellerName(context.Context, *GetNameReq) (*GetNameResp, error)
}

func RegisterSellerServer(s *grpc.Server, srv SellerServer) {
	s.RegisterService(&_Seller_serviceDesc, srv)
}

func _Seller_GetSellerName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellerServer).GetSellerName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seller.Seller/GetSellerName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellerServer).GetSellerName(ctx, req.(*GetNameReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Seller_serviceDesc = grpc.ServiceDesc{
	ServiceName: "seller.Seller",
	HandlerType: (*SellerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSellerName",
			Handler:    _Seller_GetSellerName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "seller.proto",
}

func init() { proto.RegisterFile("seller.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 125 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4e, 0xcd, 0xc9,
	0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0xa4, 0xb9, 0x58,
	0x9d, 0x12, 0x8b, 0x33, 0x93, 0x85, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15,
	0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25, 0x1e, 0x2e, 0x2e, 0xf7, 0xd4, 0x12, 0xbf, 0xc4, 0xdc,
	0xd4, 0xa0, 0xd4, 0x42, 0x25, 0x5e, 0x2e, 0x6e, 0x38, 0xaf, 0xb8, 0xc0, 0xc8, 0x89, 0x8b, 0x2d,
	0x18, 0x6c, 0x86, 0x90, 0x05, 0x17, 0xaf, 0x7b, 0x6a, 0x09, 0x84, 0x03, 0x92, 0x16, 0x12, 0xd2,
	0x83, 0xda, 0x85, 0xd0, 0x2d, 0x25, 0x8c, 0x21, 0x56, 0x5c, 0x90, 0xc4, 0x06, 0x76, 0x8c, 0x31,
	0x20, 0x00, 0x00, 0xff, 0xff, 0x6e, 0x8c, 0x96, 0x75, 0x9c, 0x00, 0x00, 0x00,
}
