// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

/*
Package account is a generated protocol buffer package.

It is generated from these files:
	account.proto

It has these top-level messages:
	Result
	AccountLoginReq
	AccountLoginResp
*/
package account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Result struct {
	// 状态码
	Code int32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	// 结果描述
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Result) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Result) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AccountLoginReq struct {
	// 账号
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	// 密码
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	// 验证码
	Captcha string `protobuf:"bytes,3,opt,name=captcha" json:"captcha,omitempty"`
}

func (m *AccountLoginReq) Reset()                    { *m = AccountLoginReq{} }
func (m *AccountLoginReq) String() string            { return proto.CompactTextString(m) }
func (*AccountLoginReq) ProtoMessage()               {}
func (*AccountLoginReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AccountLoginReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AccountLoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AccountLoginReq) GetCaptcha() string {
	if m != nil {
		return m.Captcha
	}
	return ""
}

type AccountLoginResp struct {
	// 结果
	Result *Result `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *AccountLoginResp) Reset()                    { *m = AccountLoginResp{} }
func (m *AccountLoginResp) String() string            { return proto.CompactTextString(m) }
func (*AccountLoginResp) ProtoMessage()               {}
func (*AccountLoginResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AccountLoginResp) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*Result)(nil), "Result")
	proto.RegisterType((*AccountLoginReq)(nil), "AccountLoginReq")
	proto.RegisterType((*AccountLoginResp)(nil), "AccountLoginResp")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x3d, 0x0b, 0xc2, 0x30,
	0x10, 0x86, 0xa9, 0x1f, 0xad, 0x3d, 0x11, 0x25, 0x53, 0x70, 0xb1, 0x74, 0xea, 0xd4, 0xc1, 0x82,
	0xbb, 0xbb, 0x53, 0xfe, 0x41, 0x4c, 0x43, 0x15, 0x6c, 0x2f, 0xe6, 0x52, 0xfc, 0xfb, 0xd2, 0x24,
	0x16, 0xdc, 0xee, 0xb9, 0x83, 0xf7, 0x79, 0x0f, 0x76, 0x52, 0x29, 0x1c, 0x07, 0x57, 0x1b, 0x8b,
	0x0e, 0xcb, 0x0b, 0xa4, 0x42, 0xd3, 0xf8, 0x72, 0x8c, 0xc1, 0x4a, 0x61, 0xab, 0x79, 0x52, 0x24,
	0xd5, 0x5a, 0xf8, 0x99, 0x71, 0xc8, 0x7a, 0x4d, 0x24, 0x3b, 0xcd, 0x17, 0x45, 0x52, 0xe5, 0xe2,
	0x87, 0xa5, 0x82, 0xfd, 0x35, 0x04, 0xdd, 0xb0, 0x7b, 0x0e, 0x42, 0xbf, 0xd9, 0x11, 0x36, 0x23,
	0x69, 0x3b, 0xc8, 0x3e, 0x84, 0xe4, 0x62, 0xe6, 0xe9, 0x66, 0x24, 0xd1, 0x07, 0x6d, 0x1b, 0x93,
	0x66, 0x9e, 0x24, 0x4a, 0x1a, 0xa7, 0x1e, 0x92, 0x2f, 0x83, 0x24, 0x62, 0xd9, 0xc0, 0xe1, 0x5f,
	0x42, 0x86, 0x9d, 0x20, 0xb5, 0xbe, 0xb0, 0x77, 0x6c, 0xcf, 0x59, 0x1d, 0xfa, 0x8b, 0xb8, 0xbe,
	0xa7, 0xfe, 0xb1, 0xe6, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x14, 0x3a, 0x80, 0x9c, 0xe9, 0x00, 0x00,
	0x00,
}
