/**
 * This file is auto-generated by protobufgen
 * Don't change manually
 */

import { Result as EzsellerResult } from "./result";
import webapi from "../webapi";


export interface AdmimArea {
	id: string;
	name: string;
	parentId: string;
	children: AdmimArea[];
}

export interface AddressMsg {
	id: string;
	contact: string;
	admimArea: string[];
	admimAreaCode: string[];
	street: string;
	contactMethod: string;
	remark: string;
	isShip: boolean;
	isReceipt: boolean;
}

export interface GetAdmimAreasByDepthReq {
	depth: number;
}

export interface GetAdmimAreasByDepthResp {
	result: EzsellerResult;
	areas: AdmimArea[];
}

export interface GetAdmimAreasByParentIdReq {
	parentId: string;
}

export interface GetAdmimAreasByParentIdResp {
	result: EzsellerResult;
	areas: AdmimArea[];
}

export interface GetAdmimAreaDetailReq {
	id: string;
}

export interface GetAdmimAreaDetailResp {
	result: EzsellerResult;
	area: AdmimArea;
}

export interface GetParentAdmimAreasReq {
	id: string;
}

export interface GetParentAdmimAreasResp {
	result: EzsellerResult;
	areas: AdmimArea[];
}

export interface GetOwnAddressesReq {

}

export interface GetOwnAddressesResp {
	result: EzsellerResult;
	addresses: AddressMsg[];
}

export interface CreateAddressReq {
	address: AddressMsg;
}

export interface CreateAddressResp {
	result: EzsellerResult;
}

export interface ModifyAddressReq {
	address: AddressMsg;
}

export interface ModifyAddressResp {
	result: EzsellerResult;
}

export interface ModifyDefaultAddrReq {
	id: string;
	isShip: boolean;
	isReceipt: boolean;
}

export interface ModifyDefaultAddrResp {
	result: EzsellerResult;
}

export interface RemoveAddressReq {
	id: string;
}

export interface RemoveAddressResp {
	result: EzsellerResult;
}



export function GetAdmimAreasByDepth(payload: GetAdmimAreasByDepthReq) {
	return webapi<GetAdmimAreasByDepthResp>("ezseller.Address/GetAdmimAreasByDepth", payload);
}

export function GetAdmimAreasByParentId(payload: GetAdmimAreasByParentIdReq) {
	return webapi<GetAdmimAreasByParentIdResp>("ezseller.Address/GetAdmimAreasByParentId", payload);
}

export function GetAdmimAreaDetail(payload: GetAdmimAreaDetailReq) {
	return webapi<GetAdmimAreaDetailResp>("ezseller.Address/GetAdmimAreaDetail", payload);
}

export function GetParentAdmimAreas(payload: GetParentAdmimAreasReq) {
	return webapi<GetParentAdmimAreasResp>("ezseller.Address/GetParentAdmimAreas", payload);
}

export function GetOwnAddresses(payload: GetOwnAddressesReq) {
	return webapi<GetOwnAddressesResp>("ezseller.Address/GetOwnAddresses", payload);
}

export function CreateAddress(payload: CreateAddressReq) {
	return webapi<CreateAddressResp>("ezseller.Address/CreateAddress", payload);
}

export function ModifyAddress(payload: ModifyAddressReq) {
	return webapi<ModifyAddressResp>("ezseller.Address/ModifyAddress", payload);
}

export function ModifyDefaultAddress(payload: ModifyDefaultAddrReq) {
	return webapi<ModifyDefaultAddrResp>("ezseller.Address/ModifyDefaultAddress", payload);
}

export function RemoveAddress(payload: RemoveAddressReq) {
	return webapi<RemoveAddressResp>("ezseller.Address/RemoveAddress", payload);
}


export default {
	GetAdmimAreasByDepth,
	GetAdmimAreasByParentId,
	GetAdmimAreaDetail,
	GetParentAdmimAreas,
	GetOwnAddresses,
	CreateAddress,
	ModifyAddress,
	ModifyDefaultAddress,
	RemoveAddress,
};


