/**
 * This file is auto-generated by protobufgen
 * Don't change manually
 */

import webapi from "../webapi";

export enum AmwayRecommendationTaskStatus {
	AmwayRecommendationTaskStatusUnknown = "AmwayRecommendationTaskStatusUnknown",
	AmwayRecommendationTaskStatusProcessing = "AmwayRecommendationTaskStatusProcessing",
	AmwayRecommendationTaskStatusSuccess = "AmwayRecommendationTaskStatusSuccess",
	AmwayRecommendationTaskStatusFail = "AmwayRecommendationTaskStatusFail",
}



export interface AmwayPCat {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	PCatId: number;
	PCatName: string;
}

export interface AmwayRecommendationListReq {
	pcat: AmwayPCat;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	limit: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	offset: number;
}

export interface AmwayRecommendationListItem {
	/**
	 * @pattern ^\d+$
	 */
	productId: string;
	title: string;
	image: string;
	catPath: string;
	/**
	 * @pattern ^\d+$
	 */
	price: string;
	/**
	 * @pattern ^\d+$
	 */
	copyAt: string;
	status: AmwayRecommendationTaskStatus;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	catId: number;
}

export interface AmwayRecommendationListResp {
	items: AmwayRecommendationListItem[];
}

export interface AmwayFistClassPCatListReq {

}

export interface AmwayFistClassPCatListResp {
	list: AmwayPCat[];
}

export interface AmwayCopyRecommendationsReq {
	productIds: string[];
	shopName: string;
}

export interface AmwayCopyRecommendationsResp {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	code: number;
	msg: string;
}

export interface AmwayCopyRecommendationListReq {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	status: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	limit: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	offset: number;
}

export interface AmwayCopyRecommendationListResp {
	items: AmwayRecommendationListItem[];
}



export function FistClassPCatList(payload: Partial<AmwayFistClassPCatListReq>) {
	return webapi<AmwayFistClassPCatListResp>("ezseller.Amway/FistClassPCatList", payload);
}

export function RecommendationList(payload: Partial<AmwayRecommendationListReq>) {
	return webapi<AmwayRecommendationListResp>("ezseller.Amway/RecommendationList", payload);
}

export function CopyRecommendations(payload: Partial<AmwayCopyRecommendationsReq>) {
	return webapi<AmwayCopyRecommendationsResp>("ezseller.Amway/CopyRecommendations", payload);
}

export function CopyRecommendationList(payload: Partial<AmwayCopyRecommendationListReq>) {
	return webapi<AmwayCopyRecommendationListResp>("ezseller.Amway/CopyRecommendationList", payload);
}


export default {
	FistClassPCatList,
	RecommendationList,
	CopyRecommendations,
	CopyRecommendationList,
};