/**
 * This file is auto-generated by protobufgen
 * Don't change manually
 */

import { Result as EzsellerResult } from "./result";
import { SortOption as AppcommonSortOption } from "../appcommon/common_public";
import { GroupLayoutInfo as EzsellerGroupLayoutInfo } from "./sellerStore_public";
import webapi from "../webapi";

export enum DecoratorClientType {
	DecoratorClientTypeUnknown = "DecoratorClientTypeUnknown",
	DecoratorClientTypePCSep = "DecoratorClientTypePCSep",
	DecoratorClientTypePC = "DecoratorClientTypePC",
	DecoratorClientTypeMobileSep = "DecoratorClientTypeMobileSep",
	DecoratorClientTypeIOS = "DecoratorClientTypeIOS",
	DecoratorClientTypeAndroid = "DecoratorClientTypeAndroid",
	DecoratorClientTypeMStatation = "DecoratorClientTypeMStatation",
	DecoratorClientTypeMaxLimit = "DecoratorClientTypeMaxLimit",
}



export interface AsyncGenDcidTreeReq {
	shopId: number;
}

export interface AsyncGenDcidTreeResp {
	result: EzsellerResult;
}

export interface DecoratorDcidTree {
	Dcid: number;
	Dcname: string;
	count: number;
	sub: DecoratorDcidTree[];
}

export interface GetSellerDcidTreeReq {
	shopId: number;
	shopName: string;
}

export interface GetSellerDcidTreeResp {
	result: EzsellerResult;
	tree: DecoratorDcidTree;
}

export interface SellerProductSearchReq {
	offset: number;
	limit: number;
	pcid: number;
}

export interface SellerProductItem {
	productId: number;
	name: string;
	image: string;
	price: string;
	quantity: number;
}

export interface SellerProductSearchResp {

}

export interface SellerSelfCatQueryReq {
	shopId: number;
}

export interface SellerSelfCatQueryResp {
	result: EzsellerResult;
	tree: DecoratorSelfTree;
}

export interface ShopSelfCatQueryReq {

}

export interface ShopSelfCatQueryResp {
	result: EzsellerResult;
	tree: DecoratorSelfTree;
}

export interface SelfCatDefineReq {
	tree: DecoratorSelfTree;
}

export interface SelfCatDefineResp {
	result: EzsellerResult;
}

export interface DecoratorSelfTree {
	dcname: string;
	products: number[];
	sub: DecoratorSelfTree[];
}

export interface PublishSellerHomePageAreasReq {
	shopName: string;
	areas: DecoratorHomePageArea[];
	sortOptions: AppcommonSortOption[];
	client: DecoratorClientType;
}

export interface PublishSellerHomePageAreasResp {
	result: EzsellerResult;
}

export interface SetSellerHomePageAreasViewReq {
	shopName: string;
	areas: DecoratorHomePageArea[];
	sortOptions: AppcommonSortOption[];
}

export interface SetSellerHomePageAreasViewResp {
	result: EzsellerResult;
}

export interface GetSellerHomePageAreasReq {
	client: DecoratorClientType;
}

export interface GetSellerHomePageAreasResp {
	result: EzsellerResult;
	areas: DecoratorHomePageArea[];
	sortOptions: AppcommonSortOption[];
}

export interface ValidProductLinkReq {
	link: string;
}

export interface ValidProductLinkResp {
	result: EzsellerResult;
	gpid: string;
}

export interface GetAllAvailableOptionReq {

}

export interface GetAllAvailableOptionResp {
	result: EzsellerResult;
	sortOptions: AppcommonSortOption[];
}

export interface DecoratorHomePageEntrance {
	name: string;
	image: string;
	link: string;
	desc: string;
	gpid: string;
}

export interface DecoratorHomePageArea {
	name: string;
	entranceList: DecoratorHomePageEntrance[];
	groupLayoutInfo: EzsellerGroupLayoutInfo;
	link: string;
}



export function AsyncGenDcidTree(payload: AsyncGenDcidTreeReq) {
	return webapi<AsyncGenDcidTreeResp>("ezseller.Decorator/AsyncGenDcidTree", payload);
}

export function GetSellerDcidTree(payload: GetSellerDcidTreeReq) {
	return webapi<GetSellerDcidTreeResp>("ezseller.Decorator/GetSellerDcidTree", payload);
}

export function PublishSellerHomePageAreas(payload: PublishSellerHomePageAreasReq) {
	return webapi<PublishSellerHomePageAreasResp>("ezseller.Decorator/PublishSellerHomePageAreas", payload);
}

export function GetSellerHomePageAreas(payload: GetSellerHomePageAreasReq) {
	return webapi<GetSellerHomePageAreasResp>("ezseller.Decorator/GetSellerHomePageAreas", payload);
}

export function SetSellerHomePageAreasView(payload: SetSellerHomePageAreasViewReq) {
	return webapi<SetSellerHomePageAreasViewResp>("ezseller.Decorator/SetSellerHomePageAreasView", payload);
}

export function GetAllAvailableOption(payload: GetAllAvailableOptionReq) {
	return webapi<GetAllAvailableOptionResp>("ezseller.Decorator/GetAllAvailableOption", payload);
}

export function ValidProductLink(payload: ValidProductLinkReq) {
	return webapi<ValidProductLinkResp>("ezseller.Decorator/ValidProductLink", payload);
}

export function SellerProductSearch(payload: SellerProductSearchReq) {
	return webapi<SellerProductSearchResp>("ezseller.Decorator/SellerProductSearch", payload);
}

export function SellerSelfCatQuery(payload: SellerSelfCatQueryReq) {
	return webapi<SellerSelfCatQueryResp>("ezseller.Decorator/SellerSelfCatQuery", payload);
}

export function ShopSelfCatQuery(payload: ShopSelfCatQueryReq) {
	return webapi<ShopSelfCatQueryResp>("ezseller.Decorator/ShopSelfCatQuery", payload);
}

export function SelfCatDefine(payload: SelfCatDefineReq) {
	return webapi<SelfCatDefineResp>("ezseller.Decorator/SelfCatDefine", payload);
}


export default {
	AsyncGenDcidTree,
	GetSellerDcidTree,
	PublishSellerHomePageAreas,
	GetSellerHomePageAreas,
	SetSellerHomePageAreasView,
	GetAllAvailableOption,
	ValidProductLink,
	SellerProductSearch,
	SellerSelfCatQuery,
	ShopSelfCatQuery,
	SelfCatDefine,
};


