/**
 * This file is auto-generated by protobufgen
 * Don't change manually
 */

import { Result as EzsellerResult } from "../ezseller/result";
import { OrderItemOperType as EzOrderOrderItemOperType } from "../ezOrder/order";
import webapi from "../webapi";

export enum OrderItemStyle {
	OrderItemStyleUnknown = "OrderItemStyleUnknown",
	OrderItemStyleOldCart = "OrderItemStyleOldCart",
	OrderItemStyleNewCart = "OrderItemStyleNewCart",
	OrderItemStyleMixedCart = "OrderItemStyleMixedCart"
}

export enum OrderItemType {
	OrderItemTypeUnknown = "OrderItemTypeUnknown",
	OrderItemTypeNormal = "OrderItemTypeNormal",
	OrderItemTypeAdd = "OrderItemTypeAdd",
	OrderItemTypeIncomplete = "OrderItemTypeIncomplete",
	OrderItemTypeReturn = "OrderItemTypeReturn",
	OrderItemTypeShortBalance = "OrderItemTypeShortBalance",
	OrderItemTypeUnnecessary = "OrderItemTypeUnnecessary"
}

export enum OrderItemFeeType {
	OrderItemFeeTypeUnknown = "OrderItemFeeTypeUnknown",
	OrderItemFeeTypeProduct = "OrderItemFeeTypeProduct",
	OrderItemFeeTypePostage = "OrderItemFeeTypePostage",
	OrderItemFeeTypeOther = "OrderItemFeeTypeOther",
	OrderItemFeeTypePlatformPromotionDiscount = "OrderItemFeeTypePlatformPromotionDiscount",
	OrderItemFeeTypeLocalDelivery = "OrderItemFeeTypeLocalDelivery"
}

export enum OrderItemWrapperType {
	OrderItemWrapperTypeUnknown = "OrderItemWrapperTypeUnknown",
	OrderItemWrapperTypeAsEzbuyOrder = "OrderItemWrapperTypeAsEzbuyOrder",
	OrderItemWrapperTypeAsEzbuyPackage = "OrderItemWrapperTypeAsEzbuyPackage"
}

export enum OrderItemRemarkSource {
	OrderItemRemarkSourceUnknown = "OrderItemRemarkSourceUnknown",
	OrderItemRemarkSourceEzbuyCustomer = "OrderItemRemarkSourceEzbuyCustomer",
	OrderItemRemarkSourceEzbuyOp = "OrderItemRemarkSourceEzbuyOp",
	OrderItemRemarkSourceEzSeller = "OrderItemRemarkSourceEzSeller"
}

export enum OrderItemWarehouse {
	OrderItemWarehouseUnknown = "OrderItemWarehouseUnknown",
	OrderItemWarehouseShanghai = "OrderItemWarehouseShanghai",
	OrderItemWarehouseGuangzhou = "OrderItemWarehouseGuangzhou",
	OrderItemWarehouseAmerican = "OrderItemWarehouseAmerican",
	OrderItemWarehouseTaiwan = "OrderItemWarehouseTaiwan",
	OrderItemWarehouseSingapore = "OrderItemWarehouseSingapore",
	OrderItemWarehouseMalaysia = "OrderItemWarehouseMalaysia",
	OrderItemWarehouseINCHEON = "OrderItemWarehouseINCHEON",
	OrderItemWarehouseJapan = "OrderItemWarehouseJapan"
}

export enum OrderItemDestination {
	OrderItemDestinationUnknown = "OrderItemDestinationUnknown",
	OrderItemDestinationSG = "OrderItemDestinationSG",
	OrderItemDestinationMY = "OrderItemDestinationMY",
	OrderItemDestinationTH = "OrderItemDestinationTH",
	OrderItemDestinationID = "OrderItemDestinationID"
}

export enum OrderItemBillStatus {
	OrderItemBillStatusUnknown = "OrderItemBillStatusUnknown",
	OrderItemBillStatusPending = "OrderItemBillStatusPending",
	OrderItemBillStatusBilled = "OrderItemBillStatusBilled"
}

export enum OrderItemTrackStatus {
	OrderItemTrackStatusUnknown = "OrderItemTrackStatusUnknown",
	OrderItemTrackStatusCancelled = "OrderItemTrackStatusCancelled",
	OrderItemTrackStatusPending = "OrderItemTrackStatusPending",
	OrderItemTrackStatusDispatched = "OrderItemTrackStatusDispatched",
	OrderItemTrackStatusWarehouseReceived = "OrderItemTrackStatusWarehouseReceived",
	OrderItemTrackStatusPendingDelivery = "OrderItemTrackStatusPendingDelivery",
	OrderItemTrackStatusCompleted = "OrderItemTrackStatusCompleted",
	OrderItemTrackStatusReturnPending = "OrderItemTrackStatusReturnPending",
	OrderItemTrackStatusReturnDispatched = "OrderItemTrackStatusReturnDispatched",
	OrderItemTrackStatusReturnCompleted = "OrderItemTrackStatusReturnCompleted"
}

export enum OrderItemPromotionType {
	OrderItemPromotionTypeUnknown = "OrderItemPromotionTypeUnknown",
	OrderItemPromotionTypeFlashSale = "OrderItemPromotionTypeFlashSale",
	OrderItemPromotionTypeCashOff = "OrderItemPromotionTypeCashOff",
	OrderItemPromotionTypeFriendsDeal = "OrderItemPromotionTypeFriendsDeal",
	OrderItemPromotionTypeFreeShipping = "OrderItemPromotionTypeFreeShipping",
	OrderItemPromotionTypeMNCashOff = "OrderItemPromotionTypeMNCashOff",
	OrderItemPromotionTypeMixed = "OrderItemPromotionTypeMixed",
	OrderItemPromotionTypeOldFlashSale = "OrderItemPromotionTypeOldFlashSale",
	OrderItemPromotionTypeOldCashOff = "OrderItemPromotionTypeOldCashOff",
	OrderItemPromotionTypeOldFriendsDeal = "OrderItemPromotionTypeOldFriendsDeal",
	OrderItemPromotionTypeOldFreeShipping = "OrderItemPromotionTypeOldFreeShipping"
}

export interface OrderCommitOldItem {
	/**
	 * @pattern ^\d+$
	 */
	id: string;
	forMigrate: boolean;
}

export interface OpResult {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	code: number;
	error: string;
}

export interface OrderCommitOld {
	item: OrderCommitOldItem[];
}

export interface OrderCommitOldResp {
	result: OpResult[];
}

export interface OrderUpdateTrackItem {
	/**
	 * @pattern ^\d+$
	 */
	id: string;
	shipper: string;
	trackingNumber: string;
}

export interface OrderUpdateTrack {
	item: OrderUpdateTrackItem[];
}

export interface OrderUpdateTrackResp {
	result: OpResult[];
}

export interface OrderDispatchItem {
	/**
	 * @pattern ^\d+$
	 */
	id: string;
	shipper: string;
	trackingNumber: string;
}

export interface OrderDispatch {
	item: OrderDispatchItem[];
}

export interface OrderDispatchResp {
	result: OpResult[];
}

export interface OrderUpdateTrackStatusItem {
	/**
	 * @pattern ^\d+$
	 */
	id: string;
	status: OrderItemTrackStatus;
}

export interface OrderUpdateTrackStatus {
	item: OrderUpdateTrackStatusItem[];
}

export interface OrderUpdateTrackStatusResp {
	result: OpResult[];
}

export interface OrderCancelItem {
	/**
	 * @pattern ^\d+$
	 */
	id: string;
}

export interface OrderCancel {
	item: OrderCancelItem[];
}

export interface OrderCancelResp {
	result: OpResult[];
}

export interface OrderSearch {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	shopId: number;
	AppName: string;
	orderNumber: string[];
	status: number[];
	/**
	 * @pattern ^\d+$
	 */
	startPayDate: string[];
	/**
	 * @pattern ^\d+$
	 */
	endPayDate: string[];
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	pageIndex: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	pageSize: number;
}

export interface OrderInfo {
	orderNumber: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	productId: number;
	productName: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	status: number;
	/**
	 * @pattern ^\d+$
	 */
	createDate: string;
	/**
	 * @pattern ^\d+$
	 */
	paidDate: string;
	items: OrderItem[];
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	warehouse: number;
	remark: string;
}

export interface OrderItem {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	orderItemId: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	skuId: number;
	skuName: string;
	/**
	 * @minimum 0
	 */
	unitPrice: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	quantity: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	status: number;
	sellerSkuId: string;
}

export interface OrderSearchResp {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	totalCount: number;
	orders: OrderInfo[];
}

export interface OrderSellerDispatch {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	shopId: number;
	appName: string;
	orderNumber: string;
	shipperName: string;
	trackingNumber: string;
}

export interface OrderSellerDispatchResp {
	success: boolean;
	message: string;
}

export interface OrderItemNotInStock {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	shopId: number;
	appName: string;
	orderNumber: string;
	skus: SkuStockOut[];
}

export interface SkuStockOut {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	skuId: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	quantity: number;
	reason: string;
}

export interface OrderItemNotInStockResp {
	success: boolean;
	message: string;
}

export interface OrderCommitOrder {
	/**
	 * @pattern ^\d+$
	 */
	id: string;
	/**
	 * @pattern ^\d+$
	 */
	customerID: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	regionID: number;
	item: OrderCommitOrderItem[];
	/**
	 * @pattern ^\d+$
	 */
	createDate: string;
	/**
	 * @pattern ^\d+$
	 */
	payDate: string;
}

export interface OrderCommitOrderItem {
	/**
	 * @pattern ^\d+$
	 */
	id: string;
	/**
	 * @pattern ^\d+$
	 */
	gpid: string;
	/**
	 * @pattern ^\d+$
	 */
	skuID: string;
	/**
	 * @pattern ^\d+$
	 */
	qty: string;
	/**
	 * @pattern ^\d+$
	 */
	unitPrice: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	shipmentTypeID: number;
	warehouse: OrderItemWarehouse;
	remark: string;
	unavailable: boolean;
}

export interface OrderCommit {
	order: OrderCommitOrder[];
}

export interface OrderCommitResp {
	result: OpResult[];
}

export interface OrderUpdateTrackByOrderNum {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	shopId: number;
	appName: string;
	orderNum: string;
	shipper: string;
	trackingNumber: string;
}

export interface OrderUpdateTrackByOrderNumResp {
	success: boolean;
	message: string;
}

export interface OrderRemark {
	/**
	 * @pattern ^\d+$
	 */
	orderId: string;
	remark: string;
	source: OrderItemRemarkSource;
	createBy: string;
	/**
	 * @pattern ^\d+$
	 */
	createDate: string;
}

export interface OrderRemarkMulit {
	remarks: OrderRemark[];
}

export interface OrderRemarkResp {
	result: OpResult;
}

export interface OrderRemarkMulitResp {
	result: OpResult;
}

export interface OrderCommitRequest {
	/**
	 * @pattern ^\d+$
	 */
	newOrderId: string;
}

export interface OrderCommitRequestResp {
	request: OrderCommitOrder;
}

export interface GetOrderItemByNumberReq {
	orderNumber: string;
}

export interface GetOrderItemByNumberResp {
	result: EzsellerResult;
	orderNumber: string;
	/**
	 * @pattern ^\d+$
	 */
	orderItemId: string;
	/**
	 * @pattern ^\d+$
	 */
	productId: string;
	productName: string;
	/**
	 * @minimum 0
	 */
	orderAmount: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	shopId: number;
	shopName: string;
	alreadySettled: boolean;
}

export interface OrderNewSearch {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	shopId: number;
	AppName: string;
	orderNumber: string[];
	status: OrderItemTrackStatus[];
	/**
	 * @pattern ^\d+$
	 */
	startPayDate: string[];
	/**
	 * @pattern ^\d+$
	 */
	endPayDate: string[];
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	pageIndex: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	pageSize: number;
	/**
	 * @pattern ^\d+$
	 */
	startCancelDate: string[];
	/**
	 * @pattern ^\d+$
	 */
	endCancelDate: string[];
}

export interface OrderNewSearchResp {
	/**
	 * @pattern ^\d+$
	 */
	totalCount: string;
	orderList: NewOrderInfo[];
}

export interface NewOrderInfo {
	orderNumber: string;
	productName: string;
	/**
	 * @pattern ^\d+$
	 */
	productId: string;
	sellerSkuId: string;
	skuName: string;
	/**
	 * @minimum 0
	 */
	unitPrice: number;
	/**
	 * @pattern ^\d+$
	 */
	quantity: string;
	status: OrderItemTrackStatus;
	warehouse: OrderItemWarehouse;
	/**
	 * @pattern ^\d+$
	 */
	payDate: string;
	/**
	 * @pattern ^\d+$
	 */
	dispatchDate: string;
	remark: string;
	/**
	 * @pattern ^\d+$
	 */
	cancelDate: string;
}

export interface OrderNewItemNotStock {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	shopId: number;
	appName: string;
	orderNumber: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	quantity: number;
	reason: string;
}

export interface OrderNewItemNotStockResp {
	success: boolean;
	message: string;
}

export interface StockInQtyAlterReq {
	/**
	 * @pattern ^\d+$
	 */
	newOrderId: string;
	/**
	 * @pattern ^\d+$
	 */
	newOrderItemId: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	qtyAlter: number;
	reason: EzOrderOrderItemOperType;
}

export interface StockInQtyAlterResp {
	result: OpResult;
}

export interface GetStockInQtyReq {
	orderItemNum: string[];
}

export interface GetStockInQtyResp {
	stockInQty: GetStockInQty[];
}

export interface GetStockInQty {
	orderItemNum: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	qty: number;
}

export interface Shipment {
	/**
	 * @pattern ^\d+$
	 */
	trackId: string;
	/**
	 * @pattern ^\d+$
	 */
	orderItemId: string;
	shipper: string;
	trackNumber: string;
}

export interface GetUserOrderShipmentReq {
	/**
	 * @pattern ^\d+$
	 */
	orderItemId: string;
}

export interface GetUserOrderShipmentResp {
	result: EzsellerResult;
	shipments: Shipment[];
}

export interface AppendUserOrderShipmentNumberReq {
	shipment: Shipment;
}

export interface AppendUserOrderShipmentNumberResp {
	result: EzsellerResult;
}

export interface AppendShipmentNumber4APIReq {
	orderNumber: string;
	shipper: string;
	trackNumber: string;
}

export interface AppendShipmentNumber4APIResp {
	result: EzsellerResult;
}

export function CommitOld(payload: Partial<OrderCommitOld>) {
	return webapi<OrderCommitOldResp>("ezseller.Order/CommitOld", payload);
}

export function UpdateTrack(payload: Partial<OrderUpdateTrack>) {
	return webapi<OrderUpdateTrackResp>("ezseller.Order/UpdateTrack", payload);
}

export function Dispatch(payload: Partial<OrderDispatch>) {
	return webapi<OrderDispatchResp>("ezseller.Order/Dispatch", payload);
}

export function UpdateTrackStatus(payload: Partial<OrderUpdateTrackStatus>) {
	return webapi<OrderUpdateTrackStatusResp>("ezseller.Order/UpdateTrackStatus", payload);
}

export function Cancel(payload: Partial<OrderCancel>) {
	return webapi<OrderCancelResp>("ezseller.Order/Cancel", payload);
}

export function Search(payload: Partial<OrderSearch>) {
	return webapi<OrderSearchResp>("ezseller.Order/Search", payload);
}

export function SellerDispatch(payload: Partial<OrderSellerDispatch>) {
	return webapi<OrderSellerDispatchResp>("ezseller.Order/SellerDispatch", payload);
}

export function ItemNotInStock(payload: Partial<OrderItemNotInStock>) {
	return webapi<OrderItemNotInStockResp>("ezseller.Order/ItemNotInStock", payload);
}

export function Commit(payload: Partial<OrderCommit>) {
	return webapi<OrderCommitResp>("ezseller.Order/Commit", payload);
}

export function UpdateTrackByOrderNum(payload: Partial<OrderUpdateTrackByOrderNum>) {
	return webapi<OrderUpdateTrackByOrderNumResp>("ezseller.Order/UpdateTrackByOrderNum", payload);
}

export function Remark(payload: Partial<OrderRemark>) {
	return webapi<OrderRemarkResp>("ezseller.Order/Remark", payload);
}

export function RemarkMulit(payload: Partial<OrderRemarkMulit>) {
	return webapi<OrderRemarkMulitResp>("ezseller.Order/RemarkMulit", payload);
}

export function CommitRequest(payload: Partial<OrderCommitRequest>) {
	return webapi<OrderCommitRequestResp>("ezseller.Order/CommitRequest", payload);
}

export function GetOrderItemByNumber(payload: Partial<GetOrderItemByNumberReq>) {
	return webapi<GetOrderItemByNumberResp>("ezseller.Order/GetOrderItemByNumber", payload);
}

export function StockInQtyAlter(payload: Partial<StockInQtyAlterReq>) {
	return webapi<StockInQtyAlterResp>("ezseller.Order/StockInQtyAlter", payload);
}

export function GetStockInQty(payload: Partial<GetStockInQtyReq>) {
	return webapi<GetStockInQtyResp>("ezseller.Order/GetStockInQty", payload);
}

export function GetUserOrderShipment(payload: Partial<GetUserOrderShipmentReq>) {
	return webapi<GetUserOrderShipmentResp>("ezseller.Order/GetUserOrderShipment", payload);
}

export function AppendUserOrderShipmentNumber(payload: Partial<AppendUserOrderShipmentNumberReq>) {
	return webapi<AppendUserOrderShipmentNumberResp>(
		"ezseller.Order/AppendUserOrderShipmentNumber",
		payload
	);
}

export function SearchOrder4API(payload: Partial<OrderNewSearch>) {
	return webapi<OrderNewSearchResp>("ezseller.Order/SearchOrder4API", payload);
}

export function DispatchOrder4API(payload: Partial<OrderSellerDispatch>) {
	return webapi<OrderSellerDispatchResp>("ezseller.Order/DispatchOrder4API", payload);
}

export function RegisterOutOfStock4API(payload: Partial<OrderNewItemNotStock>) {
	return webapi<OrderNewItemNotStockResp>("ezseller.Order/RegisterOutOfStock4API", payload);
}

export function UpdateTrack4API(payload: Partial<OrderUpdateTrackByOrderNum>) {
	return webapi<OrderUpdateTrackByOrderNumResp>("ezseller.Order/UpdateTrack4API", payload);
}

export function AppendShipmentNumber4API(payload: Partial<AppendShipmentNumber4APIReq>) {
	return webapi<AppendShipmentNumber4APIResp>("ezseller.Order/AppendShipmentNumber4API", payload);
}

export default {
	CommitOld,
	UpdateTrack,
	Dispatch,
	UpdateTrackStatus,
	Cancel,
	Search,
	SellerDispatch,
	ItemNotInStock,
	Commit,
	UpdateTrackByOrderNum,
	Remark,
	RemarkMulit,
	CommitRequest,
	GetOrderItemByNumber,
	StockInQtyAlter,
	GetStockInQty,
	GetUserOrderShipment,
	AppendUserOrderShipmentNumber,
	SearchOrder4API,
	DispatchOrder4API,
	RegisterOutOfStock4API,
	UpdateTrack4API,
	AppendShipmentNumber4API
};
