/**
 * This file is auto-generated by protobufgen
 * Don't change manually
 */





export interface Page {
	pageNum: number;
	pageRows: number;
	totalCount: number;
	pageCount: number;
	hasNext: boolean;
}



