/**
 * This file is auto-generated by protobufgen
 * Don't change manually
 */

import { Product as AssassinProduct } from "../assassin/assassin";
import { Result as EzsellerResult } from "../ezseller/result";
import { Empty as CommonEmpty } from "../common/empty";
import webapi from "../webapi";

export enum ImportProductSource {
	ImportProductSourceUnknown = "ImportProductSourceUnknown",
	ImportProductSourceTaobao = "ImportProductSourceTaobao",
	ImportProductSourceTmall = "ImportProductSourceTmall",
	ImportProductSourceYqh = "ImportProductSourceYqh",
	ImportProductSourceAmazon = "ImportProductSourceAmazon",
	ImportProductSourceGongYun = "ImportProductSourceGongYun",
	ImportProductSourceOne688 = "ImportProductSourceOne688",
	ImportProductSourceMaxlimit = "ImportProductSourceMaxlimit"
}

export enum ImportUrlType {
	ImportUrlTypeUnknown = "ImportUrlTypeUnknown",
	ImportUrlTypeShop = "ImportUrlTypeShop",
	ImportUrlTypeProduct = "ImportUrlTypeProduct"
}

export enum ImportSubTaskManageOp {
	ImportSubTaskManageOpUnknown = "ImportSubTaskManageOpUnknown",
	ImportSubTaskManageOpOnSale = "ImportSubTaskManageOpOnSale",
	ImportSubTaskManageOpOffSale = "ImportSubTaskManageOpOffSale",
	ImportSubTaskManageOpDel = "ImportSubTaskManageOpDel",
	ImportSubTaskManageOpRetry = "ImportSubTaskManageOpRetry",
	ImportSubTaskManageOpSetSensitive = "ImportSubTaskManageOpSetSensitive",
	ImportSubTaskManageOpUnSetSensitive = "ImportSubTaskManageOpUnSetSensitive"
}

export enum ProductImportTaskTabStatus {
	ProductImportTaskTabStatusUnknown = "ProductImportTaskTabStatusUnknown",
	ProductImportTaskTabStatusTodo = "ProductImportTaskTabStatusTodo",
	ProductImportTaskTabStatusPub = "ProductImportTaskTabStatusPub",
	ProductImportTaskTabStatusDel = "ProductImportTaskTabStatusDel",
	ProductImportTaskTabStatusFail = "ProductImportTaskTabStatusFail"
}

export enum ProductImportTaskStatus {
	ProductImportTaskStatusUnknown = "ProductImportTaskStatusUnknown",
	ProductImportTaskStatusPending = "ProductImportTaskStatusPending",
	ProductImportTaskStatusProcessing = "ProductImportTaskStatusProcessing",
	ProductImportTaskStatusAborted = "ProductImportTaskStatusAborted",
	ProductImportTaskStatusSuc = "ProductImportTaskStatusSuc",
	ProductImportTaskStatusFail = "ProductImportTaskStatusFail"
}

export interface ProductGet {
	/**
	 * @pattern ^\d+$
	 */
	gpid: string;
}

export interface ProductGetResp {
	product: AssassinProduct;
}

export interface ProductMGet {
	/**
	 * @pattern ^\d+$
	 */
	gpid: string[];
}

export interface ProductMGetResp {
	product: AssassinProduct[];
}

export interface ProductMExpire {
	/**
	 * @pattern ^\d+$
	 */
	gpid: string[];
}

export interface ProductMExpireResp {}

export interface SPU {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	gpid: number;
	nameCN: string;
	nameEN: string;
	isSensitive: boolean;
	skuIds: number[];
	isOnSale: boolean;
	/**
	 * @pattern ^\d+$
	 */
	createDate: string;
	/**
	 * @pattern ^\d+$
	 */
	cid: string;
	primaryImg: string;
	description: string;
	images: string[];
	attributes: { [key: string]: string };
	skuProps: SkuProp[];
	/**
	 * @pattern ^\d+$
	 */
	aliCid: string;
	aliRefId: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	importSource: number;
}

export interface ProductGetSPU {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	gpid: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	shopId: number;
	sellerAppName: string;
}

export interface ProductGetSPUResp {
	spu: SPU;
}

export interface ProductSearchSPU {
	name: string[];
	isSensitive: boolean[];
	isOnSale: boolean[];
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	shopId: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	pageIndex: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	pageSize: number;
	sellerAppName: string;
}

export interface ProductSearchSPUResp {
	spus: SPU[];
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	pageIndex: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	pageSize: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	totalCount: number;
}

export interface SKU {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	skuId: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	gpid: number;
	sellerSkuId: string;
	name: string;
	/**
	 * @minimum 0
	 */
	originPrice: number;
	/**
	 * @minimum 0
	 */
	price: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	quantity: number;
	/**
	 * @minimum 0
	 */
	weight: number;
	isOnSale: boolean;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	length: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	width: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	height: number;
	attributes: { [key: string]: string };
}

export interface SkuProp {
	prop: Property;
	values: PropertyValue[];
}

export interface Property {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	pid: number;
	pname: string;
}

export interface PropertyValue {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	vid: number;
	name: string;
	image: string;
}

export interface ProductGetSKU {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	skuId: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	shopId: number;
	sellerAppName: string;
}

export interface ProductGetSKUResp {
	sku: SKU;
}

export interface ProductUpdateSPU {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	gpid: number;
	nameCN: string[];
	nameEN: string[];
	isSensitive: boolean[];
	isOnSale: boolean[];
	isDeleted: boolean[];
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	shopId: number;
	sellerAppName: string;
	description: string[];
	images: string[];
	attributes: { [key: string]: string };
	skuProps: SkuProp[];
	/**
	 * @pattern ^\d+$
	 */
	cid: string[];
	/**
	 * @pattern ^\d+$
	 */
	aliCid: string[];
	aliRefId: string[];
	importSource: number[];
}

export interface ProductUpdateSPUResp {
	success: boolean;
	message: string;
}

export interface ProductUpdateSKU {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	skuId: number;
	originPrice: number[];
	price: number[];
	quantity: number[];
	weight: number[];
	isOnSale: boolean[];
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	shopId: number;
	sellerAppName: string;
}

export interface ProductUpdateSKUResp {
	success: boolean;
	message: string;
}

export interface ProductAddSPU {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	shopId: number;
	sellerAppName: string;
	productBase: SPU;
	skus: SKU[];
}

export interface ProductAddSPUResp {
	productBase: SPU;
	skus: SKU[];
}

export interface ProductGetSPUByRefId {
	refId: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	importSource: number;
}

export interface ProductGetSPUByRefIdResp {
	/**
	 * @pattern ^\d+$
	 */
	productId: string;
}

export interface ProductGetSkuBySellerSkuId {
	/**
	 * @pattern ^\d+$
	 */
	productId: string;
	sellerSkuId: string;
}

export interface ProductGetSkuBySellerSkuIdResp {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	skuId: number;
}

export interface ProductImportTaskAddReq {
	urls: string[];
	source: ImportProductSource;
}

export interface ProductImportTaskAddResp {
	result: EzsellerResult;
}

export interface ProductTaskProductSimpleInfo {
	childTaskId: string;
	title: string;
	catName: string;
	origUrl: string;
	primaryImg: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	skuNum: number;
	price: string;
	quantity: string;
	/**
	 * @minimum 0
	 */
	weight: number;
	sensitive: boolean;
	onSale: boolean;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	productId: number;
}

export interface ProductTaskProductSimpleInfoSet {
	infos: ProductTaskProductSimpleInfo[];
}

export interface ProductImportTaskListReq {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	limit: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	offset: number;
}

export interface ProductImportTaskInfo {
	taskId: string;
	source: ImportProductSource;
	/**
	 * @pattern ^\d+$
	 */
	createTime: string;
	status: ProductImportTaskStatus;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	total: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	sucNum: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	failNum: number;
}

export interface ProductImportTaskListResp {
	result: EzsellerResult;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	total: number;
	infos: ProductImportTaskInfo[];
}

export interface ProductImportTaskDetailListReq {
	taskId: string;
	status: ProductImportTaskTabStatus;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	limit: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	offset: number;
}

export interface ProductImportTaskDetailGroup {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	toPubCount: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	pubCount: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	delCount: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	failCount: number;
}

export interface ProductImportTaskDetailListResp {
	result: EzsellerResult;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	total: number;
	isSpu: boolean;
	group: ProductImportTaskDetailGroup;
	set: ProductTaskProductSimpleInfoSet[];
}

export interface ProductImportSubTaskManageReq {
	op: ImportSubTaskManageOp;
	subTaskIds: string[];
}

export interface ProductImportSubTaskManageResp {
	result: EzsellerResult;
	errMsg: ProductOnSaleErr[];
}

export interface ProductOnSaleErr {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	productId: number;
	taskId: string;
	msg: string;
}

export interface ProductSaveControlReq {
	bucket: string;
}

export function Get(payload: Partial<ProductGet>) {
	return webapi<ProductGetResp>("ezseller.Product/Get", payload);
}

export function MGet(payload: Partial<ProductMGet>) {
	return webapi<ProductMGetResp>("ezseller.Product/MGet", payload);
}

export function MExpire(payload: Partial<ProductMExpire>) {
	return webapi<ProductMExpireResp>("ezseller.Product/MExpire", payload);
}

export function GetSPU(payload: Partial<ProductGetSPU>) {
	return webapi<ProductGetSPUResp>("ezseller.Product/GetSPU", payload);
}

export function SearchSPU(payload: Partial<ProductSearchSPU>) {
	return webapi<ProductSearchSPUResp>("ezseller.Product/SearchSPU", payload);
}

export function GetSKU(payload: Partial<ProductGetSKU>) {
	return webapi<ProductGetSKUResp>("ezseller.Product/GetSKU", payload);
}

export function UpdateSPU(payload: Partial<ProductUpdateSPU>) {
	return webapi<ProductUpdateSPUResp>("ezseller.Product/UpdateSPU", payload);
}

export function UpdateSKU(payload: Partial<ProductUpdateSKU>) {
	return webapi<ProductUpdateSKUResp>("ezseller.Product/UpdateSKU", payload);
}

export function AddSPU(payload: Partial<ProductAddSPU>) {
	return webapi<ProductAddSPUResp>("ezseller.Product/AddSPU", payload);
}

export function GetSPUByRefId(payload: Partial<ProductGetSPUByRefId>) {
	return webapi<ProductGetSPUByRefIdResp>("ezseller.Product/GetSPUByRefId", payload);
}

export function GetSkuBySellerSkuId(payload: Partial<ProductGetSkuBySellerSkuId>) {
	return webapi<ProductGetSkuBySellerSkuIdResp>("ezseller.Product/GetSkuBySellerSkuId", payload);
}

export function ImportTaskAdd(payload: Partial<ProductImportTaskAddReq>) {
	return webapi<ProductImportTaskAddResp>("ezseller.Product/ImportTaskAdd", payload);
}

export function ImportTaskList(payload: Partial<ProductImportTaskListReq>) {
	return webapi<ProductImportTaskListResp>("ezseller.Product/ImportTaskList", payload);
}

export function ImportTaskDetailList(payload: Partial<ProductImportTaskDetailListReq>) {
	return webapi<ProductImportTaskDetailListResp>("ezseller.Product/ImportTaskDetailList", payload);
}

export function ImportSubTaskManage(payload: Partial<ProductImportSubTaskManageReq>) {
	return webapi<ProductImportSubTaskManageResp>("ezseller.Product/ImportSubTaskManage", payload);
}

export function ResetSyncProduct(payload: Partial<CommonEmpty>) {
	return webapi<CommonEmpty>("ezseller.Product/ResetSyncProduct", payload);
}

export function ProductSaveControl(payload: Partial<ProductSaveControlReq>) {
	return webapi<CommonEmpty>("ezseller.Product/ProductSaveControl", payload);
}

export default {
	Get,
	MGet,
	MExpire,
	GetSPU,
	SearchSPU,
	GetSKU,
	UpdateSPU,
	UpdateSKU,
	AddSPU,
	GetSPUByRefId,
	GetSkuBySellerSkuId,
	ImportTaskAdd,
	ImportTaskList,
	ImportTaskDetailList,
	ImportSubTaskManage,
	ResetSyncProduct,
	ProductSaveControl
};
