/**
 * This file is auto-generated by protobufgen
 * Don't change manually
 */

import { ResultResp as AppcommonResultResp, SortOption as AppcommonSortOption, SearchSortCond as AppcommonSearchSortCond, SearchFilterCond as AppcommonSearchFilterCond, SimpleProduct as AppcommonSimpleProduct, SearchFilter as AppcommonSearchFilter } from "../appcommon/common_public";
import webapi from "../webapi";

export enum LayoutType {
	LayoutTypeTop = "LayoutTypeTop",
	LayoutTypeCarousel = "LayoutTypeCarousel",
	LayoutTypeBanner = "LayoutTypeBanner",
	LayoutTypeGrid = "LayoutTypeGrid",
	LayoutTypeFlow = "LayoutTypeFlow",
}



export interface GroupLayoutInfo {
	layoutType: LayoutType;
	columnCount: number;
	cellRatio: number;
	titleColor: string;
	bottomGap: number;
}

export interface HomePageEntrance {
	name: string;
	imageURL: string;
	link: string;
	desc: string;
}

export interface HomePageArea {
	name: string;
	entranceList: HomePageEntrance[];
	groupLayoutInfo: GroupLayoutInfo;
	link: string;
}

export interface GetHomeAreasReq {
	sellerName: string;
	isPreview: boolean;
}

export interface GetHomeAreasResp {
	result: AppcommonResultResp;
	areas: HomePageArea[];
}

export interface GetSellerCategorysReq {
	sellerName: string;
}

export interface GetSellerCategorysResp {
	result: AppcommonResultResp;
	categorys: SellerCategory[];
}

export interface GetHomePageSortOptionsReq {
	sellerName: string;
}

export interface GetHomePageSortOptionsResp {
	result: AppcommonResultResp;
	sortOptions: AppcommonSortOption[];
}

export interface SearchCategoryProductsReq {
	sellerName: string;
	categoryId: number;
	sortConds: AppcommonSearchSortCond[];
	filterConds: AppcommonSearchFilterCond[];
	limit: number;
	offset: number;
}

export interface SearchCategoryProductsResp {
	result: AppcommonResultResp;
	products: AppcommonSimpleProduct[];
	sorts: string[];
	filters: AppcommonSearchFilter[];
	sortOptions: AppcommonSortOption[];
	total: number;
}

export interface SearchByKeywordsReq {
	sellerName: string;
	keywords: string;
	sortConds: AppcommonSearchSortCond[];
	filterConds: AppcommonSearchFilterCond[];
	limit: number;
	offset: number;
}

export interface SearchByKeywordsResp {
	result: AppcommonResultResp;
	products: AppcommonSimpleProduct[];
	sorts: string[];
	filters: AppcommonSearchFilter[];
	sortOptions: AppcommonSortOption[];
	total: number;
}

export interface SellerCategory {
	categoryId: number;
	name: string;
	subCategorys: SellerCategory[];
}



export function SearchByKeywords(payload: SearchByKeywordsReq) {
	return webapi<SearchByKeywordsResp>("ezseller.SellerStore/SearchByKeywords", payload);
}

export function SearchCategoryProducts(payload: SearchCategoryProductsReq) {
	return webapi<SearchCategoryProductsResp>("ezseller.SellerStore/SearchCategoryProducts", payload);
}

export function GetHomePageSortOptions(payload: GetHomePageSortOptionsReq) {
	return webapi<GetHomePageSortOptionsResp>("ezseller.SellerStore/GetHomePageSortOptions", payload);
}

export function GetSellerCategorys(payload: GetSellerCategorysReq) {
	return webapi<GetSellerCategorysResp>("ezseller.SellerStore/GetSellerCategorys", payload);
}

export function GetHomeAreas(payload: GetHomeAreasReq) {
	return webapi<GetHomeAreasResp>("ezseller.SellerStore/GetHomeAreas", payload);
}


export default {
	SearchByKeywords,
	SearchCategoryProducts,
	GetHomePageSortOptions,
	GetSellerCategorys,
	GetHomeAreas,
};


