/**
 * This file is auto-generated by protobufgen
 * Don't change manually
 */

import { Result as EzsellerResult } from "./result";
import webapi from "../webapi";

export enum SmsMessageType {
	SmsMessageTypeVeriUnknown = "SmsMessageTypeVeriUnknown",
	SmsMessageTypeVeriCode = "SmsMessageTypeVeriCode",
}



export interface SmsSendVerificationCode {
	Phone: string;
	Expiration: string;
	From: string;
}

export interface SmsSendVerificationCodeResp {
	result: EzsellerResult;
}

export interface SmsVerifyCode {
	Phone: string;
	Code: string;
}

export interface SmsVerifyCodeResp {
	result: EzsellerResult;
}



export function SendVerificationCode(payload: SmsSendVerificationCode) {
	return webapi<SmsSendVerificationCodeResp>("ezseller.Sms/SendVerificationCode", payload);
}

export function VerifyCode(payload: SmsVerifyCode) {
	return webapi<SmsVerifyCodeResp>("ezseller.Sms/VerifyCode", payload);
}


export default {
	SendVerificationCode,
	VerifyCode,
};


