/**
 * This file is auto-generated by protobufgen
 * Don't change manually
 */





export interface ResultResp {
	result: boolean;
	msg: string;
}

export interface SimpleProduct {
	gpid: string;
	url: string;
	name: string;
	pictureUrl: string;
	localUnitPrice: number;
	originalLocalUnitPrice: number;
	originCode: string;
	discountRate: string;
	isCashOff: boolean;
	cashOffColor: string;
	vendorName: string;
	isBuyforme: boolean;
	originName: string;
	tag: ProductTag;
	titleIcons: TitleIcon[];
}

export interface TitleIcon {
	icon: string;
	text: string;
}

export interface ProductTag {
	text: string;
	color: string;
	img: string;
}

export interface TCommonOptionItemWithId {
	id: number;
	name: string;
	itemDescription: string;
}

export interface SearchFilterField {
	name: string;
	productCount: number;
}

export interface SearchFilter {
	name: string;
	fields: SearchFilterField[];
	emphasized: boolean;
}

export interface SearchFilterCond {
	filterName: string;
	fieldName: string;
}

export interface SearchSortCond {
	sort: string;
	isDesc: boolean;
}

export interface SortOption {
	code: string;
	name: string;
	descTitle: string;
	ascTitle: string;
}



