/**
 * This file is auto-generated by protobufgen
 * Don't change manually
 */

export enum Region {
	RegionInvalid = "RegionInvalid",
	RegionCN = "RegionCN",
	RegionTW = "RegionTW",
	RegionUS = "RegionUS",
	RegionKR = "RegionKR",
	RegionJP = "RegionJP",
	RegionSG = "RegionSG",
	RegionMY = "RegionMY",
	RegionTH = "RegionTH",
	RegionID = "RegionID",
	RegionPK = "RegionPK",
	RegionTWC = "RegionTWC"
}
