/**
 * This file is auto-generated by protobufgen
 * Don't change manually
 */

export enum Warehouse {
	WarehouseInvalid = "WarehouseInvalid",
	WarehouseGuangzhou = "WarehouseGuangzhou",
	WarehouseShanghai = "WarehouseShanghai",
	WarehouseAmerican = "WarehouseAmerican",
	WarehouseTaiwan = "WarehouseTaiwan",
	WarehouseSingapore = "WarehouseSingapore",
	WarehouseMalaysia = "WarehouseMalaysia",
	WarehouseINCHEON = "WarehouseINCHEON",
	WarehouseJapan = "WarehouseJapan"
}
