/**
 * This file is auto-generated by tgen
 * Don't change manually
 */
import webapi from "./webapi";




export interface AliProperty {
	id: number;
	name: string;
}
export interface AliPropertyValue {
	pvid: number;
	pvname: string;
	pid: number;
	pname: string;
	vid: number;
	vname: string;
	totalcount: number;
}
export interface AliValue {
	id: number;
	name: string;
}
export interface AlipropertyValueResponse {
	total: number;
	alipropertyvalues: AliPropertyValue[];
}
export interface Category {
	cid: number;
	name: string;
	translation: Translation;
	disabled: boolean;
	breadcrumb?: CategoryBreadCrumb[];
}
export interface CategoryBreadCrumb {
	name: string;
	translation: Translation;
}
export interface CategoryPropertyValueSet {
	sid: number;
	categoryPath: Category[];
	propertyValueOptions: {[key: string]: PropertyValue[]};
	disabled: boolean;
}
export interface EzAliProertyValueResponse {
	total: number;
	aliPropertyValues: AliPropertyValue[];
}
export interface EzBuyPropertyResponse {
	total: number;
	properties: Property[];
}
export interface EzBuyValuesResposne {
	total: number;
	values: Value[];
}
export interface EzbuyMappingRule {
	pvmrid: number;
	pvid: number;
	pName: string;
	vName: string;
	aliPName: string;
	aliVName: string;
}
export interface EzbuyMappingRuleResponse {
	total: number;
	rules: EzbuyMappingRule[];
}
export interface EzbuyPropertyValueResponse {
	total: number;
	propertyValues: PropertyValue[];
}
export interface ListQuery {
	prefix: string;
	caseSensitive: boolean;
	limit: number;
}
export interface MappingRuleTask {
	taskId: number;
	status: number;
	ruleId: number;
	ezPname: string;
	ezVname: string;
	aliPname: string;
	aliVname: string;
	runedAt: number;
	runStartAt: number;
}
export interface MappingRuleTaskResponse {
	total: number;
	tasks: MappingRuleTask[];
}
export interface ProductListQuery {
	limit: number;
	lastId: number;
	sort?: string[];
}
export interface Property {
	pid: number;
	name: string;
	translation: Translation;
	disabled: boolean;
}
export interface PropertyValue {
	pvid: number;
	pid: number;
	pname: string;
	vid: number;
	vname: string;
	disabled: boolean;
	pvslug: string;
	pvname: string;
	translation: Translation;
}
export interface Translation {
	CN: string;
	MY: string;
}
export interface Value {
	vid: number;
	name: string;
	translation: Translation;
	disabled: boolean;
}
export interface ValueOptions {
	fixed: PropertyValue[];
	single: ValueOptionsItem[];
	multi: ValueOptionsItem[];
}
export interface ValueOptionsItem {
	pname: string;
	translation: Translation;
	pvs: PropertyValue[];
}


export function AddAliProperTyValueInMapping(pvid: number, aliPvid: number): Promise<boolean> {
	return webapi<boolean>("BootyBay.AddAliProperTyValueInMapping", { pvid, aliPvid });
}

export function AddCategory(parent: number, name: string, translation: Translation): Promise<Category> {
	return webapi<Category>("BootyBay.AddCategory", { parent, name, translation });
}

export function AddCidToPubCate(ezCid: number, cid: number): Promise<boolean> {
	return webapi<boolean>("BootyBay.AddCidToPubCate", { ezCid, cid });
}

export function AddMappingRule(ezpvid: number, aliPName: string, aliVName: string): Promise<boolean> {
	return webapi<boolean>("BootyBay.AddMappingRule", { ezpvid, aliPName, aliVName });
}

export function AddMappingRuleTask(ruleId: number): Promise<boolean> {
	return webapi<boolean>("BootyBay.AddMappingRuleTask", { ruleId });
}

export function AddProperty(name: string, translation: Translation): Promise<Property> {
	return webapi<Property>("BootyBay.AddProperty", { name, translation });
}

export function AddPropertyValue(pid: number, vid: number): Promise<PropertyValue> {
	return webapi<PropertyValue>("BootyBay.AddPropertyValue", { pid, vid });
}

export function AddPropertyValueByNames(pname: string, vname: string): Promise<PropertyValue> {
	return webapi<PropertyValue>("BootyBay.AddPropertyValueByNames", { pname, vname });
}

export function AddSubCategory(cid: number, subCid: number): Promise<boolean> {
	return webapi<boolean>("BootyBay.AddSubCategory", { cid, subCid });
}

export function AddValue(name: string, translation: Translation): Promise<Value> {
	return webapi<Value>("BootyBay.AddValue", { name, translation });
}

export function DelSubCategories(cid: number, subCids: number[]): Promise<boolean> {
	return webapi<boolean>("BootyBay.DelSubCategories", { cid, subCids });
}

export function DelValuesForProperty(pid: number, vids: number[]): Promise<boolean> {
	return webapi<boolean>("BootyBay.DelValuesForProperty", { pid, vids });
}

export function DisableCategory(cid: number, disabled: boolean): Promise<Category> {
	return webapi<Category>("BootyBay.DisableCategory", { cid, disabled });
}

export function DisableProperty(pid: number, disabled: boolean): Promise<Property> {
	return webapi<Property>("BootyBay.DisableProperty", { pid, disabled });
}

export function DisableValue(vid: number, disabled: boolean): Promise<Value> {
	return webapi<Value>("BootyBay.DisableValue", { vid, disabled });
}

export function GetAliPropertyByPrefix(query: ListQuery): Promise<AliProperty[]> {
	return webapi<AliProperty[]>("BootyBay.GetAliPropertyByPrefix", { query });
}

export function GetAliValueByPrefix(aliPid: number, limit: number, offset: number): Promise<AlipropertyValueResponse> {
	return webapi<AlipropertyValueResponse>("BootyBay.GetAliValueByPrefix", { aliPid, limit, offset });
}

export function GetCategories(query: ListQuery, parent: number): Promise<Category[]> {
	return webapi<Category[]>("BootyBay.GetCategories", { query, parent });
}

export function GetCategory(cid: number): Promise<Category> {
	return webapi<Category>("BootyBay.GetCategory", { cid });
}

export function GetCategoryPathValueOptions(categoryPath: Category[]): Promise<ValueOptions> {
	return webapi<ValueOptions>("BootyBay.GetCategoryPathValueOptions", { categoryPath });
}

export function GetCategoryValueOptions(cid: number, merged: boolean): Promise<ValueOptions> {
	return webapi<ValueOptions>("BootyBay.GetCategoryValueOptions", { cid, merged });
}

export function GetEzAliProertyValueMapping(ezpvid: number, limit: number, offset: number): Promise<EzAliProertyValueResponse> {
	return webapi<EzAliProertyValueResponse>("BootyBay.GetEzAliProertyValueMapping", { ezpvid, limit, offset });
}

export function GetEzBuyValuesByProertyId(ezpid: number, limit: number, offset: number): Promise<EzBuyValuesResposne> {
	return webapi<EzBuyValuesResposne>("BootyBay.GetEzBuyValuesByProertyId", { ezpid, limit, offset });
}

export function GetEzbuyProperties(limit: number, offset: number): Promise<EzBuyPropertyResponse> {
	return webapi<EzBuyPropertyResponse>("BootyBay.GetEzbuyProperties", { limit, offset });
}

export function GetEzbuyPropertyValues(limit: number, offset: number): Promise<EzbuyPropertyValueResponse> {
	return webapi<EzbuyPropertyValueResponse>("BootyBay.GetEzbuyPropertyValues", { limit, offset });
}

export function GetMappingRuleTaskByPvId(pvid: number, status: number, limit: number, offset: number): Promise<MappingRuleTaskResponse> {
	return webapi<MappingRuleTaskResponse>("BootyBay.GetMappingRuleTaskByPvId", { pvid, status, limit, offset });
}

export function GetMappingRuleTasks(status: number, limit: number, offset: number): Promise<MappingRuleTaskResponse> {
	return webapi<MappingRuleTaskResponse>("BootyBay.GetMappingRuleTasks", { status, limit, offset });
}

export function GetMappingRules(ezpvid: number, limit: number, offset: number): Promise<EzbuyMappingRuleResponse> {
	return webapi<EzbuyMappingRuleResponse>("BootyBay.GetMappingRules", { ezpvid, limit, offset });
}

export function GetProperties(query: ListQuery): Promise<Property[]> {
	return webapi<Property[]>("BootyBay.GetProperties", { query });
}

export function GetProperty(pid: number): Promise<Property> {
	return webapi<Property>("BootyBay.GetProperty", { pid });
}

export function GetSubCategories(cid: number): Promise<Category[]> {
	return webapi<Category[]>("BootyBay.GetSubCategories", { cid });
}

export function GetValue(vid: number): Promise<Value> {
	return webapi<Value>("BootyBay.GetValue", { vid });
}

export function GetValues(query: ListQuery): Promise<Value[]> {
	return webapi<Value[]>("BootyBay.GetValues", { query });
}

export function GetValuesForProperty(pname: string): Promise<PropertyValue[]> {
	return webapi<PropertyValue[]>("BootyBay.GetValuesForProperty", { pname });
}

export function ListCidToPabCates(ezCid: number): Promise<number[]> {
	return webapi<number[]>("BootyBay.ListCidToPabCates", { ezCid });
}

export function MappingRuleTaskRun(taskId: number): Promise<null> {
	return webapi<null>("BootyBay.MappingRuleTaskRun", { taskId });
}

export function RemoveAliPropertyValueInMapping(ezpvid: number, aliPvid: number): Promise<boolean> {
	return webapi<boolean>("BootyBay.RemoveAliPropertyValueInMapping", { ezpvid, aliPvid });
}

export function RemoveCidToPubCate(cid: number): Promise<boolean> {
	return webapi<boolean>("BootyBay.RemoveCidToPubCate", { cid });
}

export function RemoveMappingRule(pvmrid: number): Promise<boolean> {
	return webapi<boolean>("BootyBay.RemoveMappingRule", { pvmrid });
}

export function UpdateCategory(cid: number, name: string, translation: Translation): Promise<Category> {
	return webapi<Category>("BootyBay.UpdateCategory", { cid, name, translation });
}

export function UpdateCategoryValueOptions(cid: number, options: ValueOptions): Promise<ValueOptions> {
	return webapi<ValueOptions>("BootyBay.UpdateCategoryValueOptions", { cid, options });
}

export function UpdatePropKey(name: string, rename: string, translation: Translation): Promise<boolean> {
	return webapi<boolean>("BootyBay.UpdatePropKey", { name, rename, translation });
}

export function UpdatePropValue(name: string, rename: string, translation: Translation): Promise<boolean> {
	return webapi<boolean>("BootyBay.UpdatePropValue", { name, rename, translation });
}

export function UpdateSubCategories(cid: number, subCids: number[]): Promise<boolean> {
	return webapi<boolean>("BootyBay.UpdateSubCategories", { cid, subCids });
}



export default {
	AddAliProperTyValueInMapping,
	AddCategory,
	AddCidToPubCate,
	AddMappingRule,
	AddMappingRuleTask,
	AddProperty,
	AddPropertyValue,
	AddPropertyValueByNames,
	AddSubCategory,
	AddValue,
	DelSubCategories,
	DelValuesForProperty,
	DisableCategory,
	DisableProperty,
	DisableValue,
	GetAliPropertyByPrefix,
	GetAliValueByPrefix,
	GetCategories,
	GetCategory,
	GetCategoryPathValueOptions,
	GetCategoryValueOptions,
	GetEzAliProertyValueMapping,
	GetEzBuyValuesByProertyId,
	GetEzbuyProperties,
	GetEzbuyPropertyValues,
	GetMappingRuleTaskByPvId,
	GetMappingRuleTasks,
	GetMappingRules,
	GetProperties,
	GetProperty,
	GetSubCategories,
	GetValue,
	GetValues,
	GetValuesForProperty,
	ListCidToPabCates,
	MappingRuleTaskRun,
	RemoveAliPropertyValueInMapping,
	RemoveCidToPubCate,
	RemoveMappingRule,
	UpdateCategory,
	UpdateCategoryValueOptions,
	UpdatePropKey,
	UpdatePropValue,
	UpdateSubCategories,
};

