/**
 * This file is auto-generated by tgen
 * Don't change manually
 */
import webapi from "./webapi";




export interface ImportTask {
	id: string;
	type: string;
	url: string;
	state: string;
	remark: string;
	totalCount: number;
	fetchedCount: number;
	failedCount: number;
	createdAt: number;
	updatedAt: number;
}
export interface ImportTaskListResult {
	total: number;
	data: ImportTask[];
}
export interface ListQuery {
	offset: number;
	limit: number;
	sort: string[];
}
export interface Order {
	orderId: number;
	purchase: OrderPurchase;
	delivery: OrderDelivery;
	address: string;
	createdAt: number;
	updatedAt: number;
	state: string;
	remark: string;
}
export interface OrderDelivery {
	provider: string;
	sn: string;
}
export interface OrderFilter {
	state: string;
	startAt: number;
	endAt: number;
}
export interface OrderListResult {
	total: number;
	data: Order[];
}
export interface OrderPurchase {
	productId: number;
	name: string;
	propertyValues: {[key: string]: string};
	quantity: number;
	remark: string;
}
export interface ProductBase {
	pid: number;
	categoryId: number;
	name: string;
	description?: string;
	primaryImage: string;
	images?: string[];
	isOnSale: boolean;
	saleRegion: string[];
	originCode: string;
	price: number;
	weight: number;
	shipmentInfo: number;
	attributes: {[key: string]: string};
	quantity?: number;
}
export interface ProductDetail {
	base: ProductBase;
	skus: ProductSku[];
}
export interface ProductListFilter {
	sellerId?: number;
	categoryId?: number;
	saleRegion?: string;
}
export interface ProductListResult {
	total: number;
	data: ProductSimple[];
}
export interface ProductSimple {
	pid: number;
	categoryId: number;
	name: string;
	primaryImage: string;
	isOnSale: boolean;
	url: string;
	price: number;
}
export interface ProductSku {
	skuId: string;
	name: string;
	images?: string[];
	isOnSale: boolean;
	attributes: {[key: string]: string};
	price: number;
	weight: number;
	shipmentInfo: number;
	quantity: number;
}
export interface Seller {
	sellerId: number;
	name: string;
	shopName: string;
	cookie: string;
	logged: boolean;
}


export function ImportTaskAdd(sellerId: number, taskType: string, url: string): Promise<ImportTask> {
	return webapi<ImportTask>("CastleBlack.ImportTaskAdd", { sellerId, taskType, url });
}

export function ImportTaskList(sellerId: number, listQuery: ListQuery): Promise<ImportTaskListResult> {
	return webapi<ImportTaskListResult>("CastleBlack.ImportTaskList", { sellerId, listQuery });
}

export function OrderClose(sellerId: number, orderId: number, remark: string): Promise<Order> {
	return webapi<Order>("CastleBlack.OrderClose", { sellerId, orderId, remark });
}

export function OrderDeliveryUpdate(sellerId: number, orderId: number, delivery: OrderDelivery): Promise<Order> {
	return webapi<Order>("CastleBlack.OrderDeliveryUpdate", { sellerId, orderId, delivery });
}

export function OrderList(sellerId: number, listQuery: ListQuery, filter: OrderFilter): Promise<OrderListResult> {
	return webapi<OrderListResult>("CastleBlack.OrderList", { sellerId, listQuery, filter });
}

export function ProductAdd(sellerId: number, data: ProductBase, skus: ProductSku[]): Promise<ProductDetail> {
	return webapi<ProductDetail>("CastleBlack.ProductAdd", { sellerId, data, skus });
}

export function ProductGet(pid: number): Promise<ProductDetail> {
	return webapi<ProductDetail>("CastleBlack.ProductGet", { pid });
}

export function ProductList(sellerId: number, listQuery: ListQuery): Promise<ProductListResult> {
	return webapi<ProductListResult>("CastleBlack.ProductList", { sellerId, listQuery });
}

export function ProductListPublic(listQuery: ListQuery, filter: ProductListFilter, originCode: string): Promise<ProductListResult> {
	return webapi<ProductListResult>("CastleBlack.ProductListPublic", { listQuery, filter, originCode });
}

export function ProductSkuAdd(sellerId: number, productId: number, data: ProductSku): Promise<ProductSku> {
	return webapi<ProductSku>("CastleBlack.ProductSkuAdd", { sellerId, productId, data });
}

export function ProductSkuAddMulti(sellerId: number, productId: number, data: ProductSku[]): Promise<ProductSku[]> {
	return webapi<ProductSku[]>("CastleBlack.ProductSkuAddMulti", { sellerId, productId, data });
}

export function ProductSkuRemove(sellerId: number, productId: number, skuId: string): Promise<boolean> {
	return webapi<boolean>("CastleBlack.ProductSkuRemove", { sellerId, productId, skuId });
}

export function ProductSkuUpdate(sellerId: number, productId: number, data: ProductSku): Promise<ProductSku> {
	return webapi<ProductSku>("CastleBlack.ProductSkuUpdate", { sellerId, productId, data });
}

export function ProductSkuUpdateMulti(sellerId: number, productId: number, data: ProductSku[]): Promise<ProductSku[]> {
	return webapi<ProductSku[]>("CastleBlack.ProductSkuUpdateMulti", { sellerId, productId, data });
}

export function ProductUpdate(sellerId: number, data: ProductBase, skus: ProductSku[]): Promise<ProductDetail> {
	return webapi<ProductDetail>("CastleBlack.ProductUpdate", { sellerId, data, skus });
}

export function SellerLogin(username: string, password: string): Promise<Seller> {
	return webapi<Seller>("CastleBlack.SellerLogin", { username, password });
}

export function SellerUpdatePassword(sellerId: number, oldpw: string, newpw: string): Promise<boolean> {
	return webapi<boolean>("CastleBlack.SellerUpdatePassword", { sellerId, oldpw, newpw });
}



export default {
	ImportTaskAdd,
	ImportTaskList,
	OrderClose,
	OrderDeliveryUpdate,
	OrderList,
	ProductAdd,
	ProductGet,
	ProductList,
	ProductListPublic,
	ProductSkuAdd,
	ProductSkuAddMulti,
	ProductSkuRemove,
	ProductSkuUpdate,
	ProductSkuUpdateMulti,
	ProductUpdate,
	SellerLogin,
	SellerUpdatePassword,
};

