/**
 * This file is auto-generated by tgen
 * Don't change manually
 */
import webapi from "./webapi";

export enum APIExceptionErrCode {
	AccountInvalidEmailOrUsername = 4,
	AccountInvalidPassword = 5,
	AccountInvalidPhoneOrUsername = 34,
	AccountInvalidResetToken = 6,
	AccountNotFound = 1,
	AccountOperationTooOften = 2,
	AccountUnauthorizedOperation = 3,
	AccountWrongPassword = 7,
	AdminInvalidShopApprovalForm = 11,
	AnnouncementNotEditable = 32,
	AnnouncementNotFound = 31,
	BadRequest = 28,
	BillNotFound = 21,
	CatagoryHasAnn = 38,
	CatagoryHasSub = 37,
	CategoryNotFound = 24,
	DuplicateTransferRequest = 23,
	ExportTaskNotFound = 33,
	ImportSubTaskNotFound = 13,
	ImportSubTaskProductCommitted = 16,
	ImportSubTaskProductNotFound = 15,
	ImportSubTaskUnCommitable = 14,
	IntervalTime = 36,
	InvalidImportFile = 20,
	InvalidOriginCode = 29,
	InvalidServiceFeeRate = 26,
	MaxLimit = 41,
	MirrorProductAlreadyLinked = 19,
	OrderItemNotFound = 18,
	OrderNotFound = 17,
	PackageNotFound = 30,
	ParsingPage = 39,
	PhoneNotUnique = 40,
	ProductNotFound = 12,
	ShopDuplicateApprovalRequest = 10,
	ShopInvalidApprovalForm = 8,
	ShopInvalidShopName = 9,
	ShopNotFound = 25,
	TransferNotFound = 22,
	Unknown = 0,
	VeriCodeIncorrect = 35
}
export enum ActionResultCode {
	Error = 1,
	Ok = 0
}
export enum Activity {
	CashOff = 2,
	FlashSale = 1,
	FreeShipping = 4,
	FriendsDeal = 3,
	MNCashOff = 5,
	MaxLimit = 6,
	Mixed = 200000,
	Unknown = 0
}
export enum AdminAnnouncementOp {
	Delete = 3,
	Publish = 2,
	Save = 1,
	Unknown = 0
}
export enum AdminAnnouncementOriginType {
	All = 1,
	Shop = 2,
	Unknown = 0
}
export enum AdminAnnouncementStatus {
	Deleted = 3,
	Published = 1,
	UnPublished = 2,
	Unknown = 0
}
export enum AdminMirrorProductOrderListSort {
	CreatedAtAsc = 1,
	CreatedAtDesc = 2,
	FinishedAtAsc = 3,
	FinishedAtDesc = 4,
	MaxLimit = 5,
	Unknown = 0
}
export enum AdminOpProductStatus {
	ForcedOffSale = 3,
	IsDeleted = 4,
	MaxLimit = 5,
	OffSale = 2,
	OnSale = 1,
	Unknown = 0
}
export enum AdminOpShopListSort {
	MaxLimit = 5,
	ShopIdAsc = 1,
	ShopIdDesc = 2,
	ShopNameAsc = 3,
	ShopNameDesc = 4,
	Unknown = 0
}
export enum BillOperationType {
	Appeal = 2,
	Approve = 1,
	MaxLimit = 4,
	OpAppealDispose = 3,
	Unknown = 0
}
export enum BillPeriod {
	Daily = 4,
	HalfMonth = 6,
	MaxLimit = 7,
	Monthly = 2,
	Never = 1,
	ShortTerm = 5,
	Unknown = 0,
	Weekly = 3
}
export enum BillRemarkType {
	Appealling = 3,
	Internal = 2,
	MaxLimit = 5,
	Normal = 1,
	Transfer = 4,
	Unknown = 0
}
export enum BillStatus {
	Appealled = 3,
	Approved = 2,
	Confirmed = 4,
	FinancePending = 5,
	MaxLimit = 6,
	Pending = 1,
	Unknown = 0
}
export enum ExportFileLanguage {
	CN = 1,
	EN = 2,
	MaxLimit = 3,
	Unknown = 0
}
export enum ExportFileTaskState {
	Done = 1,
	Duplicate = 3,
	Exec = 2,
	Unknown = 0
}
export enum ExportFileType {
	AdminOpOrderList = 6,
	AdminOpProductList = 5,
	ERPBillDetail = 2,
	MaxLimit = 12,
	OrderItems = 1,
	ShopExportSkus = 11,
	ShopOrderList = 7,
	ShopPickList = 8,
	Unknown = 0,
	UserBillOrderItems = 3,
	UserBillOrders = 4,
	UserUploadProducts = 10,
	WarehouseExportInformation = 9
}
export enum ExportTaskStatus {
	Cancelled = 6,
	Failed = 4,
	Paused = 5,
	Pending = 1,
	Processing = 2,
	Succeeded = 3,
	Unknown = 0
}
export enum ExportTaskType {
	AdminOpOrderList = 2,
	AdminOpProductList = 1,
	ErpBatchBill = 2001,
	ErpTransferCardInfo = 2002,
	ShopBillOrder = 1005,
	ShopBillOrderItem = 1004,
	ShopDispatchItemOrderGroupList = 1001,
	ShopOrderList = 1003,
	ShopPackingList = 1007,
	ShopProductAnalyticsReport = 1008
}
export enum ImportFileType {
	MaxLimit = 2,
	OrderDispatch = 1,
	Unknown = 0
}
export enum ImportSubTaskState {
	Committed = 5,
	Failed = 4,
	MaxLimit = 6,
	Pending = 1,
	Processing = 2,
	Succeeded = 3,
	Unknown = 0
}
export enum ImportTaskState {
	Finished = 3,
	MaxLimit = 4,
	Pending = 1,
	Processing = 2,
	Unknown = 0
}
export enum ImportTaskType {
	MaxLimit = 3,
	Product = 1,
	Shop = 2,
	Unknown = 0
}
export enum MessageType {
	MaxLimit = 2,
	Stockout = 1,
	Unknown = 0
}
export enum NewImportTaskType {
	ImportTaskTypeShopOrderDispatch = 1001,
	ImportTaskTypeUnknown = 0
}
export enum NotificationChannel {
	Email = 1,
	MaxLimit = 4,
	None = 0,
	Phone = 2
}
export enum NotificationType {
	MaxLimit = 2,
	None = 0,
	ShippingReminder = 1
}
export enum OpProductOperationLogType {
	ForcedOffSale = 1,
	ForcedOffSaleCancelled = 2,
	MaxLimit = 3,
	Unknown = 0
}
export enum OrderBillStatus {
	BillConfirmed = 3,
	Billable = 2,
	MaxLimit = 4,
	Pending = 1,
	Unknown = 0
}
export enum OrderDispatchImportError {
	EmptyTrackNum = 4,
	EmptyTrackProvider = 3,
	InvalidRowData = 1,
	MaxLimit = 7,
	MultipleTrackInfoForSingleOrder = 5,
	OrderNotFound = 6,
	OrderUnchangable = 2,
	Unknown = 0
}
export enum OrderItemRemarkSource {
	Customer = 100,
	EzSeller = 300,
	EzbuyOp = 200,
	Unknown = 0
}
export enum OrderItemSortBy {
	CancelDateDESC = 4,
	OrderDispatchTimeDESC = 3,
	PaymentTimeASC = 2,
	PaymentTimeDESC = 1,
	Unknown = 0
}
export enum OrderItemStatus {
	ArrivedWarehouse = 8,
	Cancelled = 3,
	Dispatched = 2,
	Finished = 6,
	MaxLimit = 9,
	Pending = 1,
	ReturnConfirmed = 5,
	Returned = 4,
	UnPaid = 7,
	Unknown = 0
}
export enum OrderItemTrackStatus {
	Cancelled = 1000001,
	Completed = 1021000,
	Dispatched = 1004000,
	OrderItemTrackStatusDelivered = 1009000,
	Pending = 1003000,
	PendingDelivery = 1016000,
	ReturnCompleted = 2011000,
	ReturnDispatched = 2002000,
	ReturnPending = 2001000,
	Unknown = 0,
	WarehouseReceived = 1006000
}
export enum OrderItemType {
	MaxLimit = 4,
	Normal = 1,
	ReOrdered = 3,
	Return = 2,
	Unknown = 0
}
export enum OrderOperation {
	Cancel = 3,
	Create = 1,
	Dispatch = 2,
	Finish = 6,
	MaxLimit = 7,
	Remark = 4,
	ReturnConfirm = 5,
	Unknown = 0
}
export enum OrderRemarkSource {
	Buyer = 1,
	Internal = 2,
	MaxLimit = 3,
	Unknown = 0
}
export enum OrderStatus {
	ArrivedWarehouse = 6,
	Cancelled = 2,
	Dispatched = 5,
	Finished = 3,
	MaxLimit = 7,
	Pending = 1,
	UnPaid = 4,
	Unknown = 0
}
export enum OrderWarehouse {
	American = 3,
	CNGuangZhou = 2,
	CNShangHai = 1,
	KRIncheon = 7,
	MYLocal = 6,
	MaxLimit = 8,
	SGLocal = 5,
	Taiwan = 4,
	Unknown = 0
}
export enum ProductChangeLogField {
	EnName = 2,
	IsDeleted = 8,
	MaxLimit = 13,
	Name = 1,
	PrimaryImage = 3,
	SellerSkuId = 10,
	ShipmentInfo = 12,
	SkuIds = 4,
	SkuOnSale = 6,
	SkuOriginalPrice = 9,
	SkuPrice = 5,
	SkuQuantity = 7,
	SkuWeight = 11,
	Unknown = 0
}
export enum ProductSellType {
	MaxLimit = 4,
	MirrorProduct = 2,
	MirrorProductBase = 3,
	Normal = 1,
	Unknown = 0
}
export enum ProductShipmentInfo {
	MaxLimit = 3,
	Normal = 1,
	Sensitive = 2,
	Unknown = 0
}
export enum ProductSource {
	Amwayed = 5,
	Imported = 2,
	MaxLimit = 6,
	Migrate = 3,
	Published = 1,
	Unknown = 0,
	Uploaded = 4
}
export enum Reason {
	EZSELLER_OPER_BAD_PRODUCT = 303,
	EZSELLER_OPER_CUSTOMER = 306,
	EZSELLER_OPER_MISSING = 302,
	EZSELLER_OPER_TIMEOUT = 301,
	EZSELLER_OPER_TRANSPORT_MISSING = 304,
	EZSELLER_OPER_TRANSPORT_OTHER = 305,
	UNKNOWN = 0
}
export enum Region {
	CN = 1,
	ID = 400000000,
	JP = 5,
	KR = 4,
	MY = 200000000,
	PK = 600000000,
	SG = 100000000,
	TH = 300000000,
	TW = 2,
	US = 3,
	Unknown = 0
}
export enum SellerPackageState {
	ArriveDestination = 6,
	Completed = 10,
	Delivered = 9,
	Delivering = 8,
	MaxLimit = 11,
	PendingDelivery = 7,
	ShopDelivered = 2,
	ShopPendingDelivery = 1,
	Unknown = 0,
	UserCancelled = 5,
	WarehouseReceived = 3,
	WarehouseShipped = 4
}
export enum SendBy {
	MaxLimit = 3,
	Unknown = 0,
	seller = 1,
	supporter = 2
}
export enum SesssionStatus {
	Closed = 2,
	MaxLimit = 3,
	Processing = 1,
	Unknown = 0
}
export enum ShopApprovalFormStatus {
	Applied = 1,
	Approved = 2,
	Denied = 3,
	MaxLimit = 4,
	Unknown = 0
}
export enum ShopApprovalFormType {
	MaxLimit = 4,
	Normal = 3,
	Organization = 2,
	Personal = 1,
	Unknown = 0
}
export enum ShopMailType {
	AdminOffSale = 3,
	BillApprove = 5,
	OrderCancel = 6,
	ProductOffSale = 2,
	SellerOffSale = 4,
	SellerSkuStock = 1,
	Unknown = 0
}
export enum ShopPackageFilterState {
	MaxLimit = 4,
	ShopDelivered = 2,
	ShopPendingDelivery = 1,
	Unknown = 0,
	UserCancelled = 3
}
export enum ShopRegisterStep {
	AppliedPening = 2,
	ApplyApproved = 3,
	ApplyDenied = 4,
	MaxLimit = 5,
	NewRegister = 1,
	Unknown = 0
}
export enum SortOption {
	ADDTOCARTCOUNT = 1001,
	CUSTOMERORDERAMOUNT = 1003,
	None = 0,
	TOTALORDERCCOUNT = 1002
}
export enum SortType {
	ASC = 1,
	DESC = 2,
	None = 0
}
export enum TransferAccountChangeField {
	AccountName = 5,
	AccountNumber = 2,
	AgencyAddress = 4,
	AgencyName = 3,
	BankName = 1,
	BankSwiftCode = 7,
	BeneficiaryBankAddress = 8,
	BeneficiaryName = 9,
	Phone = 6,
	Unknown = 0
}
export enum TransferAccountChangeOp {
	Apply = 1001,
	Approve = 2002,
	Cancel = 1003,
	Modify = 1002,
	OpUnknown = 2000,
	Reject = 2001,
	Unknown = 0,
	UserUnknown = 1000
}
export enum TransferAccountChangeStatus {
	Cancelled = 4,
	Normal = 1,
	Pending = 2,
	PendingSucceed = 6,
	Rejected = 3,
	Succeed = 5,
	Unknown = 0
}
export enum TransferStatus {
	Approved = 4,
	MaxLimit = 6,
	Pending = 1,
	Rejected = 2,
	Transferred = 3,
	Transferring = 5,
	Unknown = 0
}
export enum WarehousePackageFilterState {
	MaxLimit = 4,
	Unknown = 0,
	WaitingForReceiving = 1,
	WarehouseReceived = 2,
	WarehouseShipped = 3
}

export interface AccountBase {
	userId: number;
	username: string;
	token: string;
	shop?: ShopBase;
	isActivated: boolean;
}
export interface AccountForgetPasswordByPhoneResult {
	isPhoneExists: boolean;
	isCodeValid: boolean;
	token: string;
	usernames: string[];
}
export interface AccountForgetPasswordResult {
	email: string;
	isSent: boolean;
}
export interface AccountForgetPasswordUserNameResult {
	result: boolean;
	token: string;
}
export interface AccountNotification {
	notification: NotificationType;
	subscribed: boolean;
}
export interface AccountNotificationSetting {
	channelValue: string;
	notifications: AccountNotification[];
}
export interface ActionResult {
	code: ActionResultCode;
	message: string;
}
export interface AdminAnnouncementCata {
	pCata: AdminAnnouncementCataItem;
	sCatas: AdminAnnouncementCata[];
}
export interface AdminAnnouncementCataGetResult {
	pCata: AdminAnnouncementCataItem;
	sCata: AdminAnnouncementCataItem[];
}
export interface AdminAnnouncementCataItem {
	cId: number;
	cVal: string;
}
export interface AdminAnnouncementCataListResult {
	Catas: AdminAnnouncementCata[];
}
export interface AdminAnnouncementGetResult {
	title: string;
	content: string;
	catas: AdminAnnouncementCataItem[];
	originCodes: string[];
	fileKey: string;
}
export interface AdminAnnouncementListFilter {
	publishedAtFrom?: number;
	publishedAtTo?: number;
	title?: string;
	catagoryId?: number;
	published?: boolean;
}
export interface AdminAnnouncementListItem {
	publishedAt: number;
	createdAt: number;
	title: string;
	cataVal: string;
	originCodes: string[];
	announcementId: number;
	status: AdminAnnouncementStatus;
}
export interface AdminAnnouncementListResult {
	announcements: AdminAnnouncementListItem[];
	total: number;
}
export interface AdminAnnouncementLog {
	op: AdminAnnouncementOp;
	accountName: string;
	date: number;
}
export interface AdminAnnouncementLogResult {
	logs: AdminAnnouncementLog[];
	total: number;
}
export interface AdminAnnouncementShopItem {
	shopId: number;
	shopName: string;
	originCode: string;
}
export interface AdminAnnouncementShopListFilter {
	shopName: string;
}
export interface AdminAnnouncementShopListResult {
	shops: AdminAnnouncementShopItem[];
	total: number;
}
export interface AdminAnnouncementUpdateReq {
	title: string;
	content: string;
	catagoryId: number;
	OriginCodes: string[];
	fileKey: string;
	publish: boolean;
	announcementId?: number;
}
export interface AdminExportTaskListFilter {
	taskType?: ExportTaskType;
	id?: string;
}
export interface AdminExportTaskListResult {
	total: number;
	tasks: ExportTask[];
}
export interface AdminMirrorProductOrderListFilter {
	orderNum?: string;
	shopName?: string;
	status?: OrderStatus;
	warehouse?: OrderWarehouse;
}
export interface AdminOpAnnouncementDetail {
	announcementId: number;
	detail: AnnouncementDetail;
	published: boolean;
	createdAt: number;
	updatedAt: number;
	publishedAt: number;
}
export interface AdminOpAnnouncementListFilter {
	publishedAtFrom?: number;
	publishedAtTo?: number;
	title?: string;
	published?: boolean;
}
export interface AdminOpAnnouncementListResult {
	total: number;
	results: AdminOpAnnouncementSimple[];
}
export interface AdminOpAnnouncementSimple {
	announcementId: number;
	title: string;
	published: boolean;
	publishedAt: number;
	updatedAt: number;
}
export interface AdminOpJdBalanceResult {
	result: string;
}
export interface AdminOpOrderItemSimple {
	orderItemId: number;
	skuName: string;
	skuId: number;
	quantity: number;
	unitPrice: number;
	status: OrderItemStatus;
	type: OrderItemType;
	unitOriginalPrice: number;
	unitDiscount: number;
	unitCashOff: number;
	activity: Activity;
	originCode: string;
	totalCashOff: number;
}
export interface AdminOpOrderItemSimpleNew {
	orderNum: string;
	orderItemId: string;
	shopName: string;
	productId: number;
	productName: string;
	skuName: string;
	status: OrderItemTrackStatus;
	totalAmount: number;
	createdAt: number;
	finishedAt: number;
	dispatchedAt: number;
	arrivedAt: number;
	expectedDispatchAt: number;
	dispatchDelayed: boolean;
	newOrderNum: string;
	unitAmount: number;
	qty: number;
	region: Region;
	stockInQty: number;
}
export interface AdminOpOrderListFilter {
	shopId?: number;
	shopName?: string;
	createdAtFrom?: number;
	createdAtTo?: number;
	finishedAtFrom?: number;
	finishedAtTo?: number;
	packageState?: SellerPackageState;
	productId?: number;
	productUrl?: string;
	dispatchDelayedOnly?: boolean;
	lang?: ExportFileLanguage;
	OriginCode?: string;
	paidAtFrom?: number;
	paidAtTo?: number;
}
export interface AdminOpOrderListFilterNew {
	shopId?: number;
	shopName?: string;
	createdAtFrom?: number;
	createdAtTo?: number;
	finishedAtFrom?: number;
	finishedAtTo?: number;
	orderItemTrackStatus?: OrderItemTrackStatus;
	productId?: number;
	productUrl?: string;
	dispatchDelayedOnly?: boolean;
	lang?: ExportFileLanguage;
	prodRegion?: Region;
	orderNum?: string;
}
export interface AdminOpOrderListResult {
	orders: AdminOpOrderSimple[];
	count: number;
}
export interface AdminOpOrderListResultNew {
	orderItems: AdminOpOrderItemSimpleNew[];
	count: number;
}
export interface AdminOpOrderSimple {
	orderNum: string;
	orderId: number;
	shopId: number;
	shopName: string;
	productId: number;
	productUrl: string;
	productName: string;
	status: OrderStatus;
	shippingFee: number;
	totalAmount: number;
	items: AdminOpOrderItemSimple[];
	remarks: OrderRemark[];
	warehouse: OrderWarehouse;
	sellType: ProductSellType;
	createdAt: number;
	finishedAt: number;
	dispatchedAt: number;
	arrivedAt: number;
	primaryImage: string;
	track: OrderTrack;
	expectedDispatchAt: number;
	dispatchDelayed: boolean;
	packageState: SellerPackageState;
	paidAt: number;
	paidAmount: number;
}
export interface AdminOpProductChangeLogListFilter {
	fields?: ProductChangeLogField[];
}
export interface AdminOpProductChangeLogListResult {
	changeLogs: ProductChangeLog[];
	total: number;
}
export interface AdminOpProductListFilter {
	shopId?: number;
	shopName?: string;
	productName?: string;
	productUrl?: string;
	status?: AdminOpProductStatus;
	minPrice?: number;
	maxPrice?: number;
	productSource?: ProductSource;
	isStocked?: boolean;
	lang?: ExportFileLanguage;
	originCode?: string;
	createdAtFrom?: number;
	createdAtTo?: number;
}
export interface AdminOpProductListResult {
	products: AdminOpProductSimple[];
	count: number;
}
export interface AdminOpProductOperationLogListFilter {
	type?: OpProductOperationLogType;
}
export interface AdminOpProductOperationLogListResult {
	operationLogs: OpProductOperationLog[];
	total: number;
}
export interface AdminOpProductSimple {
	productId: number;
	productUrl: string;
	productName: string;
	primaryImage: string;
	price: string;
	status: AdminOpProductStatus;
	shopName: string;
	originCode: string;
	isStocked: boolean;
	isDeleted: boolean;
	categoryId: number;
	aliCid: number;
	categoryLeaf?: string;
	weight: string;
	originalPrice: string;
	soldCount: number;
	CreateDate: string;
	shipmentInfo: ProductShipmentInfo;
}
export interface AdminOpRemarkListResult {
	remarks: OrderItemRemark[];
}
export interface AdminOpServiceFeeRateHistory {
	username: string;
	opTime: number;
	category?: string;
	shop?: { [key: string]: number[] };
	exRate?: number;
	curRate?: number;
}
export interface AdminOpServiceFeeRateHistoryResp {
	total: number;
	offset: number;
	limit: number;
	result?: AdminOpServiceFeeRateHistory[];
}
export interface AdminOpServiceFeeRateItem {
	rate: number;
	inherited: boolean;
	inheritedCategoryName?: string;
	inheritedCategoryId?: number;
}
export interface AdminOpServiceFeeRateSettings {
	common: AdminOpServiceFeeRateItem;
	shops?: AdminOpServiceFeeRateShopSetting[];
}
export interface AdminOpServiceFeeRateShopSetting {
	shopId: number;
	shopName: string;
	rateItem: AdminOpServiceFeeRateItem;
}
export interface AdminOpServiceFeeRateShopUpdateItem {
	shopId: number;
	exRate: number;
	curRate: number;
}
export interface AdminOpShopListFilter {
	shopName?: string;
	isShutDown?: boolean;
	isApproved?: boolean;
	isDisabled?: boolean;
	originCode?: string;
}
export interface AdminOpShopListResult {
	total: number;
	shops: AdminOpShopSimple[];
}
export interface AdminOpShopSimple {
	shopName: string;
	shopId: number;
	disabled: boolean;
	originCode: string;
	isApproved: boolean;
	isShutDown: boolean;
}
export interface AdminShopApprovalDetail {
	formId: string;
	email: string;
	username: string;
	shopName: string;
	type: ShopApprovalFormType;
	personalForm?: ShopApprovalFormPersonal;
	orgForm?: ShopApprovalFormOrganization;
	status: ShopApprovalFormStatus;
	requester: ShopApprovalRequesterInfo;
	shopId: number;
	originCode: string;
	warehouseAddress: string;
}
export interface AdminShopApprovalFormListItem {
	formId: string;
	email: string;
	username: string;
	shopName: string;
	type: ShopApprovalFormType;
	createdAt: number;
	status: ShopApprovalFormStatus;
	shopId: number;
	originCode: string;
	account: string;
	mainCats: string;
	qqNumber: string;
}
export interface AdminShopApprovalFormListResult {
	total: number;
	list: AdminShopApprovalFormListItem[];
}
export interface AdminShopApprovalListFilter {
	status?: ShopApprovalFormStatus;
	type?: ShopApprovalFormType;
	shopName?: string;
	originCode?: string;
	mainCat?: string;
	qqNumber?: string;
	createdFrom?: number;
	createdTo?: number;
}
export interface AdminShopApprovalOplog {
	status: number;
	time: number;
	operator: string;
	remark: string;
}
export interface AdminTransferAccountChangeInfoResult {
	transferAccount: TransferAccountInfo;
	changeTransferAccount: TransferAccountInfo;
	ShopType: ShopApprovalFormType;
}
export interface AdminTransferAccountChangeListFilter {
	shopName: string;
	region: Region;
	status: TransferAccountChangeStatus;
	userName: string;
	deal: boolean;
}
export interface AdminTransferAccountChangeListResult {
	results: AdminTransferAccountChangeListResultItem[];
	total: number;
}
export interface AdminTransferAccountChangeListResultItem {
	userName: string;
	shopName: string;
	region: Region;
	createdAt: number;
	status: TransferAccountChangeStatus;
	id: string;
	updatedAt: number;
}
export interface AdminTransferAccountChangeLogEntry {
	field: TransferAccountChangeField;
	valBefore: string;
	valAfter: string;
}
export interface AdminTransferAccountChangeLogItem {
	date: number;
	userName: string;
	op: TransferAccountChangeOp;
	entries: AdminTransferAccountChangeLogEntry[];
	remark: string;
}
export interface AdminTransferAccountChangeLogResult {
	results: AdminTransferAccountChangeLogItem[];
	total: number;
}
export interface AnnouncementDetail {
	title: string;
	content: string;
}
export interface BaseInfo {
	orderNum: string;
	msgType: MessageType;
}
export interface BillOperationHistory {
	type: BillOperationType;
	createdAt: number;
	createdBy: string;
	amount: number;
	remark: string;
}
export interface BillRemark {
	type: BillRemarkType;
	createdBy: string;
	createdAt: number;
	text: string;
}
export interface Chatlog {
	from: string;
	createBy: string;
	content: string;
	ctime: number;
}
export interface ChatlogResp {
	snapshoot: Chatlog[];
}
export interface CompletedSession {
	shopName: string;
	msgType: MessageType;
	orderNum: string;
}
export interface Contact {
	name: string;
	phone: string;
}
export interface ERPBillApproveItem {
	billNum: string;
	amount: number;
	remark: string;
}
export interface ERPBillDetailFilter {
	withOffset?: boolean;
}
export interface ERPBillDetailResult {
	orders: ERPBillOrder[];
	shopName: string;
}
export interface ERPBillDisposeItem {
	billNum: string;
	suggestedAmount: number;
	remark?: string;
}
export interface ERPBillListFilter {
	billNum?: string;
	shopName?: string;
	approved?: boolean;
	periodType?: BillPeriod;
	originCode?: string;
	status?: BillStatus;
	marked?: boolean;
}
export interface ERPBillListResult {
	bills: ERPBillSimple[];
	total: number;
}
export interface ERPBillOrder {
	orderNum: string;
	catalogCode: string;
	warehouse: OrderWarehouse;
	createdAt: number;
	arrivedAt: number;
	finishedAt: number;
	unitQuantity: number;
	unitAmount: number;
	offsetAmount: number;
	unitAmountWithOffset: number;
	shippingFee: number;
	totalAmount: number;
	totalAmountWithOffset: number;
	serviceFee: number;
	finalAmount: number;
	unitQuantityWithOffset: number;
	packageNum: string;
	serviceFeeRate: number;
	arriveDestAt: number;
	localDeliveryFee: number;
}
export interface ERPBillSimple {
	billNum: string;
	shopName: string;
	createdAt: number;
	finalAmount: number;
	approvedAmount: number;
	remarks: BillRemark[];
	status: BillStatus;
	opHistory?: BillOperationHistory[];
	appeallingAmount: number;
	periodType: BillPeriod;
	originCode: string;
	marked: boolean;
}
export interface ERPExportTaskListFilter {
	taskType?: ExportTaskType;
	id?: string;
	createdAtFrom?: number;
	createdAtTo?: number;
}
export interface ERPExportTaskListResult {
	total: number;
	tasks: ExportTask[];
}
export interface ERPShop {
	shopId: number;
	shopName: string;
}
export interface ERPShopSearchListReq {
	shopName: string;
}
export interface ERPShopSearchListResp {
	shops: ERPShop[];
}
export interface ERPTransferDoneItem {
	billNum: string;
	transferInfo: TransferInfo;
	remark: string;
}
export interface ERPTransferFilter {
	status?: TransferStatus;
	shopName?: string;
	bankName?: string;
	billNum?: string;
	approved?: boolean;
	approvedByMe?: boolean;
	accountName?: string;
	marked?: boolean;
	originCode?: string;
}
export interface ERPTransferListResult {
	transfers: Transfer[];
	total: number;
}
export interface ExportFile {
	fileUrl: string;
	type: ExportFileType;
}
export interface ExportFileSubmitResult {
	errMessage?: string;
	state?: ExportFileTaskState;
	file?: string;
}
export interface ExportTask {
	id: string;
	taskType: ExportTaskType;
	status: ExportTaskStatus;
	createdAt: number;
	createBy: string;
	fileUrl: string;
	err: string;
}
export interface ExportTaskResult {
	id: string;
	isAlreadyExists: boolean;
	taskType: ExportTaskType;
}
export interface ImportSubTask {
	subTaskId: string;
	productUrl: string;
	productName: string;
	state: ImportSubTaskState;
}
export interface ImportTask {
	taskId: string;
	type: ImportTaskType;
	url: string;
	name: string;
	state: ImportTaskState;
	remark: string;
	totalCount: number;
	fetchedCount: number;
	failedCount: number;
	createdAt: number;
	updatedAt: number;
	subTaskIdForQuickView?: string;
}
export interface ImportTaskItemError {
	global: string;
	lines: ImportTaskItemLineError[];
}
export interface ImportTaskItemLineError {
	num: number;
	object: string;
	message: string;
}
export interface ImportTaskListResult {
	total: number;
	offset: number;
	data: ImportTask[];
}
export interface ImportTaskResult {
	id: string;
	isAlreadyExists: boolean;
	taskType: NewImportTaskType;
}
export interface ImportTaskRetry {
	id: string;
}
export interface Invoice {
	username: string;
	packageNumber: string;
	boxCnt: number;
	pkgCnt: number;
	subPkgNumbers: InvoiceSubPkgNumber[];
	warehouse: InvoiceWarehouse;
	sender: InvoiceSender;
	receiver: InvoiceConsignee;
	items: InvoiceItem[];
	total: number;
	localDeliveryMethod: string;
	orderItems: OrderItem[];
	deliveryStationCode: string;
}
export interface InvoiceConsignee {
	username: string;
	mobile: string;
	ZIPCode: string;
	address: string;
}
export interface InvoiceItem {
	description: string;
	qty: number;
	unitType: string;
	unitPrice: number;
	total: number;
	itemPaidAmount: number;
}
export interface InvoiceSender {
	username: string;
	mobile: string;
	ZIPCode: string;
	address: string;
	provider: string;
}
export interface InvoiceSubPkgNumber {
	subPkgNumber: string;
	hblNumber: string;
}
export interface InvoiceWarehouse {
	name: string;
	originCountry: string;
	destination: string;
	exportDate: string;
}
export interface LoginFieldCheckResult {
	exists: boolean;
	inValid: boolean;
}
export interface MessageResult {
	result: { [key: string]: boolean };
}
export interface MirrorProductCandidate {
	productName: string;
	productUrl: string;
	categoryId: number;
	categoryName: number;
}
export interface MirrorProductCandidateListEzBuyCategoryFilter {
	categoryId: number;
}
export interface MirrorProductCandidateListFilter {
	aliProductUrlFilter?: MirrorProductCandidateListUrlFilter;
	aliPageUrlFilter?: MirrorProductCandidateListUrlFilter;
	categoryFilter?: MirrorProductCandidateListEzBuyCategoryFilter;
}
export interface MirrorProductCandidateListUrlFilter {
	url: string;
}
export interface MirrorProductDetail {
	base: ProductBase;
	skus: MirrorProductSku[];
}
export interface MirrorProductOrder {
	orderNum: string;
	shopName: string;
	shopId: number;
	status: OrderStatus;
	shippingFee: number;
	totalAmount: number;
	items: OrderItemSimple[];
	remarks: OrderRemark[];
	warehouse: OrderWarehouse;
	createdAt: number;
	finishedAt: number;
	track: OrderTrack;
	productName: string;
	primaryImage: string;
}
export interface MirrorProductProvider {
	productId: number;
	shopId: number;
	shopName: string;
	productUrl: string;
	isOnSale: boolean;
	skus: MirrorProductProviderSku[];
}
export interface MirrorProductProviderSku {
	skuId: number;
	name: string;
	isOnSale: boolean;
	price: number;
	weight: number;
	quantity: number;
	shippingFee: number;
}
export interface MirrorProductSimple {
	pid: number;
	categoryId: number;
	name: string;
	primaryImage: string;
	isOnSale: boolean;
	url: string;
	price: number;
	originCode: string;
	sellType: ProductSellType;
}
export interface MirrorProductSku {
	skuId: number;
	name: string;
	skuImage?: string;
	images?: string[];
	isOnSale: boolean;
	attributes: { [key: string]: string };
	price: number;
	originalPrice?: number;
	sellingPrice: number;
	weight: number;
	quantity: number;
	shippingFee: number;
}
export interface MsgInstance {
	content: string;
	info: BaseInfo;
}
export interface NewImportTask {
	id: string;
	taskType: NewImportTaskType;
	status: ExportTaskStatus;
	createdAt: number;
	createBy: string;
	fileUrl: string;
	error?: ImportTaskItemError;
}
export interface NewOrder {
	productImg: string;
	orderId: string;
	orderNum: string;
	productId: string;
	sellerSkuId: string;
	productName: string;
	skuName: string;
	activity: Activity[];
	unitPrice: number;
	quantity: number;
	warehouse: OrderWarehouse;
	orderStatus: OrderItemTrackStatus;
	expectedDispatchAt: number;
	userRemark: OrderItemRemark[];
	sellerRemark: OrderItemRemark[];
	orderGroupNum: string;
	createdAt: number;
	billDate: number;
	cusRegion: Region;
	paidAmount: number;
	stockInQty: number;
	reason: Reason;
	trackTime: number;
	ticketId: number;
	cancelDate: number;
}
export interface NewOrderListResult {
	orderCount: { [key: string]: number };
	data: NewOrder[];
}
export interface OpProductOperationLog {
	type: OpProductOperationLogType;
	text: string;
	operator: string;
	createdAt: number;
}
export interface Order {
	orderNum: string;
	productName: string;
	status: OrderStatus;
	shippingFee: number;
	totalAmount: number;
	items: OrderItemSimple[];
	remarks: OrderRemark[];
	warehouse: OrderWarehouse;
	sellType: ProductSellType;
	createdAt: number;
	finishedAt: number;
	track: OrderTrack;
	primaryImage: string;
	dispatchDelayed: boolean;
	expectedDispatchAt: number;
	productUrl: string;
	packageState: SellerPackageState;
	paidAmount: number;
}
export interface OrderDetail {
	order: Order;
	history: OrderHistory[];
}
export interface OrderDispatchImportResult {
	orderNum: string;
	rowNum: number;
	error: OrderDispatchImportError;
}
export interface OrderHistory {
	operation: OrderOperation;
	operator: string;
	createdAt: number;
	text?: string;
}
export interface OrderInfo {
	sellerSkuId: string;
	skuName: string;
	unitPrice: number;
	quantity: number;
	warehouse: OrderWarehouse;
}
export interface OrderItem {
	orderItemId: number;
	productName: string;
	orderNum: string;
	skuName: string;
	quantity: number;
	unitPrice: number;
	totalAmount: number;
	attrs: string[];
	status: OrderItemStatus;
	type: OrderItemType;
	track?: OrderTrack;
	sellType: ProductSellType;
	unitOriginalPrice: number;
	unitDiscount: number;
	unitCashOff: number;
	sellerSkuId: string;
}
export interface OrderItemGroup {
	orderNum: string;
	sellType: ProductSellType;
	productName: string;
	items: OrderItem[];
	remarks: OrderRemark[];
	warehouse: OrderWarehouse;
	status: OrderStatus;
	track: OrderTrack;
	primaryImage: string;
	createdAt: number;
	paidAt: number;
	dispatchDelayed: boolean;
	expectedDispatchAt: number;
	productUrl: string;
}
export interface OrderItemGroupListResult {
	total: number;
	offset: number;
	data: OrderItemGroup[];
}
export interface OrderItemRemark {
	remark: string;
	createdAt: number;
	userName: string;
	source: OrderItemRemarkSource;
}
export interface OrderItemSimple {
	orderItemId: number;
	skuName: string;
	quantity: number;
	unitPrice: number;
	totalAmount: number;
	status: OrderItemStatus;
	type: OrderItemType;
	track?: OrderTrack;
	unitOriginalPrice: number;
	unitDiscount: number;
	unitCashOff: number;
	sellerSkuId: string;
	totalCashOff: number;
	itemPaidAmount: number;
}
export interface OrderListResult {
	total: number;
	offset: number;
	data: Order[];
}
export interface OrderRemark {
	text: string;
	source: OrderRemarkSource;
	createdBy: string;
	createdAt: number;
}
export interface OrderTrack {
	provider: string;
	trackingNum: string;
	trackId: number;
}
export interface OrderTrackDetail {
	provider: string;
	trackingNum: string;
	itemCount: number;
	createdAt: number;
	updatedAt: number;
}
export interface OrderTrackDetailListFilter {
	provider?: string;
	trackingNum?: string;
}
export interface Package {
	pkgId: number;
	pkgNumber: string;
	createdAt: number;
	expiredAt: number;
	dispatchedAt: number;
	state: string;
	orderItems: PackageOrderItem[];
	isStocked: boolean;
	trackInfo?: PackageTrackInfo;
}
export interface PackageListResult {
	total: number;
	data: Package[];
}
export interface PackageOrderItem {
	productName: string;
	skuId: number;
	skuName: string;
	img: string;
	unitPrice: number;
	quantity: number;
	state: OrderItemStatus;
	remarks: OrderRemark[];
	sellerSkuId: string;
	productUrl: string;
	orderNumber: string;
	itemPaidAmount: number;
	newOrderNum: string;
}
export interface PackageTrackInfo {
	provider: string;
	trackingNumber: string;
}
export interface PickListItem {
	packageNumber: string;
	skuId: number;
	productName: string;
	skuInfo: string;
	quantity: number;
	sellerSkuId: string;
}
export interface ProductBase {
	pid: number;
	categoryId: number;
	name: string;
	description?: string;
	primaryImage: string;
	images?: string[];
	isOnSale: boolean;
	originCode: string;
	shipmentInfo: ProductShipmentInfo;
	attributes: { [key: string]: string };
	sellType: ProductSellType;
	url: string;
	skuProps: SkuProp[];
	enName: string;
	isStocked: boolean;
	forceOffSale: boolean;
	committed: boolean;
	source: ProductSource;
}
export interface ProductChangeLog {
	productId: number;
	createdBy: string;
	createdAt: number;
	entries: ProductChangeLogEntry[];
}
export interface ProductChangeLogEntry {
	field: ProductChangeLogField;
	skuId?: number;
	valBefore: string;
	valAfter: string;
}
export interface ProductDetail {
	base: ProductBase;
	skus: ProductSku[];
}
export interface ProductItem {
	productImg: string;
	productName: string;
	productId: number;
	vendorOrderAmount: number;
	orderTotalCount: number;
	addToCartCount: number;
	date: number;
}
export interface ProductSimple {
	pid: number;
	categoryId: number;
	name: string;
	primaryImage: string;
	isOnSale: boolean;
	url: string;
	price: number;
	originCode: string;
	sellType: ProductSellType;
	forcedOffSale?: boolean;
	opLogs?: OpProductOperationLog[];
	soldCount: number;
	isStocked: boolean;
	shipment: ProductShipmentInfo;
}
export interface ProductSimpleInfo {
	productName: string;
	productId: number;
}
export interface ProductSku {
	skuId: number;
	name: string;
	skuImage?: string;
	images?: string[];
	isOnSale: boolean;
	attributes: { [key: string]: string };
	price: number;
	originalPrice?: number;
	weight: number;
	quantity: number;
	shippingFee: number;
	volume: ProductSkuVolume;
	sellerSkuId: string;
}
export interface ProductSkuPrice {
	productId: number;
	skuPrices: SkuPrice[];
}
export interface ProductSkuVolume {
	length: number;
	width: number;
	height: number;
}
export interface ProductsFromSourceResult {
	total: number;
	results: ProductBase[];
}
export interface SellerFeedback {
	orderId: number;
	orderNum: string;
	warehouse: OrderWarehouse;
	shopName: string;
	msgType: MessageType;
	Closed: number;
	lastReplyTime: number;
	lastReplyItem: string;
	lastEzbuySender: string;
	newEzOrderId: string;
	newEzOrderItemId: string;
}
export interface SellerFeedbackFilter {
	warehouse?: OrderWarehouse;
	msgType?: MessageType;
	shopName?: string;
	stime?: number;
	etime?: number;
	Closed?: SesssionStatus;
	orderNum?: string;
	region?: Region;
}
export interface SellerFeedbackResp {
	result: SellerFeedback[];
	total: number;
}
export interface SellerInfo {
	storeName: string;
	storeUrl: string;
	contactPerson: string;
	contactPhone: string;
	originCode: string;
	warehouseAddress: string;
}
export interface SessionFilter {
	orderNums: string[];
	sender: SendBy;
	msgType: MessageType;
}
export interface ShipmentType {
	id: number;
	code: string;
	name: string;
	enName: string;
}
export interface Shipper {
	shipperId: number;
	name: string;
}
export interface ShopApprovalFormAddress {
	areasCode: string[];
	areasVal: string[];
	address: string;
}
export interface ShopApprovalFormBankInfo {
	bankName: string;
	agencyAddress: string;
	agencyName: string;
	accountNumber: string;
	beneficiaryName: string;
	swiftCode: string;
	companyRegistrationNumber: string;
	accountName: string;
}
export interface ShopApprovalFormGetResult {
	appliedShopName: string;
	registerPhone: string;
	type: ShopApprovalFormType;
	status: ShopApprovalFormStatus;
	requester: ShopApprovalRequesterInfo;
	personalForm?: ShopApprovalFormPersonal;
	orgForm?: ShopApprovalFormOrganization;
	refuseMark?: string;
}
export interface ShopApprovalFormIDImage {
	front: string;
	opposite: string;
	handHeld: string;
}
export interface ShopApprovalFormOrgCredentials {
	combined: boolean;
	combinedBusinessLicense?: string;
	businessLicense?: string;
	orgCodeCrt?: string;
	taxRegistrationCrt?: string;
	bankAccountCrt: string;
}
export interface ShopApprovalFormOrgInfo {
	orgName: string;
	approvalImages: string[];
	legalRepresentativeName: string;
	bizRegistrationNumber: string;
	approvalCrts?: ShopApprovalFormOrgCredentials;
}
export interface ShopApprovalFormOrganization {
	responsibleInfo: ShopApprovalFormResponsibleInfo;
	contacts: Contact[];
	orgInfo: ShopApprovalFormOrgInfo;
	bankInfo: ShopApprovalFormBankInfo;
	surveyInfo: ShopApprovalFormShopSurvey;
}
export interface ShopApprovalFormPersonal {
	responsibleInfo: ShopApprovalFormResponsibleInfo;
	bankInfo: ShopApprovalFormBankInfo;
	surveyInfo: ShopApprovalFormShopSurvey;
}
export interface ShopApprovalFormResponsibleInfo {
	realName: string;
	identifierNum: string;
	approvalImages: string[];
	idImages?: ShopApprovalFormIDImage;
}
export interface ShopApprovalFormShopSurvey {
	mainCat: string;
	stockChan: string;
	warehouseAddr: ShopApprovalFormAddress;
	prodCount: string;
	awareChan: string;
	srcPlat?: ShopApprovalFormSrcPlat;
	samplePics?: string[];
}
export interface ShopApprovalFormSrcPlat {
	platform: string[];
	shopUrl: string;
}
export interface ShopApprovalRequesterInfo {
	realName: string;
	identifierNum: string;
	phone: string;
	aliShopUrl?: string;
	email?: string;
	qqNumber?: string;
}
export interface ShopBase {
	shopId: number;
	shopName: string;
	shopSlug: string;
	isApproved: boolean;
	approvalProcessing: boolean;
	originCode: string;
	isShutDown: boolean;
	firstSignin: boolean;
	step: ShopRegisterStep;
}
export interface ShopPackageListFilter {
	pkgState?: SellerPackageState;
	pkgNumber?: string;
	state?: ShopPackageFilterState;
	isStocked?: boolean;
	pkgCreateDateStart?: number;
	pkgCreateDateEnd?: number;
	pkgShopDispatchDateStart?: number;
	pkgShopDispatchDateEnd?: number;
	orderNumber?: string;
}
export interface SkuPrice {
	skuId: number;
	price: number;
	taobaoPrice?: number;
}
export interface SkuProp {
	propId: number;
	propName: string;
	values: SkuValue[];
}
export interface SkuValue {
	valueId: number;
	valueName: string;
	image?: string;
}
export interface Transfer {
	billNum: string;
	status: TransferStatus;
	createdAt: number;
	amount: number;
	account: TransferAccountInfo;
	shopName: string;
	transferInfo: TransferInfo;
	transferredBy: string;
	remarks: BillRemark[];
	approvedAt?: number;
	approvedBy?: string;
	marked: boolean;
	originCode: string;
}
export interface TransferAccountInfo {
	bankName: string;
	agencyName: string;
	agencyAddress: string;
	accountNumber: string;
	accountName: string;
	phone: string;
	beneficiaryName: string;
	beneficiaryBankAddress: string;
	bankSwiftCode: string;
}
export interface TransferInfo {
	trackingNum: string;
	amount: number;
	fee: number;
}
export interface UserAnnAndMailCountResult {
	announcementCount: number;
	mailCount: number;
}
export interface UserAnnouncementDetail {
	announcementId: number;
	detail: AnnouncementDetail;
	viewed: boolean;
	publishedAt: number;
}
export interface UserAnnouncementGetResult {
	announcementId: number;
	cataVal: string;
	title: string;
	content: string;
	publishedAt: number;
}
export interface UserAnnouncementListFilter {
	catagoryId?: number;
	title?: string;
	publishedAtFrom?: number;
	publishedAtTo?: number;
}
export interface UserAnnouncementListItem {
	announcementId: number;
	title: string;
	cataVal: string;
	readStatus: boolean;
	publishedAt: number;
}
export interface UserAnnouncementListResult {
	lists: UserAnnouncementListItem[];
	total: number;
}
export interface UserAnnouncementReadReq {
	announcementId?: number;
	allMark?: boolean;
}
export interface UserAnnouncementSimple {
	announcementId: number;
	title: string;
	viewed: boolean;
	publishedAt: number;
}
export interface UserBillListFilter {
	periodType?: BillPeriod;
}
export interface UserBillListResult {
	total: number;
	offset: number;
	data: UserBillSimple[];
}
export interface UserBillOrder {
	orderNum: string;
	totalAmount: number;
	offsetAmount: number;
	totalAmountWithOffset: number;
	createdAt: number;
	finishedAt: number;
	warehouse: OrderWarehouse;
	track: OrderTrack;
	shippingFee: number;
	serviceFee: number;
	finalAmount: number;
	packageNum: string;
	localDeliveryFee: number;
}
export interface UserBillOrderItem {
	orderNum: string;
	productName: string;
	skuName: string;
	quantity: number;
	unitPrice: number;
	unitDiscount: number;
	unitCashOff: number;
	unitOriginalPrice: number;
	totalAmount: number;
	serviceFee: number;
	finalAmount: number;
	packageNum: string;
	totalCashOff: number;
	localDeliveryFee: number;
}
export interface UserBillOrderItemResult {
	items: UserBillOrderItem[];
}
export interface UserBillOrderResult {
	orders: UserBillOrder[];
}
export interface UserBillSimple {
	billNum: string;
	rangeStart: number;
	rangeEnd: number;
	orderTotalAmount: number;
	orderQuantity: number;
	finalAmount: number;
	approvedAmount: number;
	status: BillStatus;
	remarks: BillRemark[];
	appealable: boolean;
	transferable: boolean;
	appeallingAmount: number;
	transferStatus?: TransferStatus;
	periodType: BillPeriod;
	localDeliveryFee: number;
	createdAt: number;
}
export interface UserDailyReport {
	summary: UserDailyReportItem;
	details: UserDailyReportItem[];
}
export interface UserDailyReportDate {
	year: number;
	month: number;
	day: number;
}
export interface UserDailyReportFilter {
	rangeStart: number;
	rangeEnd: number;
}
export interface UserDailyReportItem {
	date?: UserDailyReportDate;
	paidCount: number;
	paidAmount: number;
	canceledCount: number;
	canceledAmount: number;
	billableCount: number;
	billableAmount: number;
}
export interface UserExportTaskListFilter {
	taskType?: ExportTaskType;
	id?: string;
	createdAtFrom?: number;
	createdAtTo?: number;
}
export interface UserExportTaskListResult {
	total: number;
	tasks: ExportTask[];
}
export interface UserEzChoiseProductListFilter {
	isOnSale?: boolean;
	productName?: string;
}
export interface UserGetProductAnalyticsFilter {
	rangeStart: number;
	rangeEnd: number;
	productId: number;
}
export interface UserGetProductAnalyticsItem {
	date?: UserDailyReportDate;
	AddToCartCount: number;
	FavouriteCount: number;
	SalesAmount: number;
	TotalOrderCount: number;
	CashoffCount: number;
	FlashSalesCount: number;
	FreeShippingCount: number;
	FriendsDealCount: number;
	OtherOrdersCount: number;
}
export interface UserGetProductAnalyticsResult {
	items: UserGetProductAnalyticsItem[];
}
export interface UserImportSubTaskListFilter {
	succeeded?: boolean;
}
export interface UserImportSubTaskListResult {
	total: number;
	list: ImportSubTask[];
}
export interface UserImportTaskListFilter {
	taskType?: NewImportTaskType;
	id?: string;
	createdAtFrom?: number;
	createdAtTo?: number;
}
export interface UserImportTaskListResult {
	total: number;
	tasks: NewImportTask[];
}
export interface UserImportTaskRetryResult {
	id: string;
}
export interface UserMirrorProductListFilter {
	categoryId?: number;
	productName?: string;
	linked?: boolean;
}
export interface UserMirrorProductListResult {
	total: number;
	list: UserMirrorProductSimple[];
}
export interface UserMirrorProductSimple {
	pid: number;
	categoryId: number;
	name: string;
	primaryImage: string;
	isOnSale: boolean;
	url: string;
	price: number;
	originCode: string;
	sellType: ProductSellType;
	isLinked: boolean;
	lastPushedAt: number;
	linkProductId: number;
}
export interface UserOrderItemListFilter {
	warehouse?: OrderWarehouse;
	status?: OrderItemStatus;
	sellType?: ProductSellType;
	itemType?: OrderItemType;
	trackingProvider?: string;
	trackingNum?: string;
	orderNum?: string;
	productId?: number;
}
export interface UserOrderListFilter {
	warehouse?: OrderWarehouse;
	packageState?: SellerPackageState;
	sellType?: ProductSellType;
	orderNum?: string;
	productId?: number;
	productUrl?: string;
	minCreateDate?: number;
	maxCreateDate?: number;
	billStatus?: OrderBillStatus;
}
export interface UserOrderListNewFilter {
	orderNum?: string;
	paymentTimeStart?: number;
	paymentTimeEnd?: number;
	warehouse?: OrderWarehouse;
	productName?: string;
	productUrl?: string;
	sellerSkuId?: string;
	deliveryTimeStart?: number;
	deliveryTimeEnd?: number;
	trackingNum?: string;
	orderItemTrackStatus?: OrderItemTrackStatus;
	orderNumList?: string[];
	orderItemSortBy?: OrderItemSortBy;
	billDateStart?: number;
	billDateEnd?: number;
	cancelDateStart?: number;
	cancelDateEnd?: number;
}
export interface UserPackingListFilter {
	pkgNumbers?: string[];
	pkgIds?: number[];
}
export interface UserProductListFilter {
	isOnSale?: boolean;
	sellType?: ProductSellType;
	quantityLow?: boolean;
	productName?: string;
	unCommitted?: boolean;
	soldCountSortType?: SortType;
	minPrice?: number;
	maxPrice?: number;
	minCreateDate?: number;
	maxCreateDate?: number;
	isStocked?: boolean;
}
export interface UserProductListResult {
	total: number;
	onSaleCount: number;
	products: ProductSimple[];
}
export interface UserProductQuickChange {
	isOnSale?: boolean;
	name?: string;
	shipment?: ProductShipmentInfo;
	shouldTranslateName?: boolean;
}
export interface UserSearchProductAnalyticsFilter {
	keyword?: string;
	url?: string;
	offset?: number;
	limit?: number;
}
export interface UserSearchProductAnalyticsItem {
	productId: number;
	productName: string;
	imageUrl: string;
}
export interface UserSearchProductAnalyticsResult {
	items?: UserSearchProductAnalyticsItem[];
}
export interface UserShopIndexAnnouncement {
	announcementId: number;
	title: string;
	time: number;
}
export interface UserShopIndexDataGet {
	lastThirtyDays: UserShopIndexSales;
	lastDay: UserShopIndexSales;
	orderStatus: UserShopIndexOrderStatus;
	productStatus: UserShopIndexProductStatus;
	announcements: UserShopIndexAnnouncement[];
	productRank: UserShopIndexProduct[];
}
export interface UserShopIndexOrderStatus {
	pendingCount: number;
	overTimeCount: number;
	dispatchedCount: number;
	warehouseRcvdCount: number;
	pendingSendCount: number;
}
export interface UserShopIndexProduct {
	productId: number;
	productName: string;
	salesCount: number;
}
export interface UserShopIndexProductStatus {
	onSaleCount: number;
	offSaleCount: number;
}
export interface UserShopIndexSales {
	AddCartCount: number;
	orderCount: number;
	paidCount: number;
	salesAmount: number;
}
export interface UserShopMailListFilter {
	createdAtFrom?: number;
	createdAtTo?: number;
	content?: string;
	readStatus?: boolean;
}
export interface UserShopMailListItem {
	mailId: number;
	createdAt: number;
	content: string;
	readStatus: boolean;
	enContent: string;
}
export interface UserShopMailListResult {
	lists: UserShopMailListItem[];
	total: number;
}
export interface UserShopMailReadReq {
	mailId?: number;
	allMark?: boolean;
}
export interface UserShopStatisticsReq {
	rangeStart: number;
	rangeEnd: number;
}
export interface UserShopStatisticsResp {
	addToCartCount: number;
	vendorOrderAmount: number;
	orderTotalCount: number;
	orderCancelCount: number;
	orderCustomerCount: number;
	orderPayCount: number;
	orderCashOffCount: number;
	orderFlashSalesCount: number;
	orderFreeShippingCount: number;
	orderFriendsDealCount: number;
	orderOtherCount: number;
	productLists: { [key: string]: ProductItem[] };
}
export interface UserTransferAccountInfo {
	transferAccount: TransferAccountInfo;
	changeTransferAccount: TransferAccountInfo;
	changeStatus: TransferAccountChangeStatus;
	rejectedMsg: string;
	changeDate: number;
}
export interface WarehouseExportInformationItem {
	packageNumber: string;
	packagesCount: number;
	weight: number;
	packingNumbers: string[];
	shipperName: string;
	receiver: InvoiceConsignee;
	description: string[];
	pcs: string[];
	value: number;
}
export interface WarehousePackage {
	pkgId: number;
	pkgNumber: string;
	subPackageCount: number;
	state: string;
	shopName: string;
	catalogCode: string;
	shipmentTypeName: string;
	shopDeliveredDate: number;
	warehouseReceivedDate: number;
	shippedDate: number;
	shipperName: string;
	shipCode: string;
}
export interface WarehousePackageListFilter {
	shipmentType?: number;
	pkgNumber?: string;
	state?: WarehousePackageFilterState;
	catalogCode?: string;
	shopDeliveredStartDate?: number;
	shopDeliveredEndDate?: number;
	warehouseRecvStartDate?: number;
	warehouseRecvEndDate?: number;
	warehouseShippedStartDate?: number;
	warehouseShippedEndDate?: number;
}
export interface WarehousePackageListResult {
	total: number;
	data: WarehousePackage[];
}

export function AccountCanSigninByPhone(phone: string): Promise<boolean> {
	return webapi<boolean>("EzSeller.AccountCanSigninByPhone", { phone });
}

export function AccountForgetPassword(username: string): Promise<AccountForgetPasswordResult> {
	return webapi<AccountForgetPasswordResult>("EzSeller.AccountForgetPassword", { username });
}

export function AccountForgetPasswordByPhone(
	phone: string,
	vericode: string
): Promise<AccountForgetPasswordByPhoneResult> {
	return webapi<AccountForgetPasswordByPhoneResult>("EzSeller.AccountForgetPasswordByPhone", {
		phone,
		vericode
	});
}

export function AccountForgetPasswordUserName(
	token: string,
	username: string,
	phone: string
): Promise<AccountForgetPasswordUserNameResult> {
	return webapi<AccountForgetPasswordUserNameResult>("EzSeller.AccountForgetPasswordUserName", {
		token,
		username,
		phone
	});
}

export function AccountNotifications(): Promise<{ [key: string]: AccountNotificationSetting }> {
	return webapi<{ [key: string]: AccountNotificationSetting }>("EzSeller.AccountNotifications", {});
}

export function AccountRegister(
	email: string,
	username: string,
	password: string
): Promise<AccountBase> {
	return webapi<AccountBase>("EzSeller.AccountRegister", { email, username, password });
}

export function AccountRegisterByPhone(
	phone: string,
	username: string,
	password: string,
	vericode: string
): Promise<AccountBase> {
	return webapi<AccountBase>("EzSeller.AccountRegisterByPhone", {
		phone,
		username,
		password,
		vericode
	});
}

export function AccountResetPassword(token: string, newpass: string): Promise<AccountBase> {
	return webapi<AccountBase>("EzSeller.AccountResetPassword", { token, newpass });
}

export function AccountSignin(username: string, password: string): Promise<AccountBase> {
	return webapi<AccountBase>("EzSeller.AccountSignin", { username, password });
}

export function AccountUpdateNotificationChannel(
	channel: NotificationChannel,
	value: string
): Promise<boolean> {
	return webapi<boolean>("EzSeller.AccountUpdateNotificationChannel", { channel, value });
}

export function AccountUpdateNotifications(types: {
	[key: string]: NotificationType[];
}): Promise<boolean> {
	return webapi<boolean>("EzSeller.AccountUpdateNotifications", { types });
}

export function AccountValidEmail(email: string): Promise<boolean> {
	return webapi<boolean>("EzSeller.AccountValidEmail", { email });
}

export function AccountValidPassword(password: string): Promise<boolean> {
	return webapi<boolean>("EzSeller.AccountValidPassword", { password });
}

export function AccountValidPhone(phone: string): Promise<LoginFieldCheckResult> {
	return webapi<LoginFieldCheckResult>("EzSeller.AccountValidPhone", { phone });
}

export function AccountValidUsername(username: string): Promise<boolean> {
	return webapi<boolean>("EzSeller.AccountValidUsername", { username });
}

export function AdminAddAnnouncementCata(pCId: number, subVal: string): Promise<boolean> {
	return webapi<boolean>("EzSeller.AdminAddAnnouncementCata", { pCId, subVal });
}

export function AdminAnnouncementCataGet(pCId: number): Promise<AdminAnnouncementCataGetResult> {
	return webapi<AdminAnnouncementCataGetResult>("EzSeller.AdminAnnouncementCataGet", { pCId });
}

export function AdminAnnouncementCataList(): Promise<AdminAnnouncementCataListResult> {
	return webapi<AdminAnnouncementCataListResult>("EzSeller.AdminAnnouncementCataList", {});
}

export function AdminAnnouncementCataUpdate(announcementId: number, cId: number): Promise<boolean> {
	return webapi<boolean>("EzSeller.AdminAnnouncementCataUpdate", { announcementId, cId });
}

export function AdminAnnouncementDelete(announcementId: number): Promise<boolean> {
	return webapi<boolean>("EzSeller.AdminAnnouncementDelete", { announcementId });
}

export function AdminAnnouncementGet(announcementId: number): Promise<AdminAnnouncementGetResult> {
	return webapi<AdminAnnouncementGetResult>("EzSeller.AdminAnnouncementGet", { announcementId });
}

export function AdminAnnouncementList(
	offset: number,
	limit: number,
	filter: AdminAnnouncementListFilter
): Promise<AdminAnnouncementListResult> {
	return webapi<AdminAnnouncementListResult>("EzSeller.AdminAnnouncementList", {
		offset,
		limit,
		filter
	});
}

export function AdminAnnouncementLog(
	offset: number,
	limit: number,
	announcementId: number
): Promise<AdminAnnouncementLogResult> {
	return webapi<AdminAnnouncementLogResult>("EzSeller.AdminAnnouncementLog", {
		offset,
		limit,
		announcementId
	});
}

export function AdminAnnouncementPublish(announcementId: number): Promise<boolean> {
	return webapi<boolean>("EzSeller.AdminAnnouncementPublish", { announcementId });
}

export function AdminAnnouncementShopList(
	offset: number,
	limit: number,
	announcementId: number,
	filter: AdminAnnouncementShopListFilter
): Promise<AdminAnnouncementShopListResult> {
	return webapi<AdminAnnouncementShopListResult>("EzSeller.AdminAnnouncementShopList", {
		offset,
		limit,
		announcementId,
		filter
	});
}

export function AdminAnnouncementShopListExportTask(
	announcementId: number
): Promise<ExportTaskResult> {
	return webapi<ExportTaskResult>("EzSeller.AdminAnnouncementShopListExportTask", {
		announcementId
	});
}

export function AdminAnnouncementUpdate(req: AdminAnnouncementUpdateReq): Promise<boolean> {
	return webapi<boolean>("EzSeller.AdminAnnouncementUpdate", { req });
}

export function AdminDelAnnouncementCata(cId: number): Promise<boolean> {
	return webapi<boolean>("EzSeller.AdminDelAnnouncementCata", { cId });
}

export function AdminExportTask(id: string): Promise<ExportTask> {
	return webapi<ExportTask>("EzSeller.AdminExportTask", { id });
}

export function AdminExportTaskList(
	filter: AdminExportTaskListFilter,
	offset: number,
	limit: number
): Promise<AdminExportTaskListResult> {
	return webapi<AdminExportTaskListResult>("EzSeller.AdminExportTaskList", {
		filter,
		offset,
		limit
	});
}

export function AdminMirrorProductCandidateList(
	filter: MirrorProductCandidateListFilter
): Promise<MirrorProductCandidate[]> {
	return webapi<MirrorProductCandidate[]>("EzSeller.AdminMirrorProductCandidateList", { filter });
}

export function AdminMirrorProductDetail(productId: number): Promise<MirrorProductDetail> {
	return webapi<MirrorProductDetail>("EzSeller.AdminMirrorProductDetail", { productId });
}

export function AdminMirrorProductFetch(urls: string[]): Promise<boolean> {
	return webapi<boolean>("EzSeller.AdminMirrorProductFetch", { urls });
}

export function AdminMirrorProductList(
	offset: number,
	limit: number,
	filter: UserEzChoiseProductListFilter
): Promise<MirrorProductSimple[]> {
	return webapi<MirrorProductSimple[]>("EzSeller.AdminMirrorProductList", {
		offset,
		limit,
		filter
	});
}

export function AdminMirrorProductOrderList(
	productId: number,
	filter: AdminMirrorProductOrderListFilter,
	sort: AdminMirrorProductOrderListSort,
	offset: number,
	limit: number
): Promise<MirrorProductOrder[]> {
	return webapi<MirrorProductOrder[]>("EzSeller.AdminMirrorProductOrderList", {
		productId,
		filter,
		sort,
		offset,
		limit
	});
}

export function AdminMirrorProductProviderList(
	productId: number
): Promise<MirrorProductProvider[]> {
	return webapi<MirrorProductProvider[]>("EzSeller.AdminMirrorProductProviderList", { productId });
}

export function AdminMirrorProductUpdate(
	data: ProductBase,
	skus: MirrorProductSku[]
): Promise<MirrorProductDetail> {
	return webapi<MirrorProductDetail>("EzSeller.AdminMirrorProductUpdate", { data, skus });
}

export function AdminOpAnnouncementDelete(announcementId: number): Promise<boolean> {
	return webapi<boolean>("EzSeller.AdminOpAnnouncementDelete", { announcementId });
}

export function AdminOpAnnouncementGet(announcementId: number): Promise<AdminOpAnnouncementDetail> {
	return webapi<AdminOpAnnouncementDetail>("EzSeller.AdminOpAnnouncementGet", { announcementId });
}

export function AdminOpAnnouncementList(
	offset: number,
	limit: number,
	filter: AdminOpAnnouncementListFilter
): Promise<AdminOpAnnouncementListResult> {
	return webapi<AdminOpAnnouncementListResult>("EzSeller.AdminOpAnnouncementList", {
		offset,
		limit,
		filter
	});
}

export function AdminOpAnnouncementUpdate(
	announcementId: number,
	detail: AnnouncementDetail,
	publish: boolean
): Promise<AdminOpAnnouncementDetail> {
	return webapi<AdminOpAnnouncementDetail>("EzSeller.AdminOpAnnouncementUpdate", {
		announcementId,
		detail,
		publish
	});
}

export function AdminOpFetchProductSkuPrice(productIds: number[]): Promise<ProductSkuPrice[]> {
	return webapi<ProductSkuPrice[]>("EzSeller.AdminOpFetchProductSkuPrice", { productIds });
}

export function AdminOpJdBalance(): Promise<AdminOpJdBalanceResult> {
	return webapi<AdminOpJdBalanceResult>("EzSeller.AdminOpJdBalance", {});
}

export function AdminOpOrderList(
	offset: number,
	limit: number,
	filter: AdminOpOrderListFilter
): Promise<AdminOpOrderListResult> {
	return webapi<AdminOpOrderListResult>("EzSeller.AdminOpOrderList", { offset, limit, filter });
}

export function AdminOpOrderListExport(filter: AdminOpOrderListFilter): Promise<ExportFile> {
	return webapi<ExportFile>("EzSeller.AdminOpOrderListExport", { filter });
}

export function AdminOpOrderListExportTask(
	filter: AdminOpOrderListFilter
): Promise<ExportTaskResult> {
	return webapi<ExportTaskResult>("EzSeller.AdminOpOrderListExportTask", { filter });
}

export function AdminOpOrderListExportTaskNew(
	filter: AdminOpOrderListFilterNew
): Promise<ExportTaskResult> {
	return webapi<ExportTaskResult>("EzSeller.AdminOpOrderListExportTaskNew", { filter });
}

export function AdminOpOrderListNew(
	offset: number,
	limit: number,
	filter: AdminOpOrderListFilterNew
): Promise<AdminOpOrderListResultNew> {
	return webapi<AdminOpOrderListResultNew>("EzSeller.AdminOpOrderListNew", {
		offset,
		limit,
		filter
	});
}

export function AdminOpProductBatchOffSale(
	productIds: number[],
	forcedOffSale: boolean
): Promise<number[]> {
	return webapi<number[]>("EzSeller.AdminOpProductBatchOffSale", { productIds, forcedOffSale });
}

export function AdminOpProductChangeLogList(
	offset: number,
	limit: number,
	productId: number,
	filter: AdminOpProductChangeLogListFilter
): Promise<AdminOpProductChangeLogListResult> {
	return webapi<AdminOpProductChangeLogListResult>("EzSeller.AdminOpProductChangeLogList", {
		offset,
		limit,
		productId,
		filter
	});
}

export function AdminOpProductDetail(productId: number): Promise<ProductDetail> {
	return webapi<ProductDetail>("EzSeller.AdminOpProductDetail", { productId });
}

export function AdminOpProductList(
	offset: number,
	limit: number,
	filter: AdminOpProductListFilter
): Promise<AdminOpProductListResult> {
	return webapi<AdminOpProductListResult>("EzSeller.AdminOpProductList", { offset, limit, filter });
}

export function AdminOpProductListExport(filter: AdminOpProductListFilter): Promise<ExportFile> {
	return webapi<ExportFile>("EzSeller.AdminOpProductListExport", { filter });
}

export function AdminOpProductListExportTask(
	filter: AdminOpProductListFilter
): Promise<ExportTaskResult> {
	return webapi<ExportTaskResult>("EzSeller.AdminOpProductListExportTask", { filter });
}

export function AdminOpProductOffSale(
	productId: number,
	forcedOffSale: boolean,
	reason: string
): Promise<boolean> {
	return webapi<boolean>("EzSeller.AdminOpProductOffSale", { productId, forcedOffSale, reason });
}

export function AdminOpProductOperationLogList(
	offset: number,
	limit: number,
	productId: number,
	filter: AdminOpProductOperationLogListFilter
): Promise<AdminOpProductOperationLogListResult> {
	return webapi<AdminOpProductOperationLogListResult>("EzSeller.AdminOpProductOperationLogList", {
		offset,
		limit,
		productId,
		filter
	});
}

export function AdminOpRecommendProductImportTask(fileKey: string): Promise<ImportTaskResult> {
	return webapi<ImportTaskResult>("EzSeller.AdminOpRecommendProductImportTask", { fileKey });
}

export function AdminOpRemarkList(orderItemId: number): Promise<AdminOpRemarkListResult> {
	return webapi<AdminOpRemarkListResult>("EzSeller.AdminOpRemarkList", { orderItemId });
}

export function AdminOpServiceFeeRateHistory(
	offset: number,
	limit: number,
	started: number,
	ended: number
): Promise<AdminOpServiceFeeRateHistoryResp> {
	return webapi<AdminOpServiceFeeRateHistoryResp>("EzSeller.AdminOpServiceFeeRateHistory", {
		offset,
		limit,
		started,
		ended
	});
}

export function AdminOpServiceFeeRateSettings(
	categoryId: number
): Promise<AdminOpServiceFeeRateSettings> {
	return webapi<AdminOpServiceFeeRateSettings>("EzSeller.AdminOpServiceFeeRateSettings", {
		categoryId
	});
}

export function AdminOpServiceFeeRateSettingsUpdate(
	categoryId: number,
	exRate: number,
	curRate: number
): Promise<AdminOpServiceFeeRateSettings> {
	return webapi<AdminOpServiceFeeRateSettings>("EzSeller.AdminOpServiceFeeRateSettingsUpdate", {
		categoryId,
		exRate,
		curRate
	});
}

export function AdminOpServiceFeeRateShopSettingsUpdate(
	categoryId: number,
	updates: AdminOpServiceFeeRateShopUpdateItem[]
): Promise<AdminOpServiceFeeRateSettings> {
	return webapi<AdminOpServiceFeeRateSettings>("EzSeller.AdminOpServiceFeeRateShopSettingsUpdate", {
		categoryId,
		updates
	});
}

export function AdminOpShopList(
	offset: number,
	limit: number,
	filter: AdminOpShopListFilter,
	sort: AdminOpShopListSort
): Promise<AdminOpShopListResult> {
	return webapi<AdminOpShopListResult>("EzSeller.AdminOpShopList", { offset, limit, filter, sort });
}

export function AdminOpShopShutDown(shopId: number, shutDown: boolean): Promise<AdminOpShopSimple> {
	return webapi<AdminOpShopSimple>("EzSeller.AdminOpShopShutDown", { shopId, shutDown });
}

export function AdminShopApprovalDetail(formId: string): Promise<AdminShopApprovalDetail> {
	return webapi<AdminShopApprovalDetail>("EzSeller.AdminShopApprovalDetail", { formId });
}

export function AdminShopApprovalFormList(
	offset: number,
	limit: number,
	filter: AdminShopApprovalListFilter
): Promise<AdminShopApprovalFormListResult> {
	return webapi<AdminShopApprovalFormListResult>("EzSeller.AdminShopApprovalFormList", {
		offset,
		limit,
		filter
	});
}

export function AdminShopApprovalOplog(formId: string): Promise<AdminShopApprovalOplog[]> {
	return webapi<AdminShopApprovalOplog[]>("EzSeller.AdminShopApprovalOplog", { formId });
}

export function AdminShopApprove(formId: string): Promise<boolean> {
	return webapi<boolean>("EzSeller.AdminShopApprove", { formId });
}

export function AdminShopDeny(formId: string, remark: string): Promise<boolean> {
	return webapi<boolean>("EzSeller.AdminShopDeny", { formId, remark });
}

export function AdminTransferAccountChangeApproved(id: string): Promise<boolean> {
	return webapi<boolean>("EzSeller.AdminTransferAccountChangeApproved", { id });
}

export function AdminTransferAccountChangeInfo(
	id: string
): Promise<AdminTransferAccountChangeInfoResult> {
	return webapi<AdminTransferAccountChangeInfoResult>("EzSeller.AdminTransferAccountChangeInfo", {
		id
	});
}

export function AdminTransferAccountChangeList(
	filter: AdminTransferAccountChangeListFilter,
	offset: number,
	limit: number
): Promise<AdminTransferAccountChangeListResult> {
	return webapi<AdminTransferAccountChangeListResult>("EzSeller.AdminTransferAccountChangeList", {
		filter,
		offset,
		limit
	});
}

export function AdminTransferAccountChangeLog(
	id: string,
	offset: number,
	limit: number
): Promise<AdminTransferAccountChangeLogResult> {
	return webapi<AdminTransferAccountChangeLogResult>("EzSeller.AdminTransferAccountChangeLog", {
		id,
		offset,
		limit
	});
}

export function AdminTransferAccountChangeRejected(
	id: string,
	rejectedMsg: string
): Promise<boolean> {
	return webapi<boolean>("EzSeller.AdminTransferAccountChangeRejected", { id, rejectedMsg });
}

export function AppendUserOrderShipmentNumber(
	orderItemId: string,
	track: OrderTrack
): Promise<boolean> {
	return webapi<boolean>("EzSeller.AppendUserOrderShipmentNumber", { orderItemId, track });
}

export function BankListOfOrigin(originCode: string): Promise<string[]> {
	return webapi<string[]>("EzSeller.BankListOfOrigin", { originCode });
}

export function BatchHandleIssueOrder(info: CompletedSession[]): Promise<boolean> {
	return webapi<boolean>("EzSeller.BatchHandleIssueOrder", { info });
}

export function ERPBatchBillExportTask(
	billNums: string[],
	fileName: string
): Promise<ExportTaskResult> {
	return webapi<ExportTaskResult>("EzSeller.ERPBatchBillExportTask", { billNums, fileName });
}

export function ERPBillApprove(billNum: string, amount: number, remark: string): Promise<boolean> {
	return webapi<boolean>("EzSeller.ERPBillApprove", { billNum, amount, remark });
}

export function ERPBillBatchApprove(approveItems: ERPBillApproveItem[]): Promise<boolean> {
	return webapi<boolean>("EzSeller.ERPBillBatchApprove", { approveItems });
}

export function ERPBillBatchMark(billNums: string[]): Promise<boolean> {
	return webapi<boolean>("EzSeller.ERPBillBatchMark", { billNums });
}

export function ERPBillDetail(
	billNum: string,
	filter: ERPBillDetailFilter
): Promise<ERPBillDetailResult> {
	return webapi<ERPBillDetailResult>("EzSeller.ERPBillDetail", { billNum, filter });
}

export function ERPBillDetailExport(billNum: string): Promise<ExportFile> {
	return webapi<ExportFile>("EzSeller.ERPBillDetailExport", { billNum });
}

export function ERPBillDispose(disposeItem: ERPBillDisposeItem): Promise<boolean> {
	return webapi<boolean>("EzSeller.ERPBillDispose", { disposeItem });
}

export function ERPBillList(
	offset: number,
	limit: number,
	filter: ERPBillListFilter
): Promise<ERPBillListResult> {
	return webapi<ERPBillListResult>("EzSeller.ERPBillList", { offset, limit, filter });
}

export function ERPExportTask(id: string): Promise<ExportTask> {
	return webapi<ExportTask>("EzSeller.ERPExportTask", { id });
}

export function ERPExportTaskList(
	filter: ERPExportTaskListFilter,
	offset: number,
	limit: number
): Promise<ERPExportTaskListResult> {
	return webapi<ERPExportTaskListResult>("EzSeller.ERPExportTaskList", { filter, offset, limit });
}

export function ERPShopSearchList(req: ERPShopSearchListReq): Promise<ERPShopSearchListResp> {
	return webapi<ERPShopSearchListResp>("EzSeller.ERPShopSearchList", { req });
}

export function ERPTransferApprove(
	billNum: string,
	transferInfo: TransferInfo,
	remark: string
): Promise<boolean> {
	return webapi<boolean>("EzSeller.ERPTransferApprove", { billNum, transferInfo, remark });
}

export function ERPTransferBatchApprove(billNums: string[]): Promise<boolean> {
	return webapi<boolean>("EzSeller.ERPTransferBatchApprove", { billNums });
}

export function ERPTransferBatchConfirm(billNums: string[]): Promise<boolean> {
	return webapi<boolean>("EzSeller.ERPTransferBatchConfirm", { billNums });
}

export function ERPTransferBatchMark(billNums: string[]): Promise<boolean> {
	return webapi<boolean>("EzSeller.ERPTransferBatchMark", { billNums });
}

export function ERPTransferBatchTransferred(items: ERPTransferDoneItem[]): Promise<boolean> {
	return webapi<boolean>("EzSeller.ERPTransferBatchTransferred", { items });
}

export function ERPTransferCardInfoExportTask(billNums: string[]): Promise<ExportTaskResult> {
	return webapi<ExportTaskResult>("EzSeller.ERPTransferCardInfoExportTask", { billNums });
}

export function ERPTransferCheck(billNum: string): Promise<boolean> {
	return webapi<boolean>("EzSeller.ERPTransferCheck", { billNum });
}

export function ERPTransferList(
	offset: number,
	limit: number,
	filter: ERPTransferFilter
): Promise<ERPTransferListResult> {
	return webapi<ERPTransferListResult>("EzSeller.ERPTransferList", { offset, limit, filter });
}

export function ErpUserOrderHasExisted(baseInfo: BaseInfo): Promise<string[]> {
	return webapi<string[]>("EzSeller.ErpUserOrderHasExisted", { baseInfo });
}

export function GetEzsellerNewMessage(filter: SessionFilter): Promise<MessageResult> {
	return webapi<MessageResult>("EzSeller.GetEzsellerNewMessage", { filter });
}

export function GetEzsellerNewMessageTmp(filter: SessionFilter): Promise<MessageResult> {
	return webapi<MessageResult>("EzSeller.GetEzsellerNewMessageTmp", { filter });
}

export function GetSupporterNewMessage(filter: SessionFilter): Promise<MessageResult> {
	return webapi<MessageResult>("EzSeller.GetSupporterNewMessage", { filter });
}

export function GetUserOrderShipment(orderItemId: string): Promise<OrderTrack[]> {
	return webapi<OrderTrack[]>("EzSeller.GetUserOrderShipment", { orderItemId });
}

export function InvoiceGeneratePackageNumber(
	pkgId: number,
	boxCnt: number,
	pkgCnt: number,
	ignoreExists: boolean
): Promise<string[]> {
	return webapi<string[]>("EzSeller.InvoiceGeneratePackageNumber", {
		pkgId,
		boxCnt,
		pkgCnt,
		ignoreExists
	});
}

export function InvoiceGet(pkgId: number): Promise<Invoice> {
	return webapi<Invoice>("EzSeller.InvoiceGet", { pkgId });
}

export function SellerFeedback(
	offset: number,
	limit: number,
	filter: SellerFeedbackFilter
): Promise<SellerFeedbackResp> {
	return webapi<SellerFeedbackResp>("EzSeller.SellerFeedback", { offset, limit, filter });
}

export function SendFromEzbuySupporter(body: MsgInstance): Promise<boolean> {
	return webapi<boolean>("EzSeller.SendFromEzbuySupporter", { body });
}

export function SendFromEzseller(body: MsgInstance): Promise<boolean> {
	return webapi<boolean>("EzSeller.SendFromEzseller", { body });
}

export function SendFromEzsellerTmp(body: MsgInstance): Promise<boolean> {
	return webapi<boolean>("EzSeller.SendFromEzsellerTmp", { body });
}

export function ShopBatchUpdateSkus(fileKey: string): Promise<string[]> {
	return webapi<string[]>("EzSeller.ShopBatchUpdateSkus", { fileKey });
}

export function ShopExportSkus(filter: UserProductListFilter): Promise<ExportFile> {
	return webapi<ExportFile>("EzSeller.ShopExportSkus", { filter });
}

export function SnapshootOfEzseller(orderNum: string, msgType: MessageType): Promise<ChatlogResp> {
	return webapi<ChatlogResp>("EzSeller.SnapshootOfEzseller", { orderNum, msgType });
}

export function SnapshootOfEzsellerTmp(
	orderNum: string,
	msgType: MessageType
): Promise<ChatlogResp> {
	return webapi<ChatlogResp>("EzSeller.SnapshootOfEzsellerTmp", { orderNum, msgType });
}

export function SnapshootOfSupporter(orderNum: string, msgType: MessageType): Promise<ChatlogResp> {
	return webapi<ChatlogResp>("EzSeller.SnapshootOfSupporter", { orderNum, msgType });
}

export function UserAccountUpdatePassword(oldpass: string, newpass: string): Promise<boolean> {
	return webapi<boolean>("EzSeller.UserAccountUpdatePassword", { oldpass, newpass });
}

export function UserAlterPackageTrackInfo(
	pkgId: number,
	trackInfo: PackageTrackInfo
): Promise<ActionResult> {
	return webapi<ActionResult>("EzSeller.UserAlterPackageTrackInfo", { pkgId, trackInfo });
}

export function UserAnnAndMailCount(): Promise<UserAnnAndMailCountResult> {
	return webapi<UserAnnAndMailCountResult>("EzSeller.UserAnnAndMailCount", {});
}

export function UserAnnouncementGet(announcementId: number): Promise<UserAnnouncementGetResult> {
	return webapi<UserAnnouncementGetResult>("EzSeller.UserAnnouncementGet", { announcementId });
}

export function UserAnnouncementList(
	offset: number,
	limit: number,
	filter: UserAnnouncementListFilter
): Promise<UserAnnouncementListResult> {
	return webapi<UserAnnouncementListResult>("EzSeller.UserAnnouncementList", {
		offset,
		limit,
		filter
	});
}

export function UserAnnouncementNonViewedCount(): Promise<number> {
	return webapi<number>("EzSeller.UserAnnouncementNonViewedCount", {});
}

export function UserAnnouncementRead(req: UserAnnouncementReadReq): Promise<boolean> {
	return webapi<boolean>("EzSeller.UserAnnouncementRead", { req });
}

export function UserBatchPackageDispatch(pkgIds: number[]): Promise<ActionResult[]> {
	return webapi<ActionResult[]>("EzSeller.UserBatchPackageDispatch", { pkgIds });
}

export function UserBillAppeal(billNum: string, amount: number, remark: string): Promise<boolean> {
	return webapi<boolean>("EzSeller.UserBillAppeal", { billNum, amount, remark });
}

export function UserBillList(
	offset: number,
	limit: number,
	filter: UserBillListFilter
): Promise<UserBillListResult> {
	return webapi<UserBillListResult>("EzSeller.UserBillList", { offset, limit, filter });
}

export function UserBillOrderExportTask(billNum: string): Promise<ExportTaskResult> {
	return webapi<ExportTaskResult>("EzSeller.UserBillOrderExportTask", { billNum });
}

export function UserBillOrderItemExportTask(billNum: string): Promise<ExportTaskResult> {
	return webapi<ExportTaskResult>("EzSeller.UserBillOrderItemExportTask", { billNum });
}

export function UserBillOrderItemList(billNum: string): Promise<UserBillOrderItemResult> {
	return webapi<UserBillOrderItemResult>("EzSeller.UserBillOrderItemList", { billNum });
}

export function UserBillOrderItemListExport(billNum: string): Promise<ExportFile> {
	return webapi<ExportFile>("EzSeller.UserBillOrderItemListExport", { billNum });
}

export function UserBillOrderList(billNum: string): Promise<UserBillOrderResult> {
	return webapi<UserBillOrderResult>("EzSeller.UserBillOrderList", { billNum });
}

export function UserBillOrderListExport(billNum: string): Promise<ExportFile> {
	return webapi<ExportFile>("EzSeller.UserBillOrderListExport", { billNum });
}

export function UserBillTransferAdd(billNum: string, accountName: string): Promise<boolean> {
	return webapi<boolean>("EzSeller.UserBillTransferAdd", { billNum, accountName });
}

export function UserBillTransferInfo(billNum: string): Promise<Transfer> {
	return webapi<Transfer>("EzSeller.UserBillTransferInfo", { billNum });
}

export function UserDailyReportGet(filter: UserDailyReportFilter): Promise<UserDailyReport> {
	return webapi<UserDailyReport>("EzSeller.UserDailyReportGet", { filter });
}

export function UserExportTask(id: string): Promise<ExportTask> {
	return webapi<ExportTask>("EzSeller.UserExportTask", { id });
}

export function UserExportTaskList(
	filter: UserExportTaskListFilter,
	offset: number,
	limit: number
): Promise<UserExportTaskListResult> {
	return webapi<UserExportTaskListResult>("EzSeller.UserExportTaskList", { filter, offset, limit });
}

export function UserGetProductAnalytics(
	filter: UserGetProductAnalyticsFilter
): Promise<UserGetProductAnalyticsResult> {
	return webapi<UserGetProductAnalyticsResult>("EzSeller.UserGetProductAnalytics", { filter });
}

export function UserGetProductSimpleInfo(productName: string): Promise<ProductSimpleInfo[]> {
	return webapi<ProductSimpleInfo[]>("EzSeller.UserGetProductSimpleInfo", { productName });
}

export function UserGetShipmentTypes(catelogCode: string): Promise<ShipmentType[]> {
	return webapi<ShipmentType[]>("EzSeller.UserGetShipmentTypes", { catelogCode });
}

export function UserImportEzbuyProducts(urls: string[]): Promise<boolean> {
	return webapi<boolean>("EzSeller.UserImportEzbuyProducts", { urls });
}

export function UserImportSubTaskList(
	taskId: string,
	offset: number,
	limit: number,
	filter: UserImportSubTaskListFilter
): Promise<UserImportSubTaskListResult> {
	return webapi<UserImportSubTaskListResult>("EzSeller.UserImportSubTaskList", {
		taskId,
		offset,
		limit,
		filter
	});
}

export function UserImportSubTaskProductDetail(subTaskId: string): Promise<ProductDetail> {
	return webapi<ProductDetail>("EzSeller.UserImportSubTaskProductDetail", { subTaskId });
}

export function UserImportSubTaskProductUpdate(
	subTaskId: string,
	data: ProductBase,
	skus: ProductSku[]
): Promise<ProductDetail> {
	return webapi<ProductDetail>("EzSeller.UserImportSubTaskProductUpdate", {
		subTaskId,
		data,
		skus
	});
}

export function UserImportTaskAdd(urls: string[], taskType: ImportTaskType): Promise<boolean> {
	return webapi<boolean>("EzSeller.UserImportTaskAdd", { urls, taskType });
}

export function UserImportTaskList(offset: number, limit: number): Promise<ImportTaskListResult> {
	return webapi<ImportTaskListResult>("EzSeller.UserImportTaskList", { offset, limit });
}

export function UserImportTaskRetry(task: ImportTaskRetry): Promise<UserImportTaskRetryResult> {
	return webapi<UserImportTaskRetryResult>("EzSeller.UserImportTaskRetry", { task });
}

export function UserMirrorProductLink(productId: number): Promise<ProductDetail> {
	return webapi<ProductDetail>("EzSeller.UserMirrorProductLink", { productId });
}

export function UserMirrorProductList(
	offset: number,
	limit: number,
	filter: UserMirrorProductListFilter
): Promise<UserMirrorProductListResult> {
	return webapi<UserMirrorProductListResult>("EzSeller.UserMirrorProductList", {
		offset,
		limit,
		filter
	});
}

export function UserMirrorProductUnLink(productId: number): Promise<boolean> {
	return webapi<boolean>("EzSeller.UserMirrorProductUnLink", { productId });
}

export function UserNewImportTaskList(
	filter: UserImportTaskListFilter,
	offset: number,
	limit: number
): Promise<UserImportTaskListResult> {
	return webapi<UserImportTaskListResult>("EzSeller.UserNewImportTaskList", {
		filter,
		offset,
		limit
	});
}

export function UserOrderCancel(orderNums: string[], remark: string): Promise<boolean> {
	return webapi<boolean>("EzSeller.UserOrderCancel", { orderNums, remark });
}

export function UserOrderDetail(orderNum: string): Promise<OrderDetail> {
	return webapi<OrderDetail>("EzSeller.UserOrderDetail", { orderNum });
}

export function UserOrderDispatch(orderNum: string, track: OrderTrack): Promise<boolean> {
	return webapi<boolean>("EzSeller.UserOrderDispatch", { orderNum, track });
}

export function UserOrderDispatchImport(fileKey: string): Promise<OrderDispatchImportResult[]> {
	return webapi<OrderDispatchImportResult[]>("EzSeller.UserOrderDispatchImport", { fileKey });
}

export function UserOrderDispatchImportTask(fileKey: string): Promise<ImportTaskResult> {
	return webapi<ImportTaskResult>("EzSeller.UserOrderDispatchImportTask", { fileKey });
}

export function UserOrderDispatchNew(orderNum: string, track: OrderTrack): Promise<boolean> {
	return webapi<boolean>("EzSeller.UserOrderDispatchNew", { orderNum, track });
}

export function UserOrderDispatchNewImportTask(fileKey: string): Promise<ImportTaskResult> {
	return webapi<ImportTaskResult>("EzSeller.UserOrderDispatchNewImportTask", { fileKey });
}

export function UserOrderHasExisted(baseInfo: BaseInfo): Promise<string[]> {
	return webapi<string[]>("EzSeller.UserOrderHasExisted", { baseInfo });
}

export function UserOrderHasExistedTmp(baseInfo: BaseInfo): Promise<string[]> {
	return webapi<string[]>("EzSeller.UserOrderHasExistedTmp", { baseInfo });
}

export function UserOrderItemDispatch(orderItemIds: number[], track: OrderTrack): Promise<boolean> {
	return webapi<boolean>("EzSeller.UserOrderItemDispatch", { orderItemIds, track });
}

export function UserOrderItemGroupExport(
	filter: UserOrderItemListFilter,
	language: ExportFileLanguage
): Promise<ExportFile> {
	return webapi<ExportFile>("EzSeller.UserOrderItemGroupExport", { filter, language });
}

export function UserOrderItemGroupExportTask(
	filter: UserOrderItemListFilter,
	language: ExportFileLanguage
): Promise<ExportTaskResult> {
	return webapi<ExportTaskResult>("EzSeller.UserOrderItemGroupExportTask", { filter, language });
}

export function UserOrderItemGroupList(
	offset: number,
	limit: number,
	filter: UserOrderItemListFilter
): Promise<OrderItemGroupListResult> {
	return webapi<OrderItemGroupListResult>("EzSeller.UserOrderItemGroupList", {
		offset,
		limit,
		filter
	});
}

export function UserOrderItemGroupNewExportTask(
	filter: UserOrderListNewFilter,
	language: ExportFileLanguage
): Promise<ExportTaskResult> {
	return webapi<ExportTaskResult>("EzSeller.UserOrderItemGroupNewExportTask", { filter, language });
}

export function UserOrderItemList(
	offset: number,
	limit: number,
	filter: UserOrderItemListFilter
): Promise<OrderItem[]> {
	return webapi<OrderItem[]>("EzSeller.UserOrderItemList", { offset, limit, filter });
}

export function UserOrderItemRemarkAdd(orderItemId: number, remark: string): Promise<boolean> {
	return webapi<boolean>("EzSeller.UserOrderItemRemarkAdd", { orderItemId, remark });
}

export function UserOrderItemReturnConfirm(orderItemIds: number[]): Promise<boolean> {
	return webapi<boolean>("EzSeller.UserOrderItemReturnConfirm", { orderItemIds });
}

export function UserOrderItemTrackUpdate(
	orderItemIds: number[],
	track: OrderTrack
): Promise<boolean> {
	return webapi<boolean>("EzSeller.UserOrderItemTrackUpdate", { orderItemIds, track });
}

export function UserOrderList(
	offset: number,
	limit: number,
	filter: UserOrderListFilter
): Promise<OrderListResult> {
	return webapi<OrderListResult>("EzSeller.UserOrderList", { offset, limit, filter });
}

export function UserOrderListExportTask(
	filter: UserOrderListFilter,
	language: ExportFileLanguage
): Promise<ExportTaskResult> {
	return webapi<ExportTaskResult>("EzSeller.UserOrderListExportTask", { filter, language });
}

export function UserOrderListNew(
	offset: number,
	limit: number,
	filter: UserOrderListNewFilter
): Promise<NewOrderListResult> {
	return webapi<NewOrderListResult>("EzSeller.UserOrderListNew", { offset, limit, filter });
}

export function UserOrderListNewExportTask(
	filter: UserOrderListNewFilter,
	language: ExportFileLanguage
): Promise<ExportTaskResult> {
	return webapi<ExportTaskResult>("EzSeller.UserOrderListNewExportTask", { filter, language });
}

export function UserOrderRemarkAdd(orderNum: string, remark: string): Promise<boolean> {
	return webapi<boolean>("EzSeller.UserOrderRemarkAdd", { orderNum, remark });
}

export function UserOrderRemarkAddNew(orderNum: string, remark: string): Promise<boolean> {
	return webapi<boolean>("EzSeller.UserOrderRemarkAddNew", { orderNum, remark });
}

export function UserOrderStockout(baseInfo: BaseInfo, orderInfos: OrderInfo[]): Promise<boolean> {
	return webapi<boolean>("EzSeller.UserOrderStockout", { baseInfo, orderInfos });
}

export function UserOrderStockoutTmp(
	baseInfo: BaseInfo,
	orderInfos: OrderInfo[]
): Promise<boolean> {
	return webapi<boolean>("EzSeller.UserOrderStockoutTmp", { baseInfo, orderInfos });
}

export function UserOrderTrackDetailList(
	offset: number,
	limit: number,
	filter: OrderTrackDetailListFilter
): Promise<OrderTrackDetail[]> {
	return webapi<OrderTrackDetail[]>("EzSeller.UserOrderTrackDetailList", { offset, limit, filter });
}

export function UserOrderTrackUpdate(orderNum: string, track: OrderTrack): Promise<boolean> {
	return webapi<boolean>("EzSeller.UserOrderTrackUpdate", { orderNum, track });
}

export function UserOrderTrackUpdateNew(orderNum: string, tracks: OrderTrack[]): Promise<boolean> {
	return webapi<boolean>("EzSeller.UserOrderTrackUpdateNew", { orderNum, tracks });
}

export function UserPackageDispatch(
	pkgId: number,
	trackInfo: PackageTrackInfo
): Promise<ActionResult> {
	return webapi<ActionResult>("EzSeller.UserPackageDispatch", { pkgId, trackInfo });
}

export function UserPackageList(
	filter: ShopPackageListFilter,
	offset: number,
	limit: number
): Promise<PackageListResult> {
	return webapi<PackageListResult>("EzSeller.UserPackageList", { filter, offset, limit });
}

export function UserPackageTrackInfoDispatchImportTask(fileKey: string): Promise<ImportTaskResult> {
	return webapi<ImportTaskResult>("EzSeller.UserPackageTrackInfoDispatchImportTask", { fileKey });
}

export function UserPackingListExportTask(
	filter: UserPackingListFilter,
	language: ExportFileLanguage
): Promise<ExportTaskResult> {
	return webapi<ExportTaskResult>("EzSeller.UserPackingListExportTask", { filter, language });
}

export function UserPickList(pkgIds: number[]): Promise<PickListItem[]> {
	return webapi<PickListItem[]>("EzSeller.UserPickList", { pkgIds });
}

export function UserPickListExport(pkgIds: number[]): Promise<ExportFile> {
	return webapi<ExportFile>("EzSeller.UserPickListExport", { pkgIds });
}

export function UserProductAnalyticsReportExportTask(
	filter: UserGetProductAnalyticsFilter,
	language: ExportFileLanguage
): Promise<ExportTaskResult> {
	return webapi<ExportTaskResult>("EzSeller.UserProductAnalyticsReportExportTask", {
		filter,
		language
	});
}

export function UserProductBatchDelete(pids: number[]): Promise<ActionResult[]> {
	return webapi<ActionResult[]>("EzSeller.UserProductBatchDelete", { pids });
}

export function UserProductDetail(productId: number): Promise<ProductDetail> {
	return webapi<ProductDetail>("EzSeller.UserProductDetail", { productId });
}

export function UserProductList(
	offset: number,
	limit: number,
	filter: UserProductListFilter
): Promise<UserProductListResult> {
	return webapi<UserProductListResult>("EzSeller.UserProductList", { offset, limit, filter });
}

export function UserProductQuickUpdate(
	productId: number[],
	change: UserProductQuickChange
): Promise<boolean> {
	return webapi<boolean>("EzSeller.UserProductQuickUpdate", { productId, change });
}

export function UserProductUpdate(data: ProductBase, skus: ProductSku[]): Promise<ProductDetail> {
	return webapi<ProductDetail>("EzSeller.UserProductUpdate", { data, skus });
}

export function UserProductsFromSource(
	src: ProductSource,
	committed: boolean,
	offset: number,
	limit: number
): Promise<ProductsFromSourceResult> {
	return webapi<ProductsFromSourceResult>("EzSeller.UserProductsFromSource", {
		src,
		committed,
		offset,
		limit
	});
}

export function UserSearchProductAnalytics(
	filter: UserSearchProductAnalyticsFilter
): Promise<UserSearchProductAnalyticsResult> {
	return webapi<UserSearchProductAnalyticsResult>("EzSeller.UserSearchProductAnalytics", {
		filter
	});
}

export function UserShopApprovalFormGet(): Promise<ShopApprovalFormGetResult> {
	return webapi<ShopApprovalFormGetResult>("EzSeller.UserShopApprovalFormGet", {});
}

export function UserShopApprovalOrganization(
	shopName: string,
	requester: ShopApprovalRequesterInfo,
	form: ShopApprovalFormOrganization,
	originCode: string
): Promise<boolean> {
	return webapi<boolean>("EzSeller.UserShopApprovalOrganization", {
		shopName,
		requester,
		form,
		originCode
	});
}

export function UserShopApprovalOriganizationUpsert(
	shopName: string,
	requester: ShopApprovalRequesterInfo,
	form: ShopApprovalFormOrganization,
	originCode: string
): Promise<boolean> {
	return webapi<boolean>("EzSeller.UserShopApprovalOriganizationUpsert", {
		shopName,
		requester,
		form,
		originCode
	});
}

export function UserShopApprovalPersonal(
	shopName: string,
	requester: ShopApprovalRequesterInfo,
	form: ShopApprovalFormPersonal,
	originCode: string
): Promise<boolean> {
	return webapi<boolean>("EzSeller.UserShopApprovalPersonal", {
		shopName,
		requester,
		form,
		originCode
	});
}

export function UserShopApprovalPersonalUpsert(
	shopName: string,
	requester: ShopApprovalRequesterInfo,
	form: ShopApprovalFormPersonal,
	originCode: string
): Promise<boolean> {
	return webapi<boolean>("EzSeller.UserShopApprovalPersonalUpsert", {
		shopName,
		requester,
		form,
		originCode
	});
}

export function UserShopCreate(
	sellerInfo: SellerInfo,
	bizInfo: ShopApprovalFormOrgInfo,
	bankInfo: ShopApprovalFormBankInfo
): Promise<ActionResult> {
	return webapi<ActionResult>("EzSeller.UserShopCreate", { sellerInfo, bizInfo, bankInfo });
}

export function UserShopIndexDataGet(): Promise<UserShopIndexDataGet> {
	return webapi<UserShopIndexDataGet>("EzSeller.UserShopIndexDataGet", {});
}

export function UserShopMailList(
	offset: number,
	limit: number,
	filter: UserShopMailListFilter
): Promise<UserShopMailListResult> {
	return webapi<UserShopMailListResult>("EzSeller.UserShopMailList", { offset, limit, filter });
}

export function UserShopMailRead(req: UserShopMailReadReq): Promise<boolean> {
	return webapi<boolean>("EzSeller.UserShopMailRead", { req });
}

export function UserShopSetEverSignIn(): Promise<boolean> {
	return webapi<boolean>("EzSeller.UserShopSetEverSignIn", {});
}

export function UserShopShutDown(shutDown: boolean): Promise<ShopBase> {
	return webapi<ShopBase>("EzSeller.UserShopShutDown", { shutDown });
}

export function UserShopStatistics(filter: UserShopStatisticsReq): Promise<UserShopStatisticsResp> {
	return webapi<UserShopStatisticsResp>("EzSeller.UserShopStatistics", { filter });
}

export function UserShopValidShopName(shopName: string): Promise<boolean> {
	return webapi<boolean>("EzSeller.UserShopValidShopName", { shopName });
}

export function UserTransferAccountInfo(): Promise<UserTransferAccountInfo> {
	return webapi<UserTransferAccountInfo>("EzSeller.UserTransferAccountInfo", {});
}

export function UserTransferAccountInfoUpdate(
	password: string,
	info: TransferAccountInfo
): Promise<boolean> {
	return webapi<boolean>("EzSeller.UserTransferAccountInfoUpdate", { password, info });
}

export function UserTransferAccountInfoUpdateCancel(password: string): Promise<boolean> {
	return webapi<boolean>("EzSeller.UserTransferAccountInfoUpdateCancel", { password });
}

export function UserUnCommitedProductDetail(productId: number): Promise<ProductDetail> {
	return webapi<ProductDetail>("EzSeller.UserUnCommitedProductDetail", { productId });
}

export function UserUnCommitedProductUpdate(
	data: ProductBase,
	skus: ProductSku[]
): Promise<ProductDetail> {
	return webapi<ProductDetail>("EzSeller.UserUnCommitedProductUpdate", { data, skus });
}

export function UserUploadProducts(fileKey: string): Promise<string[]> {
	return webapi<string[]>("EzSeller.UserUploadProducts", { fileKey });
}

export function UserUploadProductsExport(categoryId: number): Promise<ExportFile> {
	return webapi<ExportFile>("EzSeller.UserUploadProductsExport", { categoryId });
}

export function WarehouseBatchDispatchPackage(
	pkgIds: number[],
	shipperTrack: OrderTrack
): Promise<boolean> {
	return webapi<boolean>("EzSeller.WarehouseBatchDispatchPackage", { pkgIds, shipperTrack });
}

export function WarehouseBatchReceivePackage(pkgIds: number[]): Promise<boolean> {
	return webapi<boolean>("EzSeller.WarehouseBatchReceivePackage", { pkgIds });
}

export function WarehouseDispatchPackage(
	pkgId: number,
	shipperTrack: OrderTrack
): Promise<boolean> {
	return webapi<boolean>("EzSeller.WarehouseDispatchPackage", { pkgId, shipperTrack });
}

export function WarehouseExportInformationExport(pkgIds: number[]): Promise<ExportFile> {
	return webapi<ExportFile>("EzSeller.WarehouseExportInformationExport", { pkgIds });
}

export function WarehouseGetShipmentTypes(catelogCode: string): Promise<ShipmentType[]> {
	return webapi<ShipmentType[]>("EzSeller.WarehouseGetShipmentTypes", { catelogCode });
}

export function WarehousePackageList(
	filter: WarehousePackageListFilter,
	offset: number,
	limit: number
): Promise<WarehousePackageListResult> {
	return webapi<WarehousePackageListResult>("EzSeller.WarehousePackageList", {
		filter,
		offset,
		limit
	});
}

export function WarehouseReceivePackage(pkgId: number): Promise<boolean> {
	return webapi<boolean>("EzSeller.WarehouseReceivePackage", { pkgId });
}

export function WarehouseShipperList(): Promise<Shipper[]> {
	return webapi<Shipper[]>("EzSeller.WarehouseShipperList", {});
}

export function WarehouseUserLogin(username: string, password: string): Promise<boolean> {
	return webapi<boolean>("EzSeller.WarehouseUserLogin", { username, password });
}

export function WarehouseUserRegister(username: string, password: string): Promise<boolean> {
	return webapi<boolean>("EzSeller.WarehouseUserRegister", { username, password });
}

export default {
	AccountCanSigninByPhone,
	AccountForgetPassword,
	AccountForgetPasswordByPhone,
	AccountForgetPasswordUserName,
	AccountNotifications,
	AccountRegister,
	AccountRegisterByPhone,
	AccountResetPassword,
	AccountSignin,
	AccountUpdateNotificationChannel,
	AccountUpdateNotifications,
	AccountValidEmail,
	AccountValidPassword,
	AccountValidPhone,
	AccountValidUsername,
	AdminAddAnnouncementCata,
	AdminAnnouncementCataGet,
	AdminAnnouncementCataList,
	AdminAnnouncementCataUpdate,
	AdminAnnouncementDelete,
	AdminAnnouncementGet,
	AdminAnnouncementList,
	AdminAnnouncementLog,
	AdminAnnouncementPublish,
	AdminAnnouncementShopList,
	AdminAnnouncementShopListExportTask,
	AdminAnnouncementUpdate,
	AdminDelAnnouncementCata,
	AdminExportTask,
	AdminExportTaskList,
	AdminMirrorProductCandidateList,
	AdminMirrorProductDetail,
	AdminMirrorProductFetch,
	AdminMirrorProductList,
	AdminMirrorProductOrderList,
	AdminMirrorProductProviderList,
	AdminMirrorProductUpdate,
	AdminOpAnnouncementDelete,
	AdminOpAnnouncementGet,
	AdminOpAnnouncementList,
	AdminOpAnnouncementUpdate,
	AdminOpFetchProductSkuPrice,
	AdminOpJdBalance,
	AdminOpOrderList,
	AdminOpOrderListExport,
	AdminOpOrderListExportTask,
	AdminOpOrderListExportTaskNew,
	AdminOpOrderListNew,
	AdminOpProductBatchOffSale,
	AdminOpProductChangeLogList,
	AdminOpProductDetail,
	AdminOpProductList,
	AdminOpProductListExport,
	AdminOpProductListExportTask,
	AdminOpProductOffSale,
	AdminOpProductOperationLogList,
	AdminOpRecommendProductImportTask,
	AdminOpRemarkList,
	AdminOpServiceFeeRateHistory,
	AdminOpServiceFeeRateSettings,
	AdminOpServiceFeeRateSettingsUpdate,
	AdminOpServiceFeeRateShopSettingsUpdate,
	AdminOpShopList,
	AdminOpShopShutDown,
	AdminShopApprovalDetail,
	AdminShopApprovalFormList,
	AdminShopApprovalOplog,
	AdminShopApprove,
	AdminShopDeny,
	AdminTransferAccountChangeApproved,
	AdminTransferAccountChangeInfo,
	AdminTransferAccountChangeList,
	AdminTransferAccountChangeLog,
	AdminTransferAccountChangeRejected,
	AppendUserOrderShipmentNumber,
	BankListOfOrigin,
	BatchHandleIssueOrder,
	ERPBatchBillExportTask,
	ERPBillApprove,
	ERPBillBatchApprove,
	ERPBillBatchMark,
	ERPBillDetail,
	ERPBillDetailExport,
	ERPBillDispose,
	ERPBillList,
	ERPExportTask,
	ERPExportTaskList,
	ERPShopSearchList,
	ERPTransferApprove,
	ERPTransferBatchApprove,
	ERPTransferBatchConfirm,
	ERPTransferBatchMark,
	ERPTransferBatchTransferred,
	ERPTransferCardInfoExportTask,
	ERPTransferCheck,
	ERPTransferList,
	ErpUserOrderHasExisted,
	GetEzsellerNewMessage,
	GetEzsellerNewMessageTmp,
	GetSupporterNewMessage,
	GetUserOrderShipment,
	InvoiceGeneratePackageNumber,
	InvoiceGet,
	SellerFeedback,
	SendFromEzbuySupporter,
	SendFromEzseller,
	SendFromEzsellerTmp,
	ShopBatchUpdateSkus,
	ShopExportSkus,
	SnapshootOfEzseller,
	SnapshootOfEzsellerTmp,
	SnapshootOfSupporter,
	UserAccountUpdatePassword,
	UserAlterPackageTrackInfo,
	UserAnnAndMailCount,
	UserAnnouncementGet,
	UserAnnouncementList,
	UserAnnouncementNonViewedCount,
	UserAnnouncementRead,
	UserBatchPackageDispatch,
	UserBillAppeal,
	UserBillList,
	UserBillOrderExportTask,
	UserBillOrderItemExportTask,
	UserBillOrderItemList,
	UserBillOrderItemListExport,
	UserBillOrderList,
	UserBillOrderListExport,
	UserBillTransferAdd,
	UserBillTransferInfo,
	UserDailyReportGet,
	UserExportTask,
	UserExportTaskList,
	UserGetProductAnalytics,
	UserGetProductSimpleInfo,
	UserGetShipmentTypes,
	UserImportEzbuyProducts,
	UserImportSubTaskList,
	UserImportSubTaskProductDetail,
	UserImportSubTaskProductUpdate,
	UserImportTaskAdd,
	UserImportTaskList,
	UserImportTaskRetry,
	UserMirrorProductLink,
	UserMirrorProductList,
	UserMirrorProductUnLink,
	UserNewImportTaskList,
	UserOrderCancel,
	UserOrderDetail,
	UserOrderDispatch,
	UserOrderDispatchImport,
	UserOrderDispatchImportTask,
	UserOrderDispatchNew,
	UserOrderDispatchNewImportTask,
	UserOrderHasExisted,
	UserOrderHasExistedTmp,
	UserOrderItemDispatch,
	UserOrderItemGroupExport,
	UserOrderItemGroupExportTask,
	UserOrderItemGroupList,
	UserOrderItemGroupNewExportTask,
	UserOrderItemList,
	UserOrderItemRemarkAdd,
	UserOrderItemReturnConfirm,
	UserOrderItemTrackUpdate,
	UserOrderList,
	UserOrderListExportTask,
	UserOrderListNew,
	UserOrderListNewExportTask,
	UserOrderRemarkAdd,
	UserOrderRemarkAddNew,
	UserOrderStockout,
	UserOrderStockoutTmp,
	UserOrderTrackDetailList,
	UserOrderTrackUpdate,
	UserOrderTrackUpdateNew,
	UserPackageDispatch,
	UserPackageList,
	UserPackageTrackInfoDispatchImportTask,
	UserPackingListExportTask,
	UserPickList,
	UserPickListExport,
	UserProductAnalyticsReportExportTask,
	UserProductBatchDelete,
	UserProductDetail,
	UserProductList,
	UserProductQuickUpdate,
	UserProductUpdate,
	UserProductsFromSource,
	UserSearchProductAnalytics,
	UserShopApprovalFormGet,
	UserShopApprovalOrganization,
	UserShopApprovalOriganizationUpsert,
	UserShopApprovalPersonal,
	UserShopApprovalPersonalUpsert,
	UserShopCreate,
	UserShopIndexDataGet,
	UserShopMailList,
	UserShopMailRead,
	UserShopSetEverSignIn,
	UserShopShutDown,
	UserShopStatistics,
	UserShopValidShopName,
	UserTransferAccountInfo,
	UserTransferAccountInfoUpdate,
	UserTransferAccountInfoUpdateCancel,
	UserUnCommitedProductDetail,
	UserUnCommitedProductUpdate,
	UserUploadProducts,
	UserUploadProductsExport,
	WarehouseBatchDispatchPackage,
	WarehouseBatchReceivePackage,
	WarehouseDispatchPackage,
	WarehouseExportInformationExport,
	WarehouseGetShipmentTypes,
	WarehousePackageList,
	WarehouseReceivePackage,
	WarehouseShipperList,
	WarehouseUserLogin,
	WarehouseUserRegister
};
