/**
 * This file is auto-generated by tgen
 * Don't change manually
 */
import webapi from "./webapi";




export interface TFixedBannerImage {
	key: string;
	name: string;
	linkAddress: string;
	picture: string;
	countryCode: string;
}
export interface TWebHomepageBanner {
	bannerType: number;
	picture: string;
	linkAddress?: string;
}
export interface TWebHomepageCampaign {
	picture: string;
	linkAddress?: string;
	name?: string;
}
export interface TWebHomepageCampaignText {
	name: string;
	linkAddress: string;
}
export interface TWebHomepageCategoryCollection {
	campaign: TWebHomepageCampaign;
	firstLevelCampaignText: TWebHomepageCampaignText;
	secondLevelCampaignTexts: TWebHomepageCampaignText[];
	thirdLevelCampaigns: TWebHomepageCampaign[];
}
export interface TWebHomepageProduct {
	id: number;
	name: string;
	url: string;
	price: number;
	image: string;
	originCode: string;
}
export interface TWebHomepagePromotion {
	topCategoryId: number;
	promotionBanner: TWebHomepageCampaign;
	products: TWebHomepageProduct[];
}


export function GetBannerList(countryCode: string): Promise<TWebHomepageBanner[]> {
	return webapi<TWebHomepageBanner[]>("WebHomepage.GetBannerList", { countryCode });
}

export function GetCategoryCollections(): Promise<TWebHomepageCategoryCollection[]> {
	return webapi<TWebHomepageCategoryCollection[]>("WebHomepage.GetCategoryCollections", {  });
}

export function GetFixedBannerImagesByKeys(keys: string[], countryCode: string): Promise<TFixedBannerImage[]> {
	return webapi<TFixedBannerImage[]>("WebHomepage.GetFixedBannerImagesByKeys", { keys, countryCode });
}

export function GetFixedBannerImagesByTypeId(typeId: number, countryCode: string): Promise<TFixedBannerImage[]> {
	return webapi<TFixedBannerImage[]>("WebHomepage.GetFixedBannerImagesByTypeId", { typeId, countryCode });
}

export function GetHomepageBanners(countryCode: string): Promise<TWebHomepageBanner[]> {
	return webapi<TWebHomepageBanner[]>("WebHomepage.GetHomepageBanners", { countryCode });
}

export function GetMenuItemByTopCategoryId(topCategoryId: number): Promise<TWebHomepagePromotion> {
	return webapi<TWebHomepagePromotion>("WebHomepage.GetMenuItemByTopCategoryId", { topCategoryId });
}

export function GetSellerProducts(originCode: string): Promise<TWebHomepageProduct[]> {
	return webapi<TWebHomepageProduct[]>("WebHomepage.GetSellerProducts", { originCode });
}



export default {
	GetBannerList,
	GetCategoryCollections,
	GetFixedBannerImagesByKeys,
	GetFixedBannerImagesByTypeId,
	GetHomepageBanners,
	GetMenuItemByTopCategoryId,
	GetSellerProducts,
};

