// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

/*
Package config is a generated protocol buffer package.

It is generated from these files:
	config.proto

It has these top-level messages:
	Basic
	BlockBasic
*/
package config

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 基本配置
type Basic struct {
	// 代码链接
	CodeLink string `protobuf:"bytes,1,opt,name=codeLink" json:"codeLink,omitempty"`
	// 板块
	BlockBasic []*BlockBasic `protobuf:"bytes,2,rep,name=blockBasic" json:"blockBasic,omitempty"`
}

func (m *Basic) Reset()                    { *m = Basic{} }
func (m *Basic) String() string            { return proto.CompactTextString(m) }
func (*Basic) ProtoMessage()               {}
func (*Basic) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Basic) GetCodeLink() string {
	if m != nil {
		return m.CodeLink
	}
	return ""
}

func (m *Basic) GetBlockBasic() []*BlockBasic {
	if m != nil {
		return m.BlockBasic
	}
	return nil
}

// 代码信息
type BlockBasic struct {
	// 交易所
	Exchange string `protobuf:"bytes,1,opt,name=exchange" json:"exchange,omitempty"`
	// 板块
	Block string `protobuf:"bytes,2,opt,name=block" json:"block,omitempty"`
	// 最小值
	Min int32 `protobuf:"varint,3,opt,name=min" json:"min,omitempty"`
	// 最大值
	Max int32 `protobuf:"varint,4,opt,name=max" json:"max,omitempty"`
}

func (m *BlockBasic) Reset()                    { *m = BlockBasic{} }
func (m *BlockBasic) String() string            { return proto.CompactTextString(m) }
func (*BlockBasic) ProtoMessage()               {}
func (*BlockBasic) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BlockBasic) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *BlockBasic) GetBlock() string {
	if m != nil {
		return m.Block
	}
	return ""
}

func (m *BlockBasic) GetMin() int32 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *BlockBasic) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func init() {
	proto.RegisterType((*Basic)(nil), "config.basic")
	proto.RegisterType((*BlockBasic)(nil), "config.blockBasic")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0x4b,
	0xcb, 0x4c, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0xc2, 0xb9, 0x58,
	0x93, 0x12, 0x8b, 0x33, 0x93, 0x85, 0xa4, 0xb8, 0x38, 0x92, 0xf3, 0x53, 0x52, 0x7d, 0x32, 0xf3,
	0xb2, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xe0, 0x7c, 0x21, 0x23, 0x2e, 0xae, 0xa4, 0x9c,
	0xfc, 0xe4, 0x6c, 0x27, 0x90, 0x4a, 0x09, 0x26, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x21, 0x3d, 0xa8,
	0x79, 0x08, 0x99, 0x20, 0x24, 0x55, 0x4a, 0x49, 0xc8, 0x7a, 0x40, 0xa6, 0xa7, 0x56, 0x24, 0x67,
	0x24, 0xe6, 0xa5, 0xa7, 0xc2, 0x4c, 0x87, 0xf1, 0x85, 0x44, 0xb8, 0x58, 0xc1, 0x2a, 0x25, 0x98,
	0xc0, 0x12, 0x10, 0x8e, 0x90, 0x00, 0x17, 0x73, 0x6e, 0x66, 0x9e, 0x04, 0xb3, 0x02, 0xa3, 0x06,
	0x6b, 0x10, 0x88, 0x09, 0x16, 0x49, 0xac, 0x90, 0x60, 0x81, 0x8a, 0x24, 0x56, 0x24, 0xb1, 0x81,
	0xfd, 0x62, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x1a, 0xc7, 0xfd, 0x8a, 0xdb, 0x00, 0x00, 0x00,
}
