/**
 * This file is auto-generated by protobufgen
 * Don't change manually
 */

import webapi from "../webapi";

export interface Result {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	code: number;
	message: string;
}

export interface AccountLoginReq {
	username: string;
	password: string;
	captcha: string;
}

export interface AccountLoginResp {
	result: Result;
}

export function GAccountSigin(payload: Partial<AccountLoginReq>) {
	return webapi<AccountLoginResp>("account.GAccount/GAccountSigin", payload);
}

export default {
	GAccountSigin
};
