/**
 * This file is auto-generated by protobufgen
 * Don't change manually
 */

import { ActInfo as ActivityActInfo } from "../activity/activity";
import { Empty as CommonEmpty } from "../common/empty";
import webapi from "../webapi";

export enum BillType {
	BillTypeUnknown = "BillTypeUnknown",
	Original = "Original",
	Modified = "Modified"
}

export enum BillStatus {
	Pending = "Pending",
	Paid = "Paid",
	Cancelled = "Cancelled"
}

export enum BalanceType {
	Unknow_Balance = "Unknow_Balance",
	InternalExpress = "InternalExpress",
	Qty = "Qty",
	UnitPrice = "UnitPrice",
	Other = "Other"
}

export enum OptionStatus {
	Disable = "Disable",
	Optional = "Optional",
	Selected = "Selected"
}

export enum ServiceType {
	Invalid = "Invalid",
	Buyforme = "Buyforme",
	Shipforme = "Shipforme",
	Prime = "Prime",
	Ezbuy = "Ezbuy"
}

export enum FeeType {
	Unknown = "Unknown",
	SubTotal = "SubTotal",
	SubPrice = "SubPrice",
	ShippingFee = "ShippingFee",
	HandlingFee = "HandlingFee",
	ExpressFee = "ExpressFee",
	AgentFee = "AgentFee",
	Insurance = "Insurance",
	Gst = "Gst",
	InternalExpressFee = "InternalExpressFee",
	ProductFee = "ProductFee",
	Discount = "Discount",
	DiscountAgent = "DiscountAgent",
	DiscountShipping = "DiscountShipping",
	DiscountCoupon = "DiscountCoupon",
	DiscountCredit = "DiscountCredit",
	DiscountCutOffVoucher = "DiscountCutOffVoucher",
	DiscountCashOffVoucher = "DiscountCashOffVoucher",
	DiscountPrimeTrialVoucher = "DiscountPrimeTrialVoucher",
	DiscountFreeAgentFeeVoucher = "DiscountFreeAgentFeeVoucher",
	DiscountProduct = "DiscountProduct",
	DiscountShippingVoucher = "DiscountShippingVoucher"
}

export enum BillCategory {
	Unknown_Category = "Unknown_Category",
	TOTAL_PRODUCT_PRICE = "TOTAL_PRODUCT_PRICE",
	EXPRESS_FEE = "EXPRESS_FEE",
	AGENT_FEE = "AGENT_FEE",
	HANDLING_FEE = "HANDLING_FEE",
	SHIPPING_FEE = "SHIPPING_FEE",
	INSURE_FEE = "INSURE_FEE",
	GST = "GST",
	DOMESTIC_SHIPPING_FEE = "DOMESTIC_SHIPPING_FEE",
	TOTAL_PRODUCT_DISCOUNT = "TOTAL_PRODUCT_DISCOUNT",
	EXPRESS_DISCOUNT = "EXPRESS_DISCOUNT",
	AGENT_DISCOUNT = "AGENT_DISCOUNT",
	HANDLING_DISCOUNT = "HANDLING_DISCOUNT",
	SHIPPING_DISCOUNT = "SHIPPING_DISCOUNT",
	INSURE_DISCOUNT = "INSURE_DISCOUNT",
	TOTAL_PRICE_DISCOUNT = "TOTAL_PRICE_DISCOUNT",
	CREDIT_DISCOUNT = "CREDIT_DISCOUNT",
	MANUAL_DISCOUNT = "MANUAL_DISCOUNT",
	ORDER_FINAL_TOTAL = "ORDER_FINAL_TOTAL",
	FINAL_TOTAL = "FINAL_TOTAL"
}

export enum ResultCode {
	Success = "Success",
	PaySuccess = "PaySuccess",
	PayFailed = "PayFailed",
	CheckoutAutoPaySuccess = "CheckoutAutoPaySuccess",
	CancelOrderSuccess = "CancelOrderSuccess",
	CancelOrderItemSuccess = "CancelOrderItemSuccess",
	CheckoutAutoPayFailed = "CheckoutAutoPayFailed",
	CancelOrderFailed = "CancelOrderFailed",
	SetOrderItemsStatusFinishFailed = "SetOrderItemsStatusFinishFailed",
	SetOrderItemsStatusFinishNotFind = "SetOrderItemsStatusFinishNotFind",
	HitOrderSkuLimitCount = "HitOrderSkuLimitCount"
}

export enum DiscountType {
	InvalidType = "InvalidType",
	AgentFeeDiscount = "AgentFeeDiscount",
	ShippingFeeDiscount = "ShippingFeeDiscount"
}

export enum OrderItemOperType {
	DEFAULT_OPER_TYPE = "DEFAULT_OPER_TYPE",
	CANCEL_TAOBAO_UNPAID = "CANCEL_TAOBAO_UNPAID",
	CANCEL_TAOBAO_PAID_REFUND = "CANCEL_TAOBAO_PAID_REFUND",
	CANCEL_TAOBAO_PAID_REFUND_RETURN = "CANCEL_TAOBAO_PAID_REFUND_RETURN",
	CANCEL_TAOBAO_PAID_UNREFUND = "CANCEL_TAOBAO_PAID_UNREFUND",
	CANCEL_TAOBAO_CLOSE_DEAL = "CANCEL_TAOBAO_CLOSE_DEAL",
	CANCEL_REORDERED = "CANCEL_REORDERED",
	CANCEL_OTHER = "CANCEL_OTHER",
	MODIFY_CHARGEWEIGHT = "MODIFY_CHARGEWEIGHT",
	MODIFY_SHIPMENTTYPE = "MODIFY_SHIPMENTTYPE",
	MODIFY_OFFSET_CONFIRM = "MODIFY_OFFSET_CONFIRM",
	MODIFY_OFFSET_CANCEL = "MODIFY_OFFSET_CANCEL",
	EZSELLER_OPER_TIMEOUT = "EZSELLER_OPER_TIMEOUT",
	EZSELLER_OPER_MISSING = "EZSELLER_OPER_MISSING",
	EZSELLER_OPER_BAD_PRODUCT = "EZSELLER_OPER_BAD_PRODUCT",
	EZSELLER_OPER_TRANSPORT_MISSING = "EZSELLER_OPER_TRANSPORT_MISSING",
	EZSELLER_OPER_TRANSPORT_OTHER = "EZSELLER_OPER_TRANSPORT_OTHER",
	EZSELLER_OPER_CUSTOMER = "EZSELLER_OPER_CUSTOMER",
	EZSELLER_OPER_EMBARGO = "EZSELLER_OPER_EMBARGO"
}

export interface RpcReOrderViaOrderIdItemIdsOrOffsetBillIdReq {
	/**
	 * @pattern ^\d+$
	 */
	RegionId: string;
	/**
	 * @pattern ^\d+$
	 */
	OffsetBillId: string[];
	CancelOrderIdItemIds: OrderIdItemId[];
	ItemIdRemarks: ItemIdRemark[];
}

export interface ItemIdRemark {
	/**
	 * @pattern ^\d+$
	 */
	ItemId: string;
	Remark: string;
}

export interface RpcReOrderViaOrderIdItemIdsOrOffsetBillIdResp {
	Result: Result;
}

export interface CancelOrderBillResp {
	Result: Result;
}

export interface CancelOrderBillReq {
	/**
	 * @pattern ^\d+$
	 */
	BillId: string;
	Client: string;
	Catalog: string;
}

export interface PayOrderBillResp {
	Result: Result;
}

export interface PayOrderBillReq {
	/**
	 * @pattern ^\d+$
	 */
	BillId: string;
	Client: string;
	Catalog: string;
	PayMethod: string;
}

export interface RpcPayCancelBillReq {
	Catalog: string;
	/**
	 * @pattern ^\d+$
	 */
	CustomerId: string;
	/**
	 * @pattern ^\d+$
	 */
	BillId: string;
	/**
	 * @pattern ^\d+$
	 */
	Amount: string;
	CancelRemark: string;
	Operator: string;
	OldOrderNumber: string;
}

export interface RpcPayCancelBillResp {
	Result: Result;
}

export interface RpcSetOrderItemsStatusFinishReq {
	Catalog: string;
	OrderIdItemIds: OrderIdItemId[];
}

export interface RpcSetOrderItemsStatusFinishResp {
	Result: Result;
}

export interface RpcOrderBackToCartReq {
	Catalog: string;
	/**
	 * @pattern ^\d+$
	 */
	OrderIds: string[];
}

export interface RpcOrderBackToCartResp {
	Result: Result;
	FaildMsg: string[];
}

export interface RpcGetOrderItemActivityAmountReq {
	Catalog: string;
	OrderIdItemIds: OrderIdItemId[];
}

export interface RpcGetOrderItemActivityAmountResp {
	Result: Result;
	OrderItemActivityAmounts: OrderItemActivityAmount[];
}

export interface OrderItemActivityAmount {
	/**
	 * @pattern ^\d+$
	 */
	OrderId: string;
	/**
	 * @pattern ^\d+$
	 */
	OrderItemId: string;
	/**
	 * @pattern ^\d+$
	 */
	TotalAmount: string;
	FeeInfos: FeeInfo[];
	ActivityIds: string[];
	/**
	 * @minimum 0
	 */
	CurrencyExchange: number;
}

export interface OrderIdItemId {
	/**
	 * @pattern ^\d+$
	 */
	OrderId: string;
	/**
	 * @pattern ^\d+$
	 */
	OrderItemIds: string[];
}

export interface RpcModifyChargeWeightReq {
	Catalog: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	OldOrderId: number;
	/**
	 * @pattern ^\d+$
	 */
	NewOrderId: string;
	/**
	 * @pattern ^\d+$
	 */
	NewOrderItemId: string;
	/**
	 * @pattern ^\d+$
	 */
	ChargeWeight: string;
	/**
	 * @pattern ^\d+$
	 */
	UserId: string;
	/**
	 * @pattern ^\d+$
	 */
	StockInDate: string;
}

export interface RpcModifyChargeWeightResp {
	Result: Result;
}

export interface RpcGetBillsReq {
	Catalog: string;
	/**
	 * @pattern ^\d+$
	 */
	NewBillIds: string[];
}

export interface RpcGetBillsResp {
	Result: Result;
	NewBills: NewBill[];
}

export interface NewBill {
	/**
	 * @pattern ^\d+$
	 */
	BillId: string;
	BillType: BillType;
	/**
	 * @pattern ^\d+$
	 */
	OrderId: string;
	/**
	 * @pattern ^\d+$
	 */
	CustomerId: string;
	JournalNumber: string;
	BillStatus: BillStatus;
	CurrencyCode: string;
	/**
	 * @pattern ^\d+$
	 */
	BillAmount: string;
	/**
	 * @pattern ^\d+$
	 */
	CreateDate: string;
	/**
	 * @pattern ^\d+$
	 */
	PayDate: string;
	/**
	 * @pattern ^\d+$
	 */
	CompleteDate: string;
}

export interface RpcGetOrderItemsOriginTotalAmountResp {
	Result: Result;
	OrderItemsOriginTotalAmounts: OrderItemsOriginTotalAmount[];
}

export interface RpcGetOrderItemsOriginTotalAmountReq {
	Catalog: string;
	OldOrderIds: number[];
}

export interface OrderItemsOriginTotalAmount {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	OldOrderId: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	OldOrderItemId: number;
	/**
	 * @pattern ^\d+$
	 */
	TotalAmount: string;
	FeeInfos: FeeInfo[];
}

export interface RpcGetOffsetsResp {
	Result: Result;
	OffsetInfos: OffsetInfo[];
}

export interface RpcGetOffsetsReq {
	Catalog: string;
	/**
	 * @pattern ^\d+$
	 */
	OffsetIds: string[];
}

export interface OffsetInfo {
	/**
	 * @pattern ^\d+$
	 */
	OffsetId: string;
	IsOffsetPay: boolean;
	IsOffsetCancelled: boolean;
	IsSkuCancelled: boolean;
	/**
	 * @pattern ^\d+$
	 */
	UnitPrice: string;
	/**
	 * @pattern ^\d+$
	 */
	DomesticShippingFee: string;
	/**
	 * @pattern ^\d+$
	 */
	Qty: string;
	/**
	 * @pattern ^\d+$
	 */
	HandlingFee: string;
	/**
	 * @pattern ^\d+$
	 */
	Gst: string;
	/**
	 * @pattern ^\d+$
	 */
	TotalProductPrice: string;
	/**
	 * @pattern ^\d+$
	 */
	OffsetBillAmount: string;
}

export interface RpcModifyWarehouseReq {
	Catalog: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	UserId: number;
	OldOrderIds: number[];
	ServiceType: ServiceType;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	WarehouseId: number;
	Remark: string;
	/**
	 * @pattern ^\d+$
	 */
	MinOrderItemStatus: string;
}

export interface RpcModifyWarehouseResp {
	Result: Result;
}

export interface RpcModifyShipmentTypeReq {
	Catalog: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	UserId: number;
	OldOrderIds: number[];
	ServiceType: ServiceType;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	ShipmentTypeId: number;
	Remark: string;
	/**
	 * @pattern ^\d+$
	 */
	MinOrderItemStatus: string;
}

export interface RpcModifyShipmentTypeResp {
	Result: Result;
}

export interface RpcPayOrderBalanceReq {
	Catalog: string;
	Client: string;
	/**
	 * @pattern ^\d+$
	 */
	CustomerId: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	OldOrderId: number;
	/**
	 * @pattern ^\d+$
	 */
	NewOffsetId: string;
	Operator: string;
	IsAllowOwe: boolean;
}

export interface RpcPayOrderBalanceResp {
	Result: Result;
}

export interface RpcCancelOrderBalanceReq {
	Catalog: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	UserId: number;
	/**
	 * @pattern ^\d+$
	 */
	NewOffsetId: string;
}

export interface RpcCancelOrderBalanceResp {
	Result: Result;
}

export interface RpcAddOrderBalanceReq {
	Catalog: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	UserId: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	OldOrderId: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	OldOrderItemId: number;
	/**
	 * @pattern ^\d+$
	 */
	NewOrderId: string;
	/**
	 * @pattern ^\d+$
	 */
	NewOrderItemId: string;
	AddBalanceInfos: AddBalanceInfo[];
	/**
	 * @pattern ^\d+$
	 */
	MinOrderItemStatus: string;
	Operator: string;
	IsPreCalc: boolean;
	IdempotentKey: string;
}

export interface AddBalanceInfo {
	BalanceType: BalanceType;
	/**
	 * @pattern ^\d+$
	 */
	Balance: string;
	Remark: string;
	/**
	 * @pattern ^\d+$
	 */
	Fee: string;
	/**
	 * @pattern ^\d+$
	 */
	RegionFee: string;
	/**
	 * @minimum 0
	 */
	CurrencyExchange: number;
	/**
	 * @pattern ^\d+$
	 */
	RefundFee: string;
	/**
	 * @pattern ^\d+$
	 */
	ReplenishFee: string;
	PriceSymbol: string;
	Reason: string;
}

export interface FeeInfo {
	BillCategory: BillCategory;
	/**
	 * @pattern ^\d+$
	 */
	Fee: string;
	FeeTitle: string;
	PriceSymbol: string;
	FeeTitleEn: string;
}

export interface RpcAddOrderBalanceResp {
	Result: Result;
	/**
	 * @pattern ^\d+$
	 */
	TotalAmount: string;
	/**
	 * @pattern ^\d+$
	 */
	NewOffsetId: string;
	AddBalanceInfos: AddBalanceInfo[];
}

export interface RpcGetOrderBalanceReq {
	Catalog: string;
	OldOrderNumber: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	OldOrderId: number;
}

export interface RpcGetOrderBalanceResp {
	Result: Result;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	OldOrderId: number;
	IsAuthorizeBalance: boolean;
	AuthorizeForBalance: string;
	OrderBalanceHistories: OrderBalanceHistory[];
	NewOrderItemInfos: NewOrderItemInfo[];
	BalanceRemarkList: string[];
	InternalExpressRemarkList: string[];
	OtherRemarkList: string[];
	PriceSymbol: string;
	BalanceReasonList: string[];
}

export interface OrderBalanceHistory {
	TypeName: string;
	/**
	 * @pattern ^\d+$
	 */
	Amount: string;
	/**
	 * @pattern ^\d+$
	 */
	BalanceDate: string;
	Status: string;
	Remark: string;
	AllowCancel: boolean;
	/**
	 * @pattern ^\d+$
	 */
	NewOffsetId: string;
}

export interface RpcCancelOrderReq {
	Catalog: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	OldOrderId: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	UserId: number;
	/**
	 * @pattern ^\d+$
	 */
	ManualFee: string;
	CancelRemark: string;
	CancelReason: string;
	/**
	 * @pattern ^\d+$
	 */
	MinOrderItemStatus: string;
	Operator: string;
	/**
	 * @pattern ^\d+$
	 */
	CustomerId: string;
	IdempotentKey: string;
}

export interface RpcCancelOrderResp {
	Result: Result;
}

export interface RpcGetCancelOrderReq {
	Catalog: string;
	OldOrderNumber: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	OldOrderId: number;
}

export interface RpcGetCancelOrderResp {
	Result: Result;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	OldOrderId: number;
	OrderNumber: string;
	ServiceTypeName: string;
	ShipmentTypeName: string;
	ShipmentPerFee: string;
	ProductName: string;
	/**
	 * @pattern ^\d+$
	 */
	OrderChargeWeight: string;
	/**
	 * @pattern ^\d+$
	 */
	PaymentChargeWeight: string;
	FeeInfos: FeeInfo[];
	CancelRemarkList: string[];
	CancelReasonList: string[];
	IsEzseller: boolean;
	OrderIdItemId: OrderIdItemId;
}

export interface NewOrderItemInfo {
	/**
	 * @pattern ^\d+$
	 */
	NewOrderId: string;
	/**
	 * @pattern ^\d+$
	 */
	NewOrderItemId: string;
	SkuName: string;
	/**
	 * @pattern ^\d+$
	 */
	InternalExpressFee: string;
	/**
	 * @pattern ^\d+$
	 */
	Qty: string;
	IsDisable: boolean;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	OldOrderItemId: number;
	IsEzseller: boolean;
}

export interface RpcCancelPaymentReq {
	Catalog: string;
	Client: string;
	/**
	 * @pattern ^\d+$
	 */
	CustomerId: string;
	/**
	 * @pattern ^\d+$
	 */
	NewBillIds: string[];
	PaymentBillIds: number[];
	IsCheckBeforeCancel: boolean;
}

export interface RpcCancelPaymentResp {
	result: Result;
	LeftPaymentBillIds: number[];
	MissingPaymentbillIds: number[];
	FaildPaymentBillIds: number[];
}

export interface RpcModifyOrderItemsInfoReq {
	Catalog: string;
	/**
	 * @pattern ^\d+$
	 */
	CustomerId: string;
	Client: string;
	OrderItemInfos: OrderItemInfo[];
}

export interface RpcModifyOrderItemsInfoResp {
	result: Result;
	LeftOrderItemInfos: OrderItemInfo[];
	FailedOrderItemInfos: OrderItemInfo[];
}

export interface OrderItemInfo {
	/**
	 * @pattern ^\d+$
	 */
	NewOrderId: string;
	/**
	 * @pattern ^\d+$
	 */
	NewOrderItemId: string;
	/**
	 * @pattern ^\d+$
	 */
	NewBillId: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	OldOrderId: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	OldOrderItemId: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	PaymentBillId: number;
	/**
	 * @pattern ^\d+$
	 */
	WarehouseId: string;
	/**
	 * @pattern ^\d+$
	 */
	ShipmentTypeId: string;
	Remark: string;
	IsInsured: boolean;
}

export interface RpcPayNewBillAfterChekcoutReq {
	Catalog: string;
	Client: string;
	/**
	 * @pattern ^\d+$
	 */
	CustomerId: string;
	/**
	 * @pattern ^\d+$
	 */
	NewBillIds: string[];
	PaymentBillIds: number[];
	Paymethod: string;
	IsCheckBeforePay: boolean;
}

export interface RpcPayNewBillAfterChekcoutResp {
	result: Result;
	LeftPaymentBillIds: number[];
	MissingPaymentbillIds: number[];
	FaildPaymentBillIds: number[];
}

export interface RpcCalcCreateOrdersReq {
	Catalog: string;
	Client: string;
	/**
	 * @pattern ^\d+$
	 */
	CustomerId: string;
	Dest: string;
	ServiceType: ServiceType;
	SkuItems: SkuItem[];
	CouponCode: string;
	/**
	 * @pattern ^\d+$
	 */
	Credits: string;
	IsInsurance: boolean;
	VoucherItems: VoucherItem[];
	/**
	 * @pattern ^\d+$
	 */
	ExpressFee: string;
	ExpressInfo: ExpressInfo;
	IsPayLater: boolean;
	IsAuthorizeBalance: boolean;
}

export interface RpcCalcCreateOrdersResp {
	result: Result;
	/**
	 * @pattern ^\d+$
	 */
	OrderIds: string[];
	OldPaymentNumbers: string[];
	/**
	 * @pattern ^\d+$
	 */
	NewBillId: string;
	/**
	 * @pattern ^\d+$
	 */
	Amount: string;
	IsPaid: boolean;
}

export interface ExpressInfo {
	/**
	 * @pattern ^\d+$
	 */
	DeliveryTypeId: string;
	/**
	 * @pattern ^\d+$
	 */
	StationTypeId: string;
	/**
	 * @pattern ^\d+$
	 */
	DeliveryStationId: string;
	/**
	 * @pattern ^\d+$
	 */
	PickupPeriodId: string;
	/**
	 * @pattern ^\d+$
	 */
	CustomerAddressId: string;
	LocalDeliveryMethod: string;
	StationName: string;
	ShipToPhone: string;
	ShipToName: string;
	ShipToZip: string;
	Address: string;
	ShipToState: string;
	PeriodName: string;
}

export interface RpcCalcBillReq {
	Catalog: string;
	Client: string;
	/**
	 * @pattern ^\d+$
	 */
	CustomerId: string;
	Dest: string;
	ServiceType: ServiceType;
	SkuItems: SkuItem[];
	CouponCode: string;
	/**
	 * @pattern ^\d+$
	 */
	Credits: string;
	IsInsurance: boolean;
	VoucherItems: VoucherItem[];
	/**
	 * @pattern ^\d+$
	 */
	ExpressFee: string;
}

export interface RpcCalcBillResp {
	PayBill: PayBill;
}

export interface PayBill {
	IsCouponValid: boolean;
	OrderBills: OrderBill[];
	VoucherItems: VoucherItem[];
}

export interface OrderBill {
	Region: string;
	SkuItems: SkuItem[];
	/**
	 * @pattern ^\d+$
	 */
	AgentFee: string;
	/**
	 * @pattern ^\d+$
	 */
	ShippingFee: string;
	/**
	 * @pattern ^\d+$
	 */
	InsuranceFee: string;
	/**
	 * @pattern ^\d+$
	 */
	ExpressFee: string;
}

export interface SkuItem {
	ServiceType: ServiceType;
	/**
	 * @pattern ^\d+$
	 */
	RegionId: string;
	/**
	 * @pattern ^\d+$
	 */
	Gpid: string;
	SkuId: string;
	/**
	 * @pattern ^\d+$
	 */
	Qty: string;
	Url: string;
	/**
	 * @pattern ^\d+$
	 */
	ChargeWeight: string;
	/**
	 * @pattern ^\d+$
	 */
	UnitPrice: string;
	/**
	 * @pattern ^\d+$
	 */
	InternalExpressFee: string;
	/**
	 * @minimum 0
	 */
	Exchange: number;
	/**
	 * @pattern ^\d+$
	 */
	WarehouseId: string;
	/**
	 * @pattern ^\d+$
	 */
	ShipmentTypeId: string;
	/**
	 * @pattern ^\d+$
	 */
	DiscountTypeId: string;
	/**
	 * @pattern ^\d+$
	 */
	GstFee: string;
	/**
	 * @pattern ^\d+$
	 */
	HandlingFee: string;
	ItemDiscounts: ItemDiscount[];
	/**
	 * @pattern ^\d+$
	 */
	SubTotal: string;
	MongoCartId: string;
	/**
	 * @pattern ^\d+$
	 */
	RegionPrice: string;
	Remark: string;
	SkuImg: string;
	/**
	 * @pattern ^\d+$
	 */
	HandlingFeeRatio: string;
	IsInsured: boolean;
	IsPresale: boolean;
	/**
	 * @pattern ^\d+$
	 */
	EtaDate: string;
	/**
	 * @pattern ^\d+$
	 */
	EtaStartDate: string;
	/**
	 * @pattern ^\d+$
	 */
	EtaEndDate: string;
	/**
	 * @pattern ^\d+$
	 */
	RegionInternalExpressFee: string;
	IsFlashSale: boolean;
	IsFriendsDeal: boolean;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	ShipmentId: number;
	IsFriendsDealFree: boolean;
	/**
	 * @pattern ^\d+$
	 */
	GpidVersion: string;
	DiscountTypeDesc: string;
	FlashsalesSettingId: string;
}

export interface ItemDiscount {
	/**
	 * @pattern ^\d+$
	 */
	Fee: string;
	FeeType: FeeType;
	ActInfo: ActivityActInfo;
	Voucher: VoucherItem;
	/**
	 * @pattern ^\d+$
	 */
	DiscountTypeId: string;
	CouponCode: string;
	/**
	 * @pattern ^\d+$
	 */
	Credits: string;
	RecordZero: boolean;
	DiscountTypeDesc: string;
}

export interface VoucherItem {
	/**
	 * @pattern ^\d+$
	 */
	VoucherId: string;
	/**
	 * @pattern ^\d+$
	 */
	VoucherTypeId: string;
	/**
	 * @pattern ^\d+$
	 */
	Category: string;
	/**
	 * @pattern ^\d+$
	 */
	FullAmount: string;
	/**
	 * @pattern ^\d+$
	 */
	CutAmount: string;
	OptionStatus: OptionStatus;
	Name: string;
	RuleId: string;
}

export interface PingReq {
	msg: string;
}

export interface PingResp {
	msg: string;
}

export interface AddMultiOrderReq {
	/**
	 * @pattern ^\d+$
	 */
	customerId: string;
	/**
	 * @pattern ^\d+$
	 */
	serviceTypeId: string;
	catalogCode: string;
	destCode: string;
	order: OrderInfo[];
}

export interface AddMultiOrderResp {
	result: Result;
	info: OrderResultInfo[];
}

export interface Result {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	code: number;
	message: string;
}

export interface OrderFee {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	type: number;
	/**
	 * @pattern ^\d+$
	 */
	balance: string;
	remark: string;
}

export interface OrderItem {
	/**
	 * @pattern ^\d+$
	 */
	id: string;
	/**
	 * @pattern ^\d+$
	 */
	gpid: string;
	skuId: string;
	remark: string;
	/**
	 * @pattern ^\d+$
	 */
	qty: string;
	/**
	 * @pattern ^\d+$
	 */
	unitPrice: string;
	/**
	 * @pattern ^\d+$
	 */
	discountId: string;
	/**
	 * @pattern ^\d+$
	 */
	totalPriceDiscount: string;
	/**
	 * @pattern ^\d+$
	 */
	totalProductPriceDiscount: string;
	/**
	 * @pattern ^\d+$
	 */
	shippingFeeDiscount: string;
	/**
	 * @pattern ^\d+$
	 */
	handlingFeeDiscount: string;
	/**
	 * @pattern ^\d+$
	 */
	expressFeeDiscount: string;
	/**
	 * @pattern ^\d+$
	 */
	agentFeeDiscount: string;
	/**
	 * @pattern ^\d+$
	 */
	insureFeeDiscount: string;
	/**
	 * @pattern ^\d+$
	 */
	gstDiscount: string;
	/**
	 * @pattern ^\d+$
	 */
	totalProductPrice: string;
	/**
	 * @pattern ^\d+$
	 */
	handlingFeeRatio: string;
	/**
	 * @pattern ^\d+$
	 */
	shipmentFee: string;
	/**
	 * @minimum 0
	 */
	currencyExchange: number;
	url: string;
	/**
	 * @pattern ^\d+$
	 */
	handlingFee: string;
	/**
	 * @pattern ^\d+$
	 */
	shipment_type_id: string;
	warehouse_code: string;
	/**
	 * @pattern ^\d+$
	 */
	gst: string;
	insured: boolean;
	/**
	 * @pattern ^\d+$
	 */
	discount: string;
	/**
	 * @pattern ^\d+$
	 */
	purchaseSourceId: string;
	alternativeColor: string;
	isFlashSales: boolean;
	refId: string;
	/**
	 * @pattern ^\d+$
	 */
	discountTypeIds: string[];
	isPreSale: boolean;
	skuImg: string;
	mongoCartId: string;
}

export interface OrderInfo {
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	shipmentTypeId: number;
	/**
	 * @pattern ^\d+$
	 */
	prosourceRegionId: string;
	remark: string;
	/**
	 * @pattern ^\d+$
	 */
	etaDate: string;
	/**
	 * @pattern ^\d+$
	 */
	etaStartDate: string;
	/**
	 * @pattern ^\d+$
	 */
	etaEndDate: string;
	/**
	 * @pattern ^\d+$
	 */
	orderDate: string;
	/**
	 * @pattern ^\d+$
	 */
	totalPrice: string;
	/**
	 * @pattern ^\d+$
	 */
	totalProductPrice: string;
	exmsg: OrderExMsg;
	payment: PaymentInfo;
	shipment: ShipmentInfo;
	feeList: OrderFee[];
	itemList: OrderItem[];
}

export interface PackageResultInfo {
	MsPackageNumber: string;
	MsOrderNumbers: string[];
}

export interface OrderExMsg {
	authorizeForBalance: boolean;
	originCode: string;
	Platform: string;
}

export interface PaymentInfo {
	/**
	 * @pattern ^\d+$
	 */
	Total: string;
	/**
	 * @pattern ^\d+$
	 */
	ActualPay: string;
	CreditCardCouponCode: string;
	/**
	 * @pattern ^\d+$
	 */
	Coupon: string;
	/**
	 * @pattern ^\d+$
	 */
	CreditCardShipmentDiscount: string;
	/**
	 * @pattern ^\d+$
	 */
	Voucher: string;
	VoucherRebates: PaymentDiscountInfo[];
	VoucherRedpackets: PaymentDiscountInfo[];
	VoucherFreeAgentFees: PaymentDiscountInfo[];
	ShipmentDiscounts: PaymentDiscountInfo[];
	AgentDiscounts: PaymentDiscountInfo[];
	IsDeferPay: boolean;
	/**
	 * @pattern ^\d+$
	 */
	CreditValue: string;
	/**
	 * @pattern ^\d+$
	 */
	PromotionCouponId: string;
	/**
	 * @pattern ^\d+$
	 */
	VoucherIds: string[];
}

export interface ShipmentInfo {
	/**
	 * @pattern ^\d+$
	 */
	CustomerAddressId: string;
	LocalDeliveryMethod: string;
	StationName: string;
	/**
	 * @pattern ^\d+$
	 */
	DeliveryDate: string;
	PeriodName: string;
	ShipToPhone: string;
	ShipToName: string;
	ShipToZip: string;
	/**
	 * @pattern ^\d+$
	 */
	DeliveryDistrictTypeId: string;
	/**
	 * @pattern ^\d+$
	 */
	SelfStationId: string;
	/**
	 * @pattern ^\d+$
	 */
	NeighbourhoodStationItemId: string;
	/**
	 * @pattern ^\d+$
	 */
	MrtStationItemId: string;
	ShipToAddress1: string;
	ShipToState: string;
	LicenseNumber: string;
	UserShipmentDelivery: UserShipmentDelivery;
}

export interface PaymentDiscountInfo {
	discountName: string;
	altDiscountName: string;
	/**
	 * @pattern ^\d+$
	 */
	discountFee: string;
}

export interface UserShipmentDelivery {
	/**
	 * @pattern ^\d+$
	 */
	DeliveryTypeId: string;
	/**
	 * @pattern ^\d+$
	 */
	StationTypeId: string;
	/**
	 * @pattern ^\d+$
	 */
	DeliveryStationId: string;
	/**
	 * @pattern ^\d+$
	 */
	PickupPeriodId: string;
}

export interface BasketOrderMapping {
	/**
	 * @pattern ^\d+$
	 */
	Gpid: string;
	/**
	 * @pattern ^\d+$
	 */
	OrderId: string;
	/**
	 * @pattern ^\d+$
	 */
	SkuId: string;
}

export interface OrderResultInfo {
	/**
	 * @pattern ^\d+$
	 */
	orderId: string;
	MsPaymentNumber: string;
	MsPackageInfos: PackageResultInfo[];
	MsAgentOrderNumbers: string[];
	BasketOrderMappings: BasketOrderMapping[];
}

export interface UserGetLastOrdersReq {
	catalog: string;
	/**
	 * @pattern ^\d+$
	 */
	customerId: string;
	/**
	 * @pattern ^\d+$
	 */
	endTime: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	limit: number;
}

export interface UserGetLastOrdersResp {
	result: Result;
	userOrders: UserOrderInfo[];
}

export interface RpcGetOrdersViaDurationReq {
	catalog: string;
	/**
	 * @pattern ^\d+$
	 */
	startTime: string;
	/**
	 * @pattern ^\d+$
	 */
	endTime: string;
	/**
	 * @pattern ^\d+$
	 */
	limit: string;
	/**
	 * @pattern ^\d+$
	 */
	offset: string;
}

export interface RpcGetOrdersViaDurationResp {
	result: Result;
	userOrders: UserOrderInfo[];
}

export interface UserOrderInfo {
	/**
	 * @pattern ^\d+$
	 */
	orderId: string;
	/**
	 * @pattern ^\d+$
	 */
	gpid: string;
	/**
	 * @pattern ^\d+$
	 */
	qty: string;
	/**
	 * @pattern ^\d+$
	 */
	orderDate: string;
	serviceType: ServiceType;
}

export interface RpcGetOrderCouponRecordReq {
	/**
	 * @pattern ^\d+$
	 */
	OrderId: string;
	CouponCode: string;
	/**
	 * @pattern ^\d+$
	 */
	CustomerId: string;
	IsUsed: boolean;
	Catalog: string;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	limit: number;
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	offset: number;
}

export interface RpcGetOrderCouponRecordResp {
	data: CouponRecord[];
	/**
	 * @minimum 0
	 * @TJS-type integer
	 */
	count: number;
}

export interface CouponRecord {
	/**
	 * @pattern ^\d+$
	 */
	OrderId: string;
	CouponCode: string;
	/**
	 * @pattern ^\d+$
	 */
	CustomerId: string;
	IsUsed: boolean;
	/**
	 * @pattern ^\d+$
	 */
	UseDate: string;
}

export interface RpcCreateOrderForUserSubmitBuy4MeReq {
	Catalog: string;
	Client: string;
	/**
	 * @pattern ^\d+$
	 */
	CustomerId: string;
	Dest: string;
	ServiceType: ServiceType;
	SkuItems: B4mSkuItem[];
	CouponCode: string;
	/**
	 * @pattern ^\d+$
	 */
	Credits: string;
	IsInsurance: boolean;
	VoucherItems: VoucherItem[];
	/**
	 * @pattern ^\d+$
	 */
	ExpressFee: string;
	ExpressInfo: ExpressInfo;
	IsPayLater: boolean;
	IsAuthorizeBalance: boolean;
	shipmentTypeCode: string;
}

export interface RpcCreateOrderForUserSubmitBuy4MeResp {
	result: Result;
	/**
	 * @pattern ^\d+$
	 */
	OrderId: string;
	OldPaymentNumbers: string[];
	/**
	 * @pattern ^\d+$
	 */
	NewBillId: string;
}

export interface RpcCalcBillForUserSubmitBuy4MeReq {
	Catalog: string;
	Client: string;
	/**
	 * @pattern ^\d+$
	 */
	CustomerId: string;
	Dest: string;
	ServiceType: ServiceType;
	SkuItems: B4mSkuItem[];
	CouponCode: string;
	/**
	 * @pattern ^\d+$
	 */
	Credits: string;
	IsInsurance: boolean;
	VoucherItems: VoucherItem[];
	/**
	 * @pattern ^\d+$
	 */
	ExpressFee: string;
	shipmentTypeCode: string;
}

export interface B4mSkuItem {
	/**
	 * @pattern ^\d+$
	 */
	newOrderId: string;
	/**
	 * @pattern ^\d+$
	 */
	newOrderItemId: string;
	/**
	 * @pattern ^\d+$
	 */
	oldOrderId: string;
	/**
	 * @pattern ^\d+$
	 */
	orderDate: string;
	sku: SkuItem;
}

export interface RpcCalcBillForUserSubmitBuy4MeResp {
	payBill: PayBill;
}

export interface RpcGetOrderSimpleItemsReq {
	items: OrderItemIdMapping[];
	catalogCode: string;
}

export interface OrderItemIdMapping {
	/**
	 * @pattern ^\d+$
	 */
	newOrderId: string;
	/**
	 * @pattern ^\d+$
	 */
	newOrderItemId: string;
}

export interface RpcGetOrderSimpleItemsResp {
	result: Result;
	items: OrderItemSimpleInfo[];
}

export interface OrderItemSimpleInfo {
	/**
	 * @pattern ^\d+$
	 */
	orderId: string;
	/**
	 * @pattern ^\d+$
	 */
	orderItemId: string;
	/**
	 * @pattern ^\d+$
	 */
	regionId: string;
	/**
	 * @pattern ^\d+$
	 */
	shipmentTypeId: string;
	/**
	 * @pattern ^\d+$
	 */
	gpid: string;
	skuId: string;
	/**
	 * @pattern ^\d+$
	 */
	qty: string;
	/**
	 * @pattern ^\d+$
	 */
	chargeWeight: string;
}

export interface SetReOrderBindDiscountReq {
	/**
	 * @pattern ^\d+$
	 */
	oldOrderId: string;
	/**
	 * @pattern ^\d+$
	 */
	discountRate: string;
	discountType: DiscountType;
	catalog: string;
}

export interface GetReOrderBindDiscountsReq {
	/**
	 * @pattern ^\d+$
	 */
	oldOrderId: string;
	catalog: string;
}

export interface GetReOrderBindDiscountsResp {
	discounts: SetReOrderBindDiscountReq[];
}

export interface RpcGetB4MDetailActivityReq {
	Catalog: string;
	Client: string;
	/**
	 * @pattern ^\d+$
	 */
	OrderId: string;
}

export interface RpcGetB4MDetailActivityResp {
	Result: Result;
	ActivityNames: string[];
}

export interface NotifyPickupReq {
	packageNumber: string;
	/**
	 * @pattern ^\d+$
	 */
	packageId: string;
	/**
	 * @pattern ^\d+$
	 */
	newBillId: string;
	/**
	 * @pattern ^\d+$
	 */
	paymentBillId: string;
	paymentNumber: string;
}

export interface GetShopBackDataReq {
	/**
	 * @pattern ^\d+$
	 */
	orderId: string;
}

export interface GetShopBackDataResp {
	result: Result;
	/**
	 * @pattern ^\d+$
	 */
	orderId: string;
	isNewCustomer: boolean;
	data: ShopBackData[];
}

export interface ShopBackData {
	/**
	 * @pattern ^\d+$
	 */
	orderItemId: string;
	/**
	 * @pattern ^\d+$
	 */
	amount: string;
	category: string;
}

export function AddMultiOrder(payload: Partial<AddMultiOrderReq>) {
	return webapi<AddMultiOrderResp>("ezOrder.OrderService/AddMultiOrder", payload);
}

export function UserGetLastOrders(payload: Partial<UserGetLastOrdersReq>) {
	return webapi<UserGetLastOrdersResp>("ezOrder.OrderService/UserGetLastOrders", payload);
}

export function RpcGetOrdersViaDuration(payload: Partial<RpcGetOrdersViaDurationReq>) {
	return webapi<RpcGetOrdersViaDurationResp>(
		"ezOrder.OrderService/RpcGetOrdersViaDuration",
		payload
	);
}

export function RpcCalcBill(payload: Partial<RpcCalcBillReq>) {
	return webapi<RpcCalcBillResp>("ezOrder.OrderService/RpcCalcBill", payload);
}

export function RpcCalcCreateOrders(payload: Partial<RpcCalcCreateOrdersReq>) {
	return webapi<RpcCalcCreateOrdersResp>("ezOrder.OrderService/RpcCalcCreateOrders", payload);
}

export function RpcPayNewBillAfterChekcout(payload: Partial<RpcPayNewBillAfterChekcoutReq>) {
	return webapi<RpcPayNewBillAfterChekcoutResp>(
		"ezOrder.OrderService/RpcPayNewBillAfterChekcout",
		payload
	);
}

export function RpcModifyOrderItemsInfo(payload: Partial<RpcModifyOrderItemsInfoReq>) {
	return webapi<RpcModifyOrderItemsInfoResp>(
		"ezOrder.OrderService/RpcModifyOrderItemsInfo",
		payload
	);
}

export function RpcCancelPayment(payload: Partial<RpcCancelPaymentReq>) {
	return webapi<RpcCancelPaymentResp>("ezOrder.OrderService/RpcCancelPayment", payload);
}

export function RpcGetCancelOrder(payload: Partial<RpcGetCancelOrderReq>) {
	return webapi<RpcGetCancelOrderResp>("ezOrder.OrderService/RpcGetCancelOrder", payload);
}

export function RpcCancelOrder(payload: Partial<RpcCancelOrderReq>) {
	return webapi<RpcCancelOrderResp>("ezOrder.OrderService/RpcCancelOrder", payload);
}

export function RpcGetOrderBalance(payload: Partial<RpcGetOrderBalanceReq>) {
	return webapi<RpcGetOrderBalanceResp>("ezOrder.OrderService/RpcGetOrderBalance", payload);
}

export function RpcAddOrderBalance(payload: Partial<RpcAddOrderBalanceReq>) {
	return webapi<RpcAddOrderBalanceResp>("ezOrder.OrderService/RpcAddOrderBalance", payload);
}

export function RpcCancelOrderBalance(payload: Partial<RpcCancelOrderBalanceReq>) {
	return webapi<RpcCancelOrderBalanceResp>("ezOrder.OrderService/RpcCancelOrderBalance", payload);
}

export function RpcPayOrderBalance(payload: Partial<RpcPayOrderBalanceReq>) {
	return webapi<RpcPayOrderBalanceResp>("ezOrder.OrderService/RpcPayOrderBalance", payload);
}

export function RpcModifyShipmentType(payload: Partial<RpcModifyShipmentTypeReq>) {
	return webapi<RpcModifyShipmentTypeResp>("ezOrder.OrderService/RpcModifyShipmentType", payload);
}

export function RpcModifyWarehouse(payload: Partial<RpcModifyWarehouseReq>) {
	return webapi<RpcModifyWarehouseResp>("ezOrder.OrderService/RpcModifyWarehouse", payload);
}

export function RpcGetOffsets(payload: Partial<RpcGetOffsetsReq>) {
	return webapi<RpcGetOffsetsResp>("ezOrder.OrderService/RpcGetOffsets", payload);
}

export function RpcGetOrderItemsOriginTotalAmount(
	payload: Partial<RpcGetOrderItemsOriginTotalAmountReq>
) {
	return webapi<RpcGetOrderItemsOriginTotalAmountResp>(
		"ezOrder.OrderService/RpcGetOrderItemsOriginTotalAmount",
		payload
	);
}

export function RpcGetOrderCouponRecord(payload: Partial<RpcGetOrderCouponRecordReq>) {
	return webapi<RpcGetOrderCouponRecordResp>(
		"ezOrder.OrderService/RpcGetOrderCouponRecord",
		payload
	);
}

export function RpcGetBills(payload: Partial<RpcGetBillsReq>) {
	return webapi<RpcGetBillsResp>("ezOrder.OrderService/RpcGetBills", payload);
}

export function RpcCalcBillForUserSubmitBuy4Me(
	payload: Partial<RpcCalcBillForUserSubmitBuy4MeReq>
) {
	return webapi<RpcCalcBillResp>("ezOrder.OrderService/RpcCalcBillForUserSubmitBuy4Me", payload);
}

export function RpcCreateOrderForUserSubmitBuy4Me(
	payload: Partial<RpcCreateOrderForUserSubmitBuy4MeReq>
) {
	return webapi<RpcCreateOrderForUserSubmitBuy4MeResp>(
		"ezOrder.OrderService/RpcCreateOrderForUserSubmitBuy4Me",
		payload
	);
}

export function RpcGetOrderSimpleItems(payload: Partial<RpcGetOrderSimpleItemsReq>) {
	return webapi<RpcGetOrderSimpleItemsResp>("ezOrder.OrderService/RpcGetOrderSimpleItems", payload);
}

export function RpcModifyChargeWeight(payload: Partial<RpcModifyChargeWeightReq>) {
	return webapi<RpcModifyChargeWeightResp>("ezOrder.OrderService/RpcModifyChargeWeight", payload);
}

export function SetReOrderBindDiscount(payload: Partial<SetReOrderBindDiscountReq>) {
	return webapi<CommonEmpty>("ezOrder.OrderService/SetReOrderBindDiscount", payload);
}

export function GetReOrderBindDiscounts(payload: Partial<GetReOrderBindDiscountsReq>) {
	return webapi<GetReOrderBindDiscountsResp>(
		"ezOrder.OrderService/GetReOrderBindDiscounts",
		payload
	);
}

export function RpcGetOrderItemActivityAmount(payload: Partial<RpcGetOrderItemActivityAmountReq>) {
	return webapi<RpcGetOrderItemActivityAmountResp>(
		"ezOrder.OrderService/RpcGetOrderItemActivityAmount",
		payload
	);
}

export function RpcGetB4MDetailActivity(payload: Partial<RpcGetB4MDetailActivityReq>) {
	return webapi<RpcGetB4MDetailActivityResp>(
		"ezOrder.OrderService/RpcGetB4MDetailActivity",
		payload
	);
}

export function RpcOrderBackToCart(payload: Partial<RpcOrderBackToCartReq>) {
	return webapi<RpcOrderBackToCartResp>("ezOrder.OrderService/RpcOrderBackToCart", payload);
}

export function RpcSetOrderItemsStatusFinish(payload: Partial<RpcSetOrderItemsStatusFinishReq>) {
	return webapi<RpcSetOrderItemsStatusFinishResp>(
		"ezOrder.OrderService/RpcSetOrderItemsStatusFinish",
		payload
	);
}

export function RpcPayCancelBill(payload: Partial<RpcPayCancelBillReq>) {
	return webapi<RpcPayCancelBillResp>("ezOrder.OrderService/RpcPayCancelBill", payload);
}

export function PayOrderBill(payload: Partial<PayOrderBillReq>) {
	return webapi<PayOrderBillResp>("ezOrder.OrderService/PayOrderBill", payload);
}

export function CancelOrderBill(payload: Partial<CancelOrderBillReq>) {
	return webapi<CancelOrderBillResp>("ezOrder.OrderService/CancelOrderBill", payload);
}

export function RpcB4MSubmitNotifyPickup(payload: Partial<NotifyPickupReq>) {
	return webapi<CommonEmpty>("ezOrder.OrderService/RpcB4MSubmitNotifyPickup", payload);
}

export function GetShopBackData(payload: Partial<GetShopBackDataReq>) {
	return webapi<GetShopBackDataResp>("ezOrder.OrderService/GetShopBackData", payload);
}

export function RpcReOrderViaOrderIdItemIdsOrOffsetBillId(
	payload: Partial<RpcReOrderViaOrderIdItemIdsOrOffsetBillIdReq>
) {
	return webapi<RpcReOrderViaOrderIdItemIdsOrOffsetBillIdResp>(
		"ezOrder.OrderService/RpcReOrderViaOrderIdItemIdsOrOffsetBillId",
		payload
	);
}

export default {
	AddMultiOrder,
	UserGetLastOrders,
	RpcGetOrdersViaDuration,
	RpcCalcBill,
	RpcCalcCreateOrders,
	RpcPayNewBillAfterChekcout,
	RpcModifyOrderItemsInfo,
	RpcCancelPayment,
	RpcGetCancelOrder,
	RpcCancelOrder,
	RpcGetOrderBalance,
	RpcAddOrderBalance,
	RpcCancelOrderBalance,
	RpcPayOrderBalance,
	RpcModifyShipmentType,
	RpcModifyWarehouse,
	RpcGetOffsets,
	RpcGetOrderItemsOriginTotalAmount,
	RpcGetOrderCouponRecord,
	RpcGetBills,
	RpcCalcBillForUserSubmitBuy4Me,
	RpcCreateOrderForUserSubmitBuy4Me,
	RpcGetOrderSimpleItems,
	RpcModifyChargeWeight,
	SetReOrderBindDiscount,
	GetReOrderBindDiscounts,
	RpcGetOrderItemActivityAmount,
	RpcGetB4MDetailActivity,
	RpcOrderBackToCart,
	RpcSetOrderItemsStatusFinish,
	RpcPayCancelBill,
	PayOrderBill,
	CancelOrderBill,
	RpcB4MSubmitNotifyPickup,
	GetShopBackData,
	RpcReOrderViaOrderIdItemIdsOrOffsetBillId
};
