// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stock.proto

/*
Package stock is a generated protocol buffer package.

It is generated from these files:
	stock.proto

It has these top-level messages:
	EastMoneyPage
	EastMoneyData
	CodeData
	BasicData
	AmountUnit
	Funds
	FundsData
	MainInfo
	DBFunds
	DBFundsData
	StockCode
	StockCodePage
	GetCodeByOffsetDataList
	CodeByOffsetData
*/
package stock

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EastMoneyPage struct {
}

func (m *EastMoneyPage) Reset()                    { *m = EastMoneyPage{} }
func (m *EastMoneyPage) String() string            { return proto.CompactTextString(m) }
func (*EastMoneyPage) ProtoMessage()               {}
func (*EastMoneyPage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type EastMoneyData struct {
	Financecode       string  `protobuf:"bytes,1,opt,name=financecode" json:"financecode,omitempty"`
	Companycode       string  `protobuf:"bytes,2,opt,name=companycode" json:"companycode,omitempty"`
	Securityshortname string  `protobuf:"bytes,3,opt,name=securityshortname" json:"securityshortname,omitempty"`
	Securitycode      string  `protobuf:"bytes,4,opt,name=securitycode" json:"securitycode,omitempty"`
	Subcode           string  `protobuf:"bytes,5,opt,name=subcode" json:"subcode,omitempty"`
	Fxzl              int64   `protobuf:"varint,6,opt,name=fxzl" json:"fxzl,omitempty"`
	Wsfxsl            int64   `protobuf:"varint,7,opt,name=wsfxsl" json:"wsfxsl,omitempty"`
	Applyont          float32 `protobuf:"fixed32,8,opt,name=applyont" json:"applyont,omitempty"`
	IssuepriceMoney   float32 `protobuf:"fixed32,9,opt,name=issuepriceMoney" json:"issuepriceMoney,omitempty"`
	Issueprice        float32 `protobuf:"fixed32,10,opt,name=issueprice" json:"issueprice,omitempty"`
	Purchasedate      string  `protobuf:"bytes,11,opt,name=purchasedate" json:"purchasedate,omitempty"`
	Lwrandate         string  `protobuf:"bytes,15,opt,name=lwrandate" json:"lwrandate,omitempty"`
	Listingdate       string  `protobuf:"bytes,16,opt,name=listingdate" json:"listingdate,omitempty"`
	Peissuea          float32 `protobuf:"fixed32,17,opt,name=peissuea" json:"peissuea,omitempty"`
	Lwr               float32 `protobuf:"fixed32,18,opt,name=lwr" json:"lwr,omitempty"`
	// float cbxjrgbs = 19;
	Sc     string  `protobuf:"bytes,20,opt,name=sc" json:"sc,omitempty"`
	Mzyqgs float32 `protobuf:"fixed32,21,opt,name=mzyqgs" json:"mzyqgs,omitempty"`
	// float sgzs = 22;
	ApplyontMoney float32 `protobuf:"fixed32,23,opt,name=applyontMoney" json:"applyontMoney,omitempty"`
	// float averagelow = 24;
	Kb     string  `protobuf:"bytes,25,opt,name=kb" json:"kb,omitempty"`
	Zzf    float32 `protobuf:"fixed32,26,opt,name=zzf" json:"zzf,omitempty"`
	Sl     float32 `protobuf:"fixed32,27,opt,name=sl" json:"sl,omitempty"`
	Mzyqhl float32 `protobuf:"fixed32,28,opt,name=mzyqhl" json:"mzyqhl,omitempty"`
	// float totaliiqrplaceoff = 29;
	INDUSTRY string  `protobuf:"bytes,30,opt,name=INDUSTRY" json:"INDUSTRY,omitempty"`
	Close    float32 `protobuf:"fixed32,35,opt,name=Close" json:"Close,omitempty"`
	// float ChangePercent = 40;
	ZgsmsOrYxs string  `protobuf:"bytes,41,opt,name=ZgsmsOrYxs" json:"ZgsmsOrYxs,omitempty"`
	Url        string  `protobuf:"bytes,42,opt,name=Url" json:"Url,omitempty"`
	INDUSTRYPE float32 `protobuf:"fixed32,43,opt,name=INDUSTRYPE" json:"INDUSTRYPE,omitempty"`
	NewPrice   float32 `protobuf:"fixed32,44,opt,name=newPrice" json:"newPrice,omitempty"`
	Wszqjkr    string  `protobuf:"bytes,45,opt,name=wszqjkr" json:"wszqjkr,omitempty"`
	MAINBUSIN  string  `protobuf:"bytes,50,opt,name=MAINBUSIN" json:"MAINBUSIN,omitempty"`
	Ycwssgsx   float32 `protobuf:"fixed32,51,opt,name=ycwssgsx" json:"ycwssgsx,omitempty"`
	Ycwssgzj   float32 `protobuf:"fixed32,52,opt,name=ycwssgzj" json:"ycwssgzj,omitempty"`
	Update     string  `protobuf:"bytes,53,opt,name=Update" json:"Update,omitempty"`
	Sgrqrow    float32 `protobuf:"fixed32,54,opt,name=sgrqrow" json:"sgrqrow,omitempty"`
}

func (m *EastMoneyData) Reset()                    { *m = EastMoneyData{} }
func (m *EastMoneyData) String() string            { return proto.CompactTextString(m) }
func (*EastMoneyData) ProtoMessage()               {}
func (*EastMoneyData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EastMoneyData) GetFinancecode() string {
	if m != nil {
		return m.Financecode
	}
	return ""
}

func (m *EastMoneyData) GetCompanycode() string {
	if m != nil {
		return m.Companycode
	}
	return ""
}

func (m *EastMoneyData) GetSecurityshortname() string {
	if m != nil {
		return m.Securityshortname
	}
	return ""
}

func (m *EastMoneyData) GetSecuritycode() string {
	if m != nil {
		return m.Securitycode
	}
	return ""
}

func (m *EastMoneyData) GetSubcode() string {
	if m != nil {
		return m.Subcode
	}
	return ""
}

func (m *EastMoneyData) GetFxzl() int64 {
	if m != nil {
		return m.Fxzl
	}
	return 0
}

func (m *EastMoneyData) GetWsfxsl() int64 {
	if m != nil {
		return m.Wsfxsl
	}
	return 0
}

func (m *EastMoneyData) GetApplyont() float32 {
	if m != nil {
		return m.Applyont
	}
	return 0
}

func (m *EastMoneyData) GetIssuepriceMoney() float32 {
	if m != nil {
		return m.IssuepriceMoney
	}
	return 0
}

func (m *EastMoneyData) GetIssueprice() float32 {
	if m != nil {
		return m.Issueprice
	}
	return 0
}

func (m *EastMoneyData) GetPurchasedate() string {
	if m != nil {
		return m.Purchasedate
	}
	return ""
}

func (m *EastMoneyData) GetLwrandate() string {
	if m != nil {
		return m.Lwrandate
	}
	return ""
}

func (m *EastMoneyData) GetListingdate() string {
	if m != nil {
		return m.Listingdate
	}
	return ""
}

func (m *EastMoneyData) GetPeissuea() float32 {
	if m != nil {
		return m.Peissuea
	}
	return 0
}

func (m *EastMoneyData) GetLwr() float32 {
	if m != nil {
		return m.Lwr
	}
	return 0
}

func (m *EastMoneyData) GetSc() string {
	if m != nil {
		return m.Sc
	}
	return ""
}

func (m *EastMoneyData) GetMzyqgs() float32 {
	if m != nil {
		return m.Mzyqgs
	}
	return 0
}

func (m *EastMoneyData) GetApplyontMoney() float32 {
	if m != nil {
		return m.ApplyontMoney
	}
	return 0
}

func (m *EastMoneyData) GetKb() string {
	if m != nil {
		return m.Kb
	}
	return ""
}

func (m *EastMoneyData) GetZzf() float32 {
	if m != nil {
		return m.Zzf
	}
	return 0
}

func (m *EastMoneyData) GetSl() float32 {
	if m != nil {
		return m.Sl
	}
	return 0
}

func (m *EastMoneyData) GetMzyqhl() float32 {
	if m != nil {
		return m.Mzyqhl
	}
	return 0
}

func (m *EastMoneyData) GetINDUSTRY() string {
	if m != nil {
		return m.INDUSTRY
	}
	return ""
}

func (m *EastMoneyData) GetClose() float32 {
	if m != nil {
		return m.Close
	}
	return 0
}

func (m *EastMoneyData) GetZgsmsOrYxs() string {
	if m != nil {
		return m.ZgsmsOrYxs
	}
	return ""
}

func (m *EastMoneyData) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *EastMoneyData) GetINDUSTRYPE() float32 {
	if m != nil {
		return m.INDUSTRYPE
	}
	return 0
}

func (m *EastMoneyData) GetNewPrice() float32 {
	if m != nil {
		return m.NewPrice
	}
	return 0
}

func (m *EastMoneyData) GetWszqjkr() string {
	if m != nil {
		return m.Wszqjkr
	}
	return ""
}

func (m *EastMoneyData) GetMAINBUSIN() string {
	if m != nil {
		return m.MAINBUSIN
	}
	return ""
}

func (m *EastMoneyData) GetYcwssgsx() float32 {
	if m != nil {
		return m.Ycwssgsx
	}
	return 0
}

func (m *EastMoneyData) GetYcwssgzj() float32 {
	if m != nil {
		return m.Ycwssgzj
	}
	return 0
}

func (m *EastMoneyData) GetUpdate() string {
	if m != nil {
		return m.Update
	}
	return ""
}

func (m *EastMoneyData) GetSgrqrow() float32 {
	if m != nil {
		return m.Sgrqrow
	}
	return 0
}

type CodeData struct {
	// 代号
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// 交易所
	Exchange string `protobuf:"bytes,2,opt,name=exchange" json:"exchange,omitempty"`
	// 简称
	Name string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	// 发行总数
	Fxzl int64 `protobuf:"varint,4,opt,name=fxzl" json:"fxzl,omitempty"`
	// 网上发行总数
	Wsfxsl int64 `protobuf:"varint,5,opt,name=wsfxsl" json:"wsfxsl,omitempty"`
	// 发行价格
	Issue float32 `protobuf:"fixed32,6,opt,name=issue" json:"issue,omitempty"`
	// 申购日期
	Purchase int64 `protobuf:"varint,7,opt,name=purchase" json:"purchase,omitempty"`
	// 发行市盈率
	Peissuea float32 `protobuf:"fixed32,8,opt,name=peissuea" json:"peissuea,omitempty"`
	// 行业信息
	Industry string `protobuf:"bytes,9,opt,name=industry" json:"industry,omitempty"`
	// 主营业务
	Mainbusin string `protobuf:"bytes,13,opt,name=mainbusin" json:"mainbusin,omitempty"`
	// 总涨幅
	Zzf float32 `protobuf:"fixed32,15,opt,name=zzf" json:"zzf,omitempty"`
	// 申购代码
	Security string `protobuf:"bytes,16,opt,name=security" json:"security,omitempty"`
	// 上市日期
	Listing int64 `protobuf:"varint,17,opt,name=listing" json:"listing,omitempty"`
	// 行业市盈率
	Industrype float32 `protobuf:"fixed32,20,opt,name=industrype" json:"industrype,omitempty"`
	// 首日收盘价
	Closing float32 `protobuf:"fixed32,21,opt,name=closing" json:"closing,omitempty"`
	// 每中一签获利
	Mzyqhl float32 `protobuf:"fixed32,22,opt,name=mzyqhl" json:"mzyqhl,omitempty"`
	// 连续一字板数量
	Sl float32 `protobuf:"fixed32,25,opt,name=sl" json:"sl,omitempty"`
	// 创建日期
	CreateTime int64 `protobuf:"varint,30,opt,name=createTime" json:"createTime,omitempty"`
	// 更新日期
	UpdateTime int64 `protobuf:"varint,31,opt,name=updateTime" json:"updateTime,omitempty"`
}

func (m *CodeData) Reset()                    { *m = CodeData{} }
func (m *CodeData) String() string            { return proto.CompactTextString(m) }
func (*CodeData) ProtoMessage()               {}
func (*CodeData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CodeData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CodeData) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *CodeData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CodeData) GetFxzl() int64 {
	if m != nil {
		return m.Fxzl
	}
	return 0
}

func (m *CodeData) GetWsfxsl() int64 {
	if m != nil {
		return m.Wsfxsl
	}
	return 0
}

func (m *CodeData) GetIssue() float32 {
	if m != nil {
		return m.Issue
	}
	return 0
}

func (m *CodeData) GetPurchase() int64 {
	if m != nil {
		return m.Purchase
	}
	return 0
}

func (m *CodeData) GetPeissuea() float32 {
	if m != nil {
		return m.Peissuea
	}
	return 0
}

func (m *CodeData) GetIndustry() string {
	if m != nil {
		return m.Industry
	}
	return ""
}

func (m *CodeData) GetMainbusin() string {
	if m != nil {
		return m.Mainbusin
	}
	return ""
}

func (m *CodeData) GetZzf() float32 {
	if m != nil {
		return m.Zzf
	}
	return 0
}

func (m *CodeData) GetSecurity() string {
	if m != nil {
		return m.Security
	}
	return ""
}

func (m *CodeData) GetListing() int64 {
	if m != nil {
		return m.Listing
	}
	return 0
}

func (m *CodeData) GetIndustrype() float32 {
	if m != nil {
		return m.Industrype
	}
	return 0
}

func (m *CodeData) GetClosing() float32 {
	if m != nil {
		return m.Closing
	}
	return 0
}

func (m *CodeData) GetMzyqhl() float32 {
	if m != nil {
		return m.Mzyqhl
	}
	return 0
}

func (m *CodeData) GetSl() float32 {
	if m != nil {
		return m.Sl
	}
	return 0
}

func (m *CodeData) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *CodeData) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

type BasicData struct {
	// 代码
	Code string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	// 类型
	Exchange string `protobuf:"bytes,2,opt,name=exchange" json:"exchange,omitempty"`
	// 日期, eg:20180314
	Date string `protobuf:"bytes,3,opt,name=date" json:"date,omitempty"`
	// 今开
	Opening int32 `protobuf:"varint,4,opt,name=opening" json:"opening,omitempty"`
	// 收盘
	Closing int32 `protobuf:"varint,5,opt,name=closing" json:"closing,omitempty"`
	// 成交量
	Volume int64 `protobuf:"varint,6,opt,name=volume" json:"volume,omitempty"`
	// 最高
	Highest int32 `protobuf:"varint,7,opt,name=highest" json:"highest,omitempty"`
	// 最低
	Lowest int32 `protobuf:"varint,8,opt,name=lowest" json:"lowest,omitempty"`
	// 内盘
	Inside int64 `protobuf:"varint,9,opt,name=inside" json:"inside,omitempty"`
	// 外盘
	Outside int64 `protobuf:"varint,10,opt,name=outside" json:"outside,omitempty"`
	// 换手率
	Turnover int64 `protobuf:"varint,11,opt,name=turnover" json:"turnover,omitempty"`
	// 成交额
	Trading int64 `protobuf:"varint,12,opt,name=trading" json:"trading,omitempty"`
	// 振幅
	Amplitude int64 `protobuf:"varint,13,opt,name=amplitude" json:"amplitude,omitempty"`
	// 委比 单位:%
	Entrust int64 `protobuf:"varint,14,opt,name=entrust" json:"entrust,omitempty"`
	// 量比
	AmountRatio int32 `protobuf:"varint,15,opt,name=amountRatio" json:"amountRatio,omitempty"`
	// 流通市值
	Circulated int64 `protobuf:"varint,16,opt,name=circulated" json:"circulated,omitempty"`
	// 总市值
	Total int64 `protobuf:"varint,17,opt,name=total" json:"total,omitempty"`
	// 市盈率MRQ
	PeRatio int32 `protobuf:"varint,18,opt,name=peRatio" json:"peRatio,omitempty"`
	// 市净率
	PbRatio int32 `protobuf:"varint,19,opt,name=pbRatio" json:"pbRatio,omitempty"`
	// 每股收益
	Income int32 `protobuf:"varint,20,opt,name=income" json:"income,omitempty"`
	// 每股净资产
	Per int32 `protobuf:"varint,21,opt,name=per" json:"per,omitempty"`
	// 总股本
	Equity int64 `protobuf:"varint,22,opt,name=equity" json:"equity,omitempty"`
	// 流通股本
	Flow int64 `protobuf:"varint,23,opt,name=flow" json:"flow,omitempty"`
}

func (m *BasicData) Reset()                    { *m = BasicData{} }
func (m *BasicData) String() string            { return proto.CompactTextString(m) }
func (*BasicData) ProtoMessage()               {}
func (*BasicData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *BasicData) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *BasicData) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *BasicData) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *BasicData) GetOpening() int32 {
	if m != nil {
		return m.Opening
	}
	return 0
}

func (m *BasicData) GetClosing() int32 {
	if m != nil {
		return m.Closing
	}
	return 0
}

func (m *BasicData) GetVolume() int64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *BasicData) GetHighest() int32 {
	if m != nil {
		return m.Highest
	}
	return 0
}

func (m *BasicData) GetLowest() int32 {
	if m != nil {
		return m.Lowest
	}
	return 0
}

func (m *BasicData) GetInside() int64 {
	if m != nil {
		return m.Inside
	}
	return 0
}

func (m *BasicData) GetOutside() int64 {
	if m != nil {
		return m.Outside
	}
	return 0
}

func (m *BasicData) GetTurnover() int64 {
	if m != nil {
		return m.Turnover
	}
	return 0
}

func (m *BasicData) GetTrading() int64 {
	if m != nil {
		return m.Trading
	}
	return 0
}

func (m *BasicData) GetAmplitude() int64 {
	if m != nil {
		return m.Amplitude
	}
	return 0
}

func (m *BasicData) GetEntrust() int64 {
	if m != nil {
		return m.Entrust
	}
	return 0
}

func (m *BasicData) GetAmountRatio() int32 {
	if m != nil {
		return m.AmountRatio
	}
	return 0
}

func (m *BasicData) GetCirculated() int64 {
	if m != nil {
		return m.Circulated
	}
	return 0
}

func (m *BasicData) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *BasicData) GetPeRatio() int32 {
	if m != nil {
		return m.PeRatio
	}
	return 0
}

func (m *BasicData) GetPbRatio() int32 {
	if m != nil {
		return m.PbRatio
	}
	return 0
}

func (m *BasicData) GetIncome() int32 {
	if m != nil {
		return m.Income
	}
	return 0
}

func (m *BasicData) GetPer() int32 {
	if m != nil {
		return m.Per
	}
	return 0
}

func (m *BasicData) GetEquity() int64 {
	if m != nil {
		return m.Equity
	}
	return 0
}

func (m *BasicData) GetFlow() int64 {
	if m != nil {
		return m.Flow
	}
	return 0
}

// 金额和单位
type AmountUnit struct {
	// 数量
	Amount float32 `protobuf:"fixed32,1,opt,name=amount" json:"amount,omitempty"`
	// 单位
	Unit string `protobuf:"bytes,2,opt,name=unit" json:"unit,omitempty"`
}

func (m *AmountUnit) Reset()                    { *m = AmountUnit{} }
func (m *AmountUnit) String() string            { return proto.CompactTextString(m) }
func (*AmountUnit) ProtoMessage()               {}
func (*AmountUnit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AmountUnit) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *AmountUnit) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

type Funds struct {
	// 错误码
	ErrorNo int32 `protobuf:"varint,1,opt,name=errorNo" json:"errorNo,omitempty"`
	// 错误描述
	ErrorMsg string `protobuf:"bytes,2,opt,name=errorMsg" json:"errorMsg,omitempty"`
	// 资金信息
	FundsData *FundsData `protobuf:"bytes,3,opt,name=fundsData" json:"fundsData,omitempty"`
}

func (m *Funds) Reset()                    { *m = Funds{} }
func (m *Funds) String() string            { return proto.CompactTextString(m) }
func (*Funds) ProtoMessage()               {}
func (*Funds) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Funds) GetErrorNo() int32 {
	if m != nil {
		return m.ErrorNo
	}
	return 0
}

func (m *Funds) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

func (m *Funds) GetFundsData() *FundsData {
	if m != nil {
		return m.FundsData
	}
	return nil
}

// 资金数据
type FundsData struct {
	// 流入
	MainInflow float64 `protobuf:"fixed64,1,opt,name=mainInflow" json:"mainInflow,omitempty"`
	// 流出
	MainOutflow float64 `protobuf:"fixed64,2,opt,name=mainOutflow" json:"mainOutflow,omitempty"`
	// 差值
	MainNet float64 `protobuf:"fixed64,3,opt,name=mainNet" json:"mainNet,omitempty"`
	// 百分比
	MainPCT int32 `protobuf:"varint,4,opt,name=mainPCT" json:"mainPCT,omitempty"`
	// 流入
	RetailInflow float64 `protobuf:"fixed64,5,opt,name=retailInflow" json:"retailInflow,omitempty"`
	// 流出
	RetailOutflow float64 `protobuf:"fixed64,6,opt,name=retailOutflow" json:"retailOutflow,omitempty"`
	// 散户净值
	RetailNet float64 `protobuf:"fixed64,7,opt,name=retailNet" json:"retailNet,omitempty"`
	// 百分比
	RetailPCT int32 `protobuf:"varint,8,opt,name=retailPCT" json:"retailPCT,omitempty"`
	// 净流出
	Outflow float64 `protobuf:"fixed64,9,opt,name=outflow" json:"outflow,omitempty"`
	// 日期
	Date string `protobuf:"bytes,10,opt,name=date" json:"date,omitempty"`
	// 主力信息
	MainInfo []*MainInfo `protobuf:"bytes,11,rep,name=mainInfo" json:"mainInfo,omitempty"`
}

func (m *FundsData) Reset()                    { *m = FundsData{} }
func (m *FundsData) String() string            { return proto.CompactTextString(m) }
func (*FundsData) ProtoMessage()               {}
func (*FundsData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *FundsData) GetMainInflow() float64 {
	if m != nil {
		return m.MainInflow
	}
	return 0
}

func (m *FundsData) GetMainOutflow() float64 {
	if m != nil {
		return m.MainOutflow
	}
	return 0
}

func (m *FundsData) GetMainNet() float64 {
	if m != nil {
		return m.MainNet
	}
	return 0
}

func (m *FundsData) GetMainPCT() int32 {
	if m != nil {
		return m.MainPCT
	}
	return 0
}

func (m *FundsData) GetRetailInflow() float64 {
	if m != nil {
		return m.RetailInflow
	}
	return 0
}

func (m *FundsData) GetRetailOutflow() float64 {
	if m != nil {
		return m.RetailOutflow
	}
	return 0
}

func (m *FundsData) GetRetailNet() float64 {
	if m != nil {
		return m.RetailNet
	}
	return 0
}

func (m *FundsData) GetRetailPCT() int32 {
	if m != nil {
		return m.RetailPCT
	}
	return 0
}

func (m *FundsData) GetOutflow() float64 {
	if m != nil {
		return m.Outflow
	}
	return 0
}

func (m *FundsData) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *FundsData) GetMainInfo() []*MainInfo {
	if m != nil {
		return m.MainInfo
	}
	return nil
}

// 信息
type MainInfo struct {
	// 日期
	Date string `protobuf:"bytes,1,opt,name=date" json:"date,omitempty"`
	// 金额
	Amount int32 `protobuf:"varint,2,opt,name=amount" json:"amount,omitempty"`
}

func (m *MainInfo) Reset()                    { *m = MainInfo{} }
func (m *MainInfo) String() string            { return proto.CompactTextString(m) }
func (*MainInfo) ProtoMessage()               {}
func (*MainInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *MainInfo) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *MainInfo) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

// 数据库储存
type DBFunds struct {
	// 代码
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// 资金信息
	Funds []*DBFundsData `protobuf:"bytes,2,rep,name=funds" json:"funds,omitempty"`
	// 创建时间
	Create int64 `protobuf:"varint,3,opt,name=create" json:"create,omitempty"`
	// 更新日期
	Update int64 `protobuf:"varint,4,opt,name=update" json:"update,omitempty"`
}

func (m *DBFunds) Reset()                    { *m = DBFunds{} }
func (m *DBFunds) String() string            { return proto.CompactTextString(m) }
func (*DBFunds) ProtoMessage()               {}
func (*DBFunds) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *DBFunds) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DBFunds) GetFunds() []*DBFundsData {
	if m != nil {
		return m.Funds
	}
	return nil
}

func (m *DBFunds) GetCreate() int64 {
	if m != nil {
		return m.Create
	}
	return 0
}

func (m *DBFunds) GetUpdate() int64 {
	if m != nil {
		return m.Update
	}
	return 0
}

// 数据库存储数据
type DBFundsData struct {
	// 流入
	Mi int32 `protobuf:"varint,1,opt,name=mi" json:"mi,omitempty"`
	// 流入
	Ri int32 `protobuf:"varint,2,opt,name=ri" json:"ri,omitempty"`
	// 流出
	Mo int32 `protobuf:"varint,3,opt,name=mo" json:"mo,omitempty"`
	// 流出
	Ro int32 `protobuf:"varint,4,opt,name=ro" json:"ro,omitempty"`
	// 日期
	Date string `protobuf:"bytes,5,opt,name=date" json:"date,omitempty"`
}

func (m *DBFundsData) Reset()                    { *m = DBFundsData{} }
func (m *DBFundsData) String() string            { return proto.CompactTextString(m) }
func (*DBFundsData) ProtoMessage()               {}
func (*DBFundsData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *DBFundsData) GetMi() int32 {
	if m != nil {
		return m.Mi
	}
	return 0
}

func (m *DBFundsData) GetRi() int32 {
	if m != nil {
		return m.Ri
	}
	return 0
}

func (m *DBFundsData) GetMo() int32 {
	if m != nil {
		return m.Mo
	}
	return 0
}

func (m *DBFundsData) GetRo() int32 {
	if m != nil {
		return m.Ro
	}
	return 0
}

func (m *DBFundsData) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

// 股票代码
type StockCode struct {
	// 代码
	Code string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	// 交易所
	Exchange string `protobuf:"bytes,2,opt,name=exchange" json:"exchange,omitempty"`
}

func (m *StockCode) Reset()                    { *m = StockCode{} }
func (m *StockCode) String() string            { return proto.CompactTextString(m) }
func (*StockCode) ProtoMessage()               {}
func (*StockCode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *StockCode) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *StockCode) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

// 股票代码翻页
type StockCodePage struct {
	// 当前页码
	Page int32 `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	// 页面大小
	Size int32 `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	// 总数
	Total int32 `protobuf:"varint,5,opt,name=total" json:"total,omitempty"`
	// 页面信息
	CodeList []*StockCode `protobuf:"bytes,10,rep,name=codeList" json:"codeList,omitempty"`
}

func (m *StockCodePage) Reset()                    { *m = StockCodePage{} }
func (m *StockCodePage) String() string            { return proto.CompactTextString(m) }
func (*StockCodePage) ProtoMessage()               {}
func (*StockCodePage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *StockCodePage) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *StockCodePage) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *StockCodePage) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *StockCodePage) GetCodeList() []*StockCode {
	if m != nil {
		return m.CodeList
	}
	return nil
}

// 翻页查询股票数据列表
type GetCodeByOffsetDataList struct {
	List []*CodeByOffsetData `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
}

func (m *GetCodeByOffsetDataList) Reset()                    { *m = GetCodeByOffsetDataList{} }
func (m *GetCodeByOffsetDataList) String() string            { return proto.CompactTextString(m) }
func (*GetCodeByOffsetDataList) ProtoMessage()               {}
func (*GetCodeByOffsetDataList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *GetCodeByOffsetDataList) GetList() []*CodeByOffsetData {
	if m != nil {
		return m.List
	}
	return nil
}

// 翻页查询股票数据
type CodeByOffsetData struct {
	// 代码ID
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// 名称
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// 交易所
	Exchange string `protobuf:"bytes,3,opt,name=exchange" json:"exchange,omitempty"`
}

func (m *CodeByOffsetData) Reset()                    { *m = CodeByOffsetData{} }
func (m *CodeByOffsetData) String() string            { return proto.CompactTextString(m) }
func (*CodeByOffsetData) ProtoMessage()               {}
func (*CodeByOffsetData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *CodeByOffsetData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CodeByOffsetData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CodeByOffsetData) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func init() {
	proto.RegisterType((*EastMoneyPage)(nil), "stock.EastMoneyPage")
	proto.RegisterType((*EastMoneyData)(nil), "stock.EastMoneyData")
	proto.RegisterType((*CodeData)(nil), "stock.CodeData")
	proto.RegisterType((*BasicData)(nil), "stock.BasicData")
	proto.RegisterType((*AmountUnit)(nil), "stock.AmountUnit")
	proto.RegisterType((*Funds)(nil), "stock.Funds")
	proto.RegisterType((*FundsData)(nil), "stock.FundsData")
	proto.RegisterType((*MainInfo)(nil), "stock.MainInfo")
	proto.RegisterType((*DBFunds)(nil), "stock.DBFunds")
	proto.RegisterType((*DBFundsData)(nil), "stock.DBFundsData")
	proto.RegisterType((*StockCode)(nil), "stock.StockCode")
	proto.RegisterType((*StockCodePage)(nil), "stock.StockCodePage")
	proto.RegisterType((*GetCodeByOffsetDataList)(nil), "stock.GetCodeByOffsetDataList")
	proto.RegisterType((*CodeByOffsetData)(nil), "stock.CodeByOffsetData")
}

func init() { proto.RegisterFile("stock.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x57, 0xc1, 0x72, 0xdb, 0x36,
	0x13, 0x1e, 0x91, 0xa6, 0x2d, 0x41, 0x71, 0xec, 0xf0, 0xcf, 0x9f, 0x20, 0x6e, 0x26, 0xf5, 0xb0,
	0x3d, 0xb8, 0x4d, 0x9a, 0x43, 0xd2, 0x66, 0x3a, 0xd3, 0x53, 0xec, 0x24, 0x1d, 0xcf, 0xd4, 0x8e,
	0x07, 0x89, 0x0f, 0xe9, 0x0d, 0xa6, 0x20, 0x09, 0x31, 0x49, 0xd0, 0x00, 0x18, 0x59, 0xea, 0xb3,
	0xf5, 0x19, 0xfa, 0x0e, 0x3d, 0xf5, 0x31, 0x3a, 0xbb, 0x00, 0x48, 0xca, 0xe9, 0x4c, 0xa7, 0x37,
	0x7c, 0xdf, 0x2e, 0x76, 0x81, 0xdd, 0x6f, 0x21, 0x8a, 0x8c, 0x8d, 0x55, 0xf9, 0xe5, 0xd3, 0x5a,
	0x2b, 0xab, 0xd2, 0x04, 0x41, 0xb6, 0x43, 0xb6, 0x5f, 0x73, 0x63, 0x4f, 0x54, 0x25, 0x96, 0x67,
	0x7c, 0x26, 0xb2, 0xdf, 0xb7, 0x7a, 0xcc, 0x2b, 0x6e, 0x79, 0xba, 0x4f, 0xc6, 0x53, 0x59, 0xf1,
	0x2a, 0x17, 0xb9, 0x9a, 0x08, 0x3a, 0xd8, 0x1f, 0x1c, 0x8c, 0x58, 0x9f, 0x02, 0x8f, 0x5c, 0x95,
	0x35, 0xaf, 0x96, 0xe8, 0x11, 0x39, 0x8f, 0x1e, 0x95, 0x3e, 0x21, 0x77, 0x8c, 0xc8, 0x1b, 0x2d,
	0xed, 0xd2, 0xcc, 0x95, 0xb6, 0x15, 0x2f, 0x05, 0x8d, 0xd1, 0xef, 0x73, 0x43, 0x9a, 0x91, 0x5b,
	0x81, 0xc4, 0x80, 0x1b, 0xe8, 0xb8, 0xc6, 0xa5, 0x94, 0x6c, 0x99, 0xe6, 0x02, 0xcd, 0x09, 0x9a,
	0x03, 0x4c, 0x53, 0xb2, 0x31, 0xbd, 0x5e, 0x15, 0x74, 0x73, 0x7f, 0x70, 0x10, 0x33, 0x5c, 0xa7,
	0xf7, 0xc8, 0xe6, 0xc2, 0x4c, 0xaf, 0x4d, 0x41, 0xb7, 0x90, 0xf5, 0x28, 0xdd, 0x23, 0x43, 0x5e,
	0xd7, 0xc5, 0x52, 0x55, 0x96, 0x0e, 0xf7, 0x07, 0x07, 0x11, 0x6b, 0x71, 0x7a, 0x40, 0x76, 0xa4,
	0x31, 0x8d, 0xa8, 0xb5, 0xcc, 0x05, 0x96, 0x83, 0x8e, 0xd0, 0xe5, 0x26, 0x9d, 0x3e, 0x22, 0xa4,
	0xa3, 0x28, 0x41, 0xa7, 0x1e, 0x03, 0xf7, 0xa9, 0x1b, 0x9d, 0xcf, 0xb9, 0x11, 0x13, 0x6e, 0x05,
	0x1d, 0xbb, 0xfb, 0xf4, 0xb9, 0xf4, 0x21, 0x19, 0x15, 0x0b, 0xcd, 0x2b, 0x74, 0xd8, 0x41, 0x87,
	0x8e, 0x80, 0x0a, 0x17, 0xd2, 0x58, 0x59, 0xcd, 0xd0, 0xbe, 0xeb, 0x2a, 0xdc, 0xa3, 0xe0, 0x26,
	0xb5, 0xc0, 0x9c, 0x9c, 0xde, 0x71, 0x37, 0x09, 0x38, 0xdd, 0x25, 0x71, 0xb1, 0xd0, 0x34, 0x45,
	0x1a, 0x96, 0xe9, 0x6d, 0x12, 0x99, 0x9c, 0xde, 0xc5, 0x30, 0x91, 0xc9, 0xa1, 0x3e, 0xe5, 0x6a,
	0x79, 0x35, 0x33, 0xf4, 0xff, 0xe8, 0xe4, 0x51, 0xfa, 0x35, 0xd9, 0x0e, 0xf5, 0x70, 0x15, 0xb8,
	0x8f, 0xe6, 0x75, 0x12, 0xa2, 0x5d, 0x5e, 0xd0, 0x07, 0x2e, 0xda, 0xe5, 0x05, 0xe4, 0x5b, 0xad,
	0xa6, 0x74, 0xcf, 0xe5, 0x5b, 0xad, 0xa6, 0x98, 0xaf, 0xa0, 0x5f, 0x20, 0x11, 0x99, 0x22, 0xe4,
	0x9b, 0x17, 0xf4, 0x61, 0x97, 0x6f, 0x8e, 0xfd, 0x38, 0x3e, 0x7d, 0x75, 0xfe, 0xee, 0x3d, 0xfb,
	0x40, 0x1f, 0x61, 0xbc, 0x16, 0xa7, 0x77, 0x49, 0x72, 0x54, 0x28, 0x23, 0xe8, 0x57, 0xb8, 0xc5,
	0x01, 0xa8, 0xfd, 0xaf, 0x33, 0x53, 0x9a, 0xb7, 0xfa, 0xc3, 0xb5, 0xa1, 0xdf, 0xe0, 0x9e, 0x1e,
	0x03, 0x67, 0x39, 0xd7, 0x05, 0xfd, 0x16, 0x0d, 0xb0, 0x84, 0x1d, 0x21, 0xe6, 0xd9, 0x6b, 0xfa,
	0xd8, 0x75, 0xab, 0x63, 0xe0, 0x0c, 0x95, 0x58, 0x9c, 0x61, 0x2f, 0x9f, 0xb8, 0x4a, 0x06, 0x0c,
	0xaa, 0x5b, 0x98, 0xd5, 0xd5, 0xc7, 0x4b, 0x4d, 0xbf, 0x73, 0xaa, 0xf3, 0x10, 0xfa, 0x77, 0xf2,
	0xf2, 0xf8, 0xf4, 0xf0, 0xfc, 0xdd, 0xf1, 0x29, 0x7d, 0xe6, 0xfa, 0xd7, 0x12, 0x10, 0x73, 0x99,
	0x2f, 0x8c, 0x99, 0x99, 0x6b, 0xfa, 0xdc, 0xc5, 0x0c, 0xb8, 0xb3, 0xad, 0x3e, 0xd2, 0xef, 0xfb,
	0xb6, 0xd5, 0x47, 0xa8, 0xd3, 0x79, 0x8d, 0x2d, 0xff, 0x01, 0x43, 0x7a, 0x84, 0xea, 0x9f, 0xe9,
	0x2b, 0xad, 0x16, 0xf4, 0x05, 0x6e, 0x09, 0x30, 0xfb, 0x2b, 0x26, 0xc3, 0x23, 0x35, 0x11, 0x38,
	0xba, 0xb7, 0x49, 0x24, 0x27, 0x7e, 0x62, 0x23, 0x39, 0x81, 0x54, 0xe2, 0x3a, 0x9f, 0xf3, 0x6a,
	0x16, 0xa6, 0xb4, 0xc5, 0x30, 0x36, 0xbd, 0xa9, 0xc4, 0x75, 0x3b, 0x4a, 0x1b, 0xff, 0x38, 0x4a,
	0xc9, 0xda, 0x28, 0xdd, 0x25, 0x09, 0xca, 0x0d, 0xe7, 0x2e, 0x62, 0x0e, 0xa0, 0x2c, 0xbd, 0xcc,
	0xfd, 0xe8, 0xb5, 0x78, 0x4d, 0xb2, 0xc3, 0x1b, 0x92, 0xdd, 0x23, 0x43, 0x59, 0x4d, 0x1a, 0x63,
	0xb5, 0x9b, 0xba, 0x11, 0x6b, 0x31, 0x94, 0xba, 0xe4, 0xb2, 0xba, 0x68, 0x8c, 0xac, 0xe8, 0xb6,
	0x2b, 0x75, 0x4b, 0x04, 0xf1, 0xed, 0x74, 0xe2, 0xdb, 0x23, 0xc3, 0xf0, 0x74, 0xf8, 0xc9, 0x69,
	0x31, 0x14, 0xd2, 0x4f, 0x11, 0x4e, 0x4d, 0xcc, 0x02, 0xc4, 0xa1, 0xf6, 0x19, 0x6b, 0x81, 0xa3,
	0x02, 0x43, 0xdd, 0x32, 0xb0, 0x33, 0x2f, 0x94, 0x81, 0x9d, 0x6e, 0x66, 0x02, 0xec, 0x89, 0xfb,
	0xde, 0x9a, 0xb8, 0xdd, 0x10, 0x3c, 0x68, 0x87, 0xe0, 0x11, 0x21, 0xb9, 0x16, 0xdc, 0x8a, 0xf7,
	0xb2, 0x14, 0x28, 0xf7, 0x98, 0xf5, 0x18, 0xb0, 0x37, 0xd8, 0x6e, 0xb4, 0x7f, 0xe9, 0xec, 0x1d,
	0x93, 0xfd, 0xb1, 0x41, 0x46, 0x87, 0xdc, 0xc8, 0x1c, 0x7b, 0x9d, 0x92, 0x8d, 0xde, 0xfb, 0x8c,
	0xeb, 0x7f, 0xeb, 0x37, 0x0a, 0xcb, 0xf7, 0x3b, 0xc8, 0x4a, 0xd5, 0xa2, 0x82, 0x3b, 0x41, 0xcb,
	0x13, 0x16, 0x60, 0xff, 0xb6, 0x89, 0xb3, 0xf4, 0x6e, 0xfb, 0x49, 0x15, 0x4d, 0x29, 0xfc, 0x83,
	0xeb, 0x11, 0xec, 0x98, 0xcb, 0xd9, 0x5c, 0x18, 0x8b, 0x8d, 0x4f, 0x58, 0x80, 0xb0, 0xa3, 0x50,
	0x0b, 0x30, 0x0c, 0xd1, 0xe0, 0x11, 0xf0, 0xb2, 0x32, 0x72, 0x22, 0xb0, 0xe3, 0x31, 0xf3, 0x08,
	0x4f, 0xd5, 0x58, 0x34, 0x10, 0xd7, 0x23, 0x0f, 0xe1, 0x7e, 0xb6, 0xd1, 0x95, 0xfa, 0x24, 0x34,
	0x3e, 0xaa, 0x31, 0x6b, 0x31, 0xec, 0xb2, 0x9a, 0x4f, 0xe0, 0xc4, 0xb7, 0xdc, 0x2e, 0x0f, 0x41,
	0x3f, 0xbc, 0xac, 0x0b, 0x69, 0x9b, 0x89, 0x40, 0xfd, 0xc4, 0xac, 0x23, 0x60, 0x9f, 0xa8, 0xac,
	0x6e, 0x8c, 0xa5, 0xb7, 0xdd, 0x3e, 0x0f, 0xe1, 0x11, 0xe6, 0xa5, 0x6a, 0x2a, 0xcb, 0xb8, 0x95,
	0x0a, 0x15, 0x96, 0xb0, 0x3e, 0x85, 0x1d, 0x95, 0x3a, 0x6f, 0x0a, 0x6e, 0xc5, 0x04, 0xb5, 0x06,
	0x1d, 0x6d, 0x19, 0x98, 0x11, 0xab, 0x2c, 0x2f, 0xbc, 0xd6, 0x1c, 0x80, 0x8c, 0xb5, 0x70, 0x31,
	0x53, 0x57, 0x29, 0x0f, 0xd1, 0x72, 0xe1, 0x2c, 0xff, 0xf3, 0x16, 0x07, 0x5d, 0xad, 0x72, 0x55,
	0x3a, 0x65, 0x26, 0xcc, 0x23, 0x50, 0x7f, 0x2d, 0x34, 0x2a, 0x32, 0x61, 0xb0, 0x04, 0x4f, 0x71,
	0xd5, 0x80, 0xf6, 0xef, 0xb9, 0xaa, 0x3a, 0x84, 0xb3, 0x5d, 0xa8, 0x05, 0xbe, 0xe8, 0x30, 0xdb,
	0x85, 0x5a, 0x64, 0x3f, 0x12, 0xf2, 0x12, 0xaf, 0x73, 0x5e, 0x49, 0xec, 0x87, 0xbb, 0x1c, 0x6a,
	0x2a, 0x62, 0x1e, 0xc1, 0xce, 0xa6, 0x92, 0xd6, 0x2b, 0x0a, 0xd7, 0x59, 0x49, 0x92, 0x37, 0x4d,
	0x35, 0x31, 0x58, 0x3e, 0xad, 0x95, 0x3e, 0x55, 0xb8, 0x2b, 0x61, 0x01, 0xa2, 0x18, 0x61, 0x79,
	0x62, 0x66, 0xad, 0x18, 0x3d, 0x4e, 0x9f, 0x92, 0xd1, 0x14, 0xb6, 0x83, 0x92, 0x51, 0x91, 0xe3,
	0x67, 0xbb, 0x4f, 0xdd, 0xe7, 0xca, 0x9b, 0xc0, 0xb3, 0xce, 0x25, 0xfb, 0x33, 0x22, 0xa3, 0xd6,
	0x00, 0x65, 0x87, 0xf9, 0x3f, 0xae, 0xf0, 0x42, 0x90, 0x76, 0xc0, 0x7a, 0x0c, 0x34, 0x0e, 0xd0,
	0xdb, 0xc6, 0xa2, 0x43, 0x84, 0x0e, 0x7d, 0x0a, 0x4e, 0x0d, 0xf0, 0x54, 0x58, 0xcc, 0x3e, 0x60,
	0x01, 0x06, 0xcb, 0xd9, 0xd1, 0xfb, 0x30, 0x12, 0x1e, 0xc2, 0xaf, 0xba, 0x16, 0x96, 0xcb, 0xc2,
	0xe7, 0x4d, 0x70, 0xe3, 0x1a, 0x07, 0xbf, 0x9f, 0x0e, 0x87, 0xdc, 0x9b, 0xe8, 0xb4, 0x4e, 0x82,
	0x20, 0x1d, 0x01, 0xf9, 0xb7, 0xd0, 0xa3, 0x23, 0x3a, 0x2b, 0x9c, 0xc1, 0x4d, 0x4c, 0x47, 0xf8,
	0xe1, 0xc0, 0xd8, 0x23, 0x77, 0x72, 0x0f, 0xdb, 0x01, 0x27, 0xbd, 0x01, 0x7f, 0x4c, 0x86, 0xbe,
	0x2e, 0x8a, 0x8e, 0xf7, 0xe3, 0x83, 0xf1, 0xb3, 0x1d, 0x5f, 0xe6, 0x13, 0x4f, 0xb3, 0xd6, 0x21,
	0x7b, 0x41, 0x86, 0x81, 0x6d, 0x83, 0x0d, 0x7a, 0xc1, 0x3a, 0x7d, 0x44, 0x4e, 0x83, 0x0e, 0x65,
	0x86, 0x6c, 0xbd, 0x3a, 0x74, 0x6a, 0xb8, 0xf9, 0x03, 0x74, 0x40, 0x12, 0x6c, 0x22, 0x8d, 0x30,
	0x79, 0xea, 0x93, 0x7b, 0x77, 0xec, 0xb2, 0x73, 0x80, 0xe0, 0xee, 0x29, 0xc4, 0x86, 0xc4, 0xcc,
	0x23, 0xe0, 0xdd, 0x13, 0xe8, 0x7f, 0x94, 0x3c, 0xca, 0x38, 0x19, 0xf7, 0xa2, 0x40, 0xe2, 0x52,
	0x7a, 0x05, 0x46, 0xa5, 0x04, 0xac, 0xa5, 0x3f, 0x67, 0xa4, 0x11, 0x97, 0x0a, 0x43, 0x83, 0x5d,
	0xa1, 0x5d, 0xf9, 0x0e, 0x47, 0xba, 0xbb, 0x6f, 0xd2, 0xdd, 0x37, 0xfb, 0x89, 0x8c, 0xde, 0xc1,
	0x71, 0x8f, 0xfc, 0x57, 0xe6, 0x7f, 0x79, 0x6e, 0xb3, 0xdf, 0xc8, 0x76, 0xbb, 0x19, 0x3e, 0xb4,
	0x21, 0x40, 0xcd, 0x67, 0xc2, 0x9f, 0x11, 0xd7, 0xc0, 0x19, 0xb9, 0x12, 0xfe, 0x9c, 0xb8, 0xee,
	0xde, 0x0c, 0xf7, 0xee, 0xfa, 0x37, 0xe3, 0x09, 0x19, 0x42, 0xca, 0x5f, 0xa4, 0xb1, 0x94, 0x60,
	0x2d, 0xc3, 0xbc, 0xb4, 0x59, 0x58, 0xeb, 0x91, 0xbd, 0x21, 0xf7, 0x7f, 0x16, 0x16, 0xc8, 0xc3,
	0xe5, 0xdb, 0xe9, 0xd4, 0x08, 0x0b, 0x45, 0x02, 0x53, 0xfa, 0x98, 0x6c, 0xc0, 0x2f, 0x1e, 0x1d,
	0x60, 0x90, 0xfb, 0x3e, 0xc8, 0x4d, 0x57, 0x86, 0x4e, 0x19, 0x23, 0xbb, 0x37, 0x2d, 0x9f, 0xb5,
	0x38, 0x7c, 0x47, 0x44, 0xbd, 0xef, 0x88, 0x7e, 0x61, 0xe2, 0xf5, 0xc2, 0x5c, 0x6c, 0xe2, 0xff,
	0x91, 0xe7, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x6b, 0xf9, 0x52, 0x49, 0x9e, 0x0c, 0x00, 0x00,
}
