/**
 * This file is auto-generated by protobufgen
 * Don't change manually
 */

import { Empty as CommonEmpty } from "../common/empty";
import webapi from "../webapi";

export enum TicketEntry {
	INVALID_ENTRY = "INVALID_ENTRY",
	SEARCH_ORDER = "SEARCH_ORDER",
	ISSUE_ORDER = "ISSUE_ORDER",
	FOLLOW_ORDER = "FOLLOW_ORDER",
	GUNBUSTER = "GUNBUSTER",
}


export enum TicketPlatform {
	INVALID_PLATFORM = "INVALID_PLATFORM",
	ERP = "ERP",
}


export enum RespParty {
	INVALID_RESP_PARTY = "INVALID_RESP_PARTY",
	SELLER_OR_BUYER = "SELLER_OR_BUYER",
	EZBUY = "EZBUY",
}


export enum TicketAction {
	INVALID_ACTION = "INVALID_ACTION",
	REVIEW_APPROVE = "REVIEW_APPROVE",
	REVIEW_REJECT = "REVIEW_REJECT",
	EDIT = "EDIT",
	CONFIRM_COMPLETE = "CONFIRM_COMPLETE",
	ASSIGN = "ASSIGN",
	CLOSE = "CLOSE",
	ADD_TRACKING_NO = "ADD_TRACKING_NO",
	REPLY = "REPLY",
	CONFIRM_SUBMIT = "CONFIRM_SUBMIT",
	EXCEPTION_HANDLE = "EXCEPTION_HANDLE",
}


export enum LastReplierType {
	INVALID = "INVALID",
	EZBUY_REPLY = "EZBUY_REPLY",
	PURCHASER_REPLY = "PURCHASER_REPLY",
}



export interface GetTicketDetailResp {
	ticketInfo: TicketM;
	ticketSkuInfo: TicketSkuInfo;
}

export interface PoInfo {
	poNumber: string;
	placeOrderAccount: string;
	placeOrderUserName: string;
	trackingNo: string;
	trackingStatus: string;
}

export interface TicketSkuInfo {
	/**
	 * @pattern ^\d+$
	 */
	orderID: string;
	/**
	 * @pattern ^\d+$
	 */
	orderItemID: string;
	productName: string;
	sku: string;
	/**
	 * @pattern ^\d+$
	 */
	qty: string;
	/**
	 * @pattern ^\d+$
	 */
	internalUnitPrice: string;
	vendorName: string;
	/**
	 * @pattern ^\d+$
	 */
	orderDate: string;
	purchaseOrderInfo: PoInfo[];
	productURL: string;
	/**
	 * @pattern ^\d+$
	 */
	gpid: string;
}

export interface CreateTicketReq {
	/**
	 * @pattern ^\d+$
	 */
	orderId: string;
	/**
	 * @pattern ^\d+$
	 */
	orderItemId: string;
	/**
	 * @pattern ^\d+$
	 */
	qty: string;
	/**
	 * @pattern ^\d+$
	 */
	amount: string;
	ticketEntry: TicketEntry;
	/**
	 * @pattern ^\d+$
	 */
	entryTicketTypeId: string;
	ticketPlatform: TicketPlatform;
	respParty: RespParty;
	ticketDescription: string;
	isTicketDescriptionLocal: boolean;
}

export interface CreateTicketsReq {
	items: CreateTicketReq[];
	createBy: string;
}

export interface GetEntryTicketTypesReq {
	entry: TicketEntry;
}

export interface IdName {
	/**
	 * @pattern ^\d+$
	 */
	id: string;
	name: string;
}

export interface IdNameList {
	items: IdName[];
}

export interface SearchFilter {
	/**
	 * @pattern ^\d+$
	 */
	ticketId: string;
	skuNo: string;
	handler: string;
	ticketEntry: TicketEntry;
	/**
	 * @pattern ^\d+$
	 */
	entryTicketTypeId: string;
	poNumber: string;
	taoBaoAccountNo: string;
	buyerAccount: string;
	/**
	 * @pattern ^\d+$
	 */
	ticketTagId: string;
	/**
	 * @pattern ^\d+$
	 */
	lastReplierTypeId: string;
	/**
	 * @pattern ^\d+$
	 */
	lastReplyDateBegin: string;
	/**
	 * @pattern ^\d+$
	 */
	lastReplyDateEnd: string;
	/**
	 * @pattern ^\d+$
	 */
	warehouseId: string;
	/**
	 * @pattern ^\d+$
	 */
	ticketStatusId: string;
	/**
	 * @pattern ^\d+$
	 */
	orderPurchaseDateBegin: string;
	/**
	 * @pattern ^\d+$
	 */
	orderPurchaseDateEnd: string;
	/**
	 * @pattern ^\d+$
	 */
	createDateBegin: string;
	/**
	 * @pattern ^\d+$
	 */
	createDateEnd: string;
	orderNo: string;
	/**
	 * @pattern ^\d+$
	 */
	offset: string;
	/**
	 * @pattern ^\d+$
	 */
	limit: string;
	buyerGroupName: string;
}

export interface TicketM {
	/**
	 * @pattern ^\d+$
	 */
	ticketId: string;
	/**
	 * @pattern ^\d+$
	 */
	createDate: string;
	poNumber: string;
	handler: string;
	buyerName: string;
	/**
	 * @pattern ^\d+$
	 */
	qty: string;
	/**
	 * @pattern ^\d+$
	 */
	amount: string;
	entryName: string;
	ticketTagName: string;
	ticketStatusName: string;
	/**
	 * @pattern ^\d+$
	 */
	returnQty: string;
	/**
	 * @pattern ^\d+$
	 */
	refundAmount: string;
	remark: string;
	productName: string;
	respPartyName: string;
	entryTicketTypeName: string;
	taoBaoAccountNo: string;
}

export interface Tickets {
	items: TicketM[];
}

export interface SubmitTicketActionReq {
	action: TicketAction;
	/**
	 * @pattern ^\d+$
	 */
	ticketIds: string[];
	handler: string;
	/**
	 * @pattern ^\d+$
	 */
	qty: string;
	/**
	 * @pattern ^\d+$
	 */
	amount: string;
	/**
	 * @pattern ^\d+$
	 */
	returnQty: string;
	/**
	 * @pattern ^\d+$
	 */
	refundAmount: string;
	logisticCompany: string;
	trackingNo: string;
	remark: string;
	lastReplierType: LastReplierType;
	content: string;
	IsContentLocal: boolean;
	submitUserName: string;
}

export interface GetReplyByTicketIdReq {
	/**
	 * @pattern ^\d+$
	 */
	ticketId: string;
}

export interface TicketReply {
	/**
	 * @pattern ^\d+$
	 */
	createDate: string;
	replierName: string;
	content: string;
}

export interface GetReplyByTicketIdResp {
	replies: TicketReply[];
}

export interface TicketId {
	/**
	 * @pattern ^\d+$
	 */
	ticketId: string;
}

export interface TicketLog {
	/**
	 * @pattern ^\d+$
	 */
	createDate: string;
	createBy: string;
	content: string;
}

export interface TicketLogs {
	items: TicketLog[];
}



export function CreateTickets(payload: Partial<CreateTicketsReq>) {
	return webapi<CommonEmpty>("ticket.Ticket/CreateTickets", payload);
}

export function GetEntryTicketTypes(payload: Partial<GetEntryTicketTypesReq>) {
	return webapi<IdNameList>("ticket.Ticket/GetEntryTicketTypes", payload);
}

export function GetTicketTags(payload: Partial<CommonEmpty>) {
	return webapi<IdNameList>("ticket.Ticket/GetTicketTags", payload);
}

export function GetReplierTypes(payload: Partial<CommonEmpty>) {
	return webapi<IdNameList>("ticket.Ticket/GetReplierTypes", payload);
}

export function GetTicketStatuses(payload: Partial<CommonEmpty>) {
	return webapi<IdNameList>("ticket.Ticket/GetTicketStatuses", payload);
}

export function Search(payload: Partial<SearchFilter>) {
	return webapi<Tickets>("ticket.Ticket/Search", payload);
}

export function SubmitTicketAction(payload: Partial<SubmitTicketActionReq>) {
	return webapi<CommonEmpty>("ticket.Ticket/SubmitTicketAction", payload);
}

export function GetReplyByTicketId(payload: Partial<GetReplyByTicketIdReq>) {
	return webapi<GetReplyByTicketIdResp>("ticket.Ticket/GetReplyByTicketId", payload);
}

export function GetLogsByTicketId(payload: Partial<TicketId>) {
	return webapi<TicketLogs>("ticket.Ticket/GetLogsByTicketId", payload);
}

export function GetTicketDetail(payload: Partial<TicketId>) {
	return webapi<GetTicketDetailResp>("ticket.Ticket/GetTicketDetail", payload);
}


export default {
	CreateTickets,
	GetEntryTicketTypes,
	GetTicketTags,
	GetReplierTypes,
	GetTicketStatuses,
	Search,
	SubmitTicketAction,
	GetReplyByTicketId,
	GetLogsByTicketId,
	GetTicketDetail,
};